/* Release #4.9.12, see https://dataconsole.kruxdigital.com/kruxjs_release_notes/#4.9.12*/
/* File modified at 02/22/2012 02:26:11 PM PST. md5 = 2819d818a5f0275386d26610039a1612 */
/* Copyright 2010-2012 Krux Digital, Inc. All Rights Reserved. No permission is granted to use, copy or modify this code. */
!window.krux_js&&-1<location.search.indexOf("krux_release")?function(){var h=location.search.match(/krux_release=(dev|stage)/);if(h)window.krux_js="http://kruxcontent-"+h[1]+".s3.amazonaws.com/krux.js?"+Math.random();else if(h=location.search.match(/krux_release=([\w.]+)/))window.krux_js="//cdn.krxd.net/kruxcontent/releases/krux-"+h[1]+".js";if(window.krux_js){window.console&&console.log&&console.log("Using "+window.krux_js);h=document.createElement("script");h.src=window.krux_js;var g=document.getElementsByTagName("script")[0];
g.parentNode.insertBefore(h,g)}}():window.KRUX||function(h,g,l){function y(a,b,c){if(b.rules)for(var a="tag_"+b.id,e=0;e<b.rules.length;++e){var f=b.rules[e],g=a+"_rule_"+e,f=[f.name,f.actual,f.operator,f.value,f.pass?"pass":"fail"].join("|");c[g]=f}}function M(a){q("config_requests");if(h.superTag.config)b.configOnload(h.superTag.config);else{var d={pubid:h.pubid,site:h.site,callback:"KRUX.configOnload"};"unpublished"==b.getRequestVal("krux_config")&&(d.state="unpublished",d.cache="false",d.cb=Math.random());
d=k.configUrl+"?"+A(d);b.configStartTime=(new Date).getTime();E(d,!a)}}function N(){var a=!1;b.ST.config?w.each(b.ST.config.tags||[],function(b){return w.each(b.rules||[],function(b){if("country"===b.name)return a=!0,w.breaker})}):a=!0;return a}var v={pubid:"",site:"",section:"",subsection:"",channels:"",async:!1,autoCollect:!0,autoInit:!0,pixelTime:1E3,reportErrors:!0,allTagsOffsite:!1,userAttributes:{},pageAttributes:{},trackSocial:!1};h||(h=v,g.KRUXSetup=h);for(var B in v)v.hasOwnProperty(B)&&
"undefined"==typeof h[B]&&(h[B]=v[B]);var C=(0===location.protocol.indexOf("http")?location.protocol:"http:")+"//services.krxd.net/",b={_kvs:{},_parameters:{},backgroundGets:[],blockUrl:C+"block.gif",collectors:[],collectUrl:C+"pixel.gif",socialUrl:C+"social.gif",eventUrl:C+"event.gif",eventsUrl:C+"stats",geo:{},geoUrl:C+"geoip?root_name=KRUX.geo",configCache:"na",debugLevel:0,errorUrl:C+"/jserror",loadedScripts:[],onloadCalled:!1,predbg:"",release:"4.9.12",scriptTimeout:2E4,sessionViews:0,sTag:/^<script((?:\s+[\w\-:]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,
userDataUrl:C+"/user_data/segments"},w=window.KRUX2=function(){function a(a){return!!(""===a||a&&a.charCodeAt&&a.substr)}function d(a,b){return function(){return a.apply(b,arguments)}}function c(){function a(){for(var d=0,c=arguments.length;d<c;++d)b.push(arguments[d]);return a}var b=[];a.data=function(){return b.join("")};return a}function e(a,b,d){var c=a.tagName,f=a.attributes||{},a=a.children||[],b=b||[],d=d||0,g=i[c];b("<",c);for(var h in f)b(" ",h,'="',f[h],'" ');if(g)return b("/>");b(">");
f=0;for(h=a.length;f<h;++f)e(a[f],b,d+1);g||b("</",c,">")}function f(b,d){a(b)&&(b={tagName:b,attributes:d});var f=new c;e(b,f);return f.data()}function h(a){var b=document.createElement("div");b.innerHTML=a;return b.childNodes}function l(a){var d=f.apply(null,arguments);b.literate()?document.write(d):document.body.appendChild(h(d)[0])}var s={},k=s.breaker={};s.each=function(a,b,d){if(a)if(a.length===+a.length)for(var c=0,e=a.length;c<e;c++){if(c in a&&b.call(d,a[c],c,a)===k)return k}else for(c in a)if(a.hasOwnProperty(c)&&
b.call(d,a[c],c,a)===k)return k;return null};var i=new function(a){for(var b=0;b<a.length;b++)this[a[b]]=!0}("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed".split(",")),j={},I=s.on=function(b,c,e,f){a(b)&&(f=e,e=c,c=b,b=null);f&&(e=d(e,f));b?b.addEventListener?b.addEventListener(c,e,!1):b.attachEvent&&b.attachEvent("on"+c,e):(j[c]||(j[c]=[])).push(e)},n=s.off=function(b,d,c){a(b)&&(c=d,d=b,b=null);b&&(b.removeEventListener?b.removeEventListener(d,c,!1):b.detachEvent&&
b.detachEvent(d,c))},o={},m=s.fire=function(a,b){var b=b||{},d=j[a]||[];b.type=a;o[a]=b;for(var c=0,e=d.length;c<e;++c)d[c](b)},p=s.hasFired=function(a){return o[a]},u=s.fireOnce=function(a,d){if(p(a)){if(b.debugLevel)throw"Double fireOnce";}else m(a,d)},K=s.waitFor=function(a,b,c){c&&(b=d(b,c));(c=p(a))?b(c):I(a,b)};s.waitForAll=function(b,c,e){function f(){if(!h){for(var a=0,d=b.length;a<d;++a)if(!p(b[a]))return;h=!0;c()}}a(b)&&(b=b.split(" "));if(a(c))var g=c,c=function(){u(g,e)};else e&&(c=d(c,
e));for(var h=!1,G=0,s=b.length;G<s;++G)K(b[G],f)};s.loadKuid=function(){function a(){u("kuid",{value:s.kuid})}function b(){function d(b){"http://cdn.krxd.net"===b.origin&&(n(window,"message",d),g.localStorage.kuid=s.kuid=b.data,a())}I(window,"message",d);l("iframe",{src:"//cdn.krxd.net/kruxcontent/xdomain.html",style:"display: none"})}s.kuid=g.localStorage&&g.localStorage.kuid;s.kuid?a():window.localStorage&&window.postMessage?b():a()};return s}(),n={};b._parameters=n;var m={};m.ua=navigator.userAgent.toLowerCase();
v=m.ua.match(/(webkit)[ \/]([\w.]+)/)||m.ua.match(/(opera)(?:.*version)?[ \/]([\w.]+)/)||m.ua.match(/(msie) ([\w.]+)/)||0>m.ua.indexOf("compatible")&&m.ua.match(/(mozilla)(?:.*? rv:([\w.]+))?/)||["","",0];m.browser=v[1];m.version=parseFloat((v[2]||"0").match(/^[0-9]+[.0-9]*/)[0],10);m.msie="msie"==v[1];m.mozilla="mozilla"==v[1];m.webkit="webkit"==v[1];m.opera="opera"==v[1];m.gecko=-1!=m.ua.indexOf("gecko/");m.chrome=!!g.chrome;v=g.screen.colorDepth;B=g.screen;m.res=8==v||16==v||24==v||32==v?[B.width,
B.height,v].join("x"):[B.width,B.height].join("x");b.is=b._is=m;b.is.awesome=!0;b.is.performance=g.performance&&g.performance.timing&&!(b.is.gecko&&9>b.is.version);b._=function(a){return l.getElementById(a)};var J=function(a,d,c){a=(a||"")+d.replace(/[^0-9A-Za-z_]/g,"_");return c?(c=b.toS(c).substring(0,542),n[a]=c,!0):n[a]},L=function(a,d){for(var c=b.keyValues(a),e=0;e<c.keys.length;e++)J(d,c.keys[e],c.values[e])};b.context=function(a,b){return J("_kcp_",a,b)};b.pageAttribute=function(a,b){return J("_kpa_",
a,b)};b.userAttribute=function(a,b){return J("_kua_",a,b)};b.afterLoadCallback=function(a){if(b.onloadCalled)return a();b.afterLoadFunctions||(b.afterLoadFunctions=[]);b.afterLoadFunctions.push(a);return null};b.trackSocial=function(){b.trackFacebook();b.trackTwitter()};b.trackFacebook=function(){g.FB&&g.FB.Event&&g.FB.Event.subscribe&&(g.FB.Event.subscribe("edge.create",function(a){var d=b.clone(n);d._ksoc_t="fb";d._ksoc_e="like";d._ksoc_url=a;D(h.socialUrl||b.socialUrl,d);q("facebook.like")}),g.FB.Event.subscribe("edge.remove",
function(a){var d=b.clone(n);d._ksoc_t="fb";d._ksoc_e="unlike";d._ksoc_url=a;D(h.socialUrl||b.socialUrl,d);q("facebook.unlike")}),g.FB.Event.subscribe("message.send",function(a){var d=b.clone(n);d._ksoc_t="fb";d._ksoc_e="send";d._ksoc_url=a;D(h.socialUrl||b.socialUrl,d);q("facebook.send")}))};b.trackTwitter=function(){g.twttr&&g.twttr.events&&g.twttr.events.bind&&g.twttr.events.bind("tweet",function(a){if(a){var d;a.target&&"IFRAME"==a.target.nodeName&&(d=b.getRequestVal("url","",H(a.target)));a=
b.clone(n);a._ksoc_t="twttr";a._ksoc_e="tweet";a._ksoc_url=d;D(h.socialUrl||b.socialUrl,a);q("twitter.tweet")}})};b.appendTag=function(a,b){var c=l.createElement(a),e;for(e in b)"string"==typeof e&&(c[e]=b[e]);if((e=l.getElementsByTagName("head"))&&e[0])e[0].appendChild(c);else{e=l.getElementsByTagName("script");for(var f=0,g=e.length;f<g;f++)if(e[f]&&e[f].parentNode){e[f].parentNode.insertBefore(c,e[f]);break}}return c};b.bool=function(a){return"string"==typeof a&&"false"===a.toLowerCase()||"0"===
a?!1:!!a};b.buildElement=function(a,d){for(var c=l.createElement(a),e=b.keyValues(d),f=0;f<e.keys.length;f++){var g,h;try{g=e.keys[f].replace(/[^A-Za-z0-9_]/g,"_").toLowerCase(),h=b.toS(e.values[f]).replace(/"/g,"&quot;"),c.setAttribute(g,h)}catch(s){}}return c};b.buildAttributes=function(a){for(var d=[],a=b.keyValues(a),c=0;c<a.keys.length;c++){var e,f;try{e=a.keys[c].replace(/[^A-Za-z0-9_]/g,"_").toLowerCase(),f=b.toS(a.values[c]).replace(/"/g,"&quot;"),d.push(e+'="'+f+'"')}catch(g){}}return d.join(" ")};
b.collectBeacon=function(){var a=r&&r.geo||null;a&&(n.geo_country=a.COUNTRY,n.geo_region=a.REGION,n.geo_city=a.CITY,n.geo_dma=a.DMA);if(r&&r.tags)for(var a=0,d=r.tags.length;a<d;a++)r.tags[a].started&&(k.loadSequence=k.loadSequence?k.loadSequence+1:1,n["kplt"+k.loadSequence]=r.tags[a].id,q("tags_loaded")),y(a,r.tags[a],n);n._knifr=g.frames.length;n._kpid=h.pubid;i.realtimeSegments();n._krtsegs=i._rsegments;b.context("s",h.site);b.context("sc",h.section);b.context("ssc",h.subSection);var c=g.performance;
b.is.performance&&(n.t_navigation_type=c.navigation.type,a=function(a,b){if(!c.timing[a]||!c.timing[b])return-1;var d=c.timing[b]-c.timing[a];return 0>d||3E4<d?-1:d},n.t_dns=a("domainLookupStart","domainLookupEnd"),n.t_tcp=a("connectStart","connectEnd"),n.t_http_request=a("requestStart","responseStart"),n.t_http_response=a("responseStart","responseEnd"),n.t_content_ready=a("navigationStart","domInteractive"),n.t_window_load=a("navigationStart","loadEventStart"),n.t_redirect=a("redirectStart","redirectEnd"));
D(h.collectUrl||b.collectUrl,n);O();w.fireOnce("collect_beacon")};b.clone=function(a){if("object"==typeof a&&null!==a){var d=new a.constructor,c;for(c in a)a.hasOwnProperty(c)&&(d[c]=b.clone(a[c]));return d}return a};(function(){function a(a,b){a._done||(a(b),a._done=1)}function d(a){var b;if("object"==typeof a)for(var d in a)a[d]&&(b={name:d,url:a[d]});else b=a.split("/"),b=b[b.length-1],d=b.indexOf("?"),b={name:-1!=d?b.substring(0,d):b,url:a};return(a=m[b.name])&&a.url===b.url?a:m[b.name]=b}function c(a,
b){if(a){"object"==typeof a&&(a=[].slice.call(a));for(var d=0;d<a.length;d++)b.call(a,a[d],d)}}function e(a){return"[object Function]"==Object.prototype.toString.call(a)}function f(a){var a=a||m,b=!1,d=0,c;for(c in a)if(a.hasOwnProperty(c)){if(a[c].state!=t)return!1;b=!0;d++}return b||0===d}function h(a){a.state=K;c(a.onpreload,function(a){a.call()})}function k(a,b,d){b.state||(b.state=q,b.node=a,b.onpreload=[],E(b.url,!1,function(){h(b)},d,a,"cache"))}function s(b,d,e){if(d.state==t&&e)return e(b);
if(d.state==v)return u.ready(d.name,e);if(d.state==q)return d.onpreload.push(function(){s(d,e)});d.state=v;d.node=b;E(d.url,!1,function(){d.state=t;e&&e(b);c(o[d.name],function(d){a(d,b)});j&&f()&&c(o.ALL,function(d){a(d,b)})});return!0}var i,j,n=[],I=[],o={},m={},p=!0===l.createElement("script").async||"MozAppearance"in l.documentElement.style||g.opera,r=g.head_conf&&g.head_conf.KRUXhead||"KRUXhead",u=g[r]=g[r]||function(){u.ready.apply(null,arguments)},K=0,q=1,v=2,t=3;u.js=p?function(){var b=arguments,
g=b[b.length-1],h=[],G=b[0],b=[].slice.call(b,1);e(g)||(g=null);c(b,function(c,e){c!=g&&(c=d(c),h.push(c),s(G,c,g&&e==b.length-2?function(){f(h)&&a(g,G)}:null))});return u}:function(){var a=arguments,b=a[0],f=[].slice.call(a,2),g=f[0];if(!i)return I.push(function(){u.js.apply(null,a)}),u;g?(c(f,function(a){e(a)||k(b,d(a))}),s(b,d(a[1]),e(g)?g:function(){u.js.apply(null,f)})):s(b,d(a[1]));return u};u.ready=function(b,d){if("dom"==b)return j?a(d):n.push(d),u;e(b)&&(d=b,b="ALL");var c=m[b];if(c&&c.state==
t||"ALL"==b&&f()&&j)return a(d),u;(c=o[b])?c.push(d):o[b]=[d];return u};u.ready("dom",function(){i&&f()&&c(o.ALL,function(b){a(b)});u.feature&&u.feature("domloaded",!0)});setTimeout(function(){i=!0;c(I,function(a){a()})},0);b.fireReady=function(){j||(j=!0,c(n,function(b){a(b)}))}})(document);(function(){var a=/^<([\w:]+)((?:\s+[\w\-:]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,d=/^<\/([\w:]+)[^>]*>/,c=/([\w:]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,
e=function(a){for(var b={},a=a.split(","),d=0;d<a.length;d++)b[a[d]]=!0;return b},f=e("area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed"),g=e("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,table,tbody,td,tfoot,th,thead,tr,ul"),h=e("a,abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,ins,kbd,label,map,object,q,s,samp,script,select,small,span,strike,strong,sub,sup,textarea,tt,u,var"),
s=e("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),l=e("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),k=e("script,style");b.HTMLParser=function(e,i,j){function n(a,d,e,k){if(g[d]||0===d.toLowerCase().indexOf("fb:"))for(;t.last()&&h[t.last()];)o("",t.last());s[d]&&t.last()==d&&o("",d);(k=f[d]||!!k)||t.push(d);if(j.start){var p=[];e.replace(c,function(a,b,d,c,e){a=d?d:c?c:e?e:l[b]?b:"";p.push({name:b,value:a,escaped:a.replace(/(^|[^\\])"/g,
'$1\\"')})});b.predbg+=" ";j.start&&-1==j.start(d,p,k,m,i,x)&&(i="");k&&(b.predbg=b.predbg.substr(0,b.predbg.length-1))}}function o(a,d){var c=0;if(d)for(c=t.length-1;0<=c&&!(t[c]==d);c--);if(0<=c){for(var e=t.length-1;e>=c;e--)j.end&&(-1==j.end(t[e],m,i)&&(i=""),b.predbg=b.predbg.substr(0,b.predbg.length-1));t.length=c}}var m=e,u="",p,r,q,t=[],v=i,w=0,x=this;t.last=function(){return this[this.length-1]};this.parse=function(b,c,e){m=b||m;"string"==typeof u&&(c=u+c);u="";for(v=i=c;i;){r=!0;if(!t.last()||
!k[t.last()]){if(0===i.indexOf("<\!--"))p=i.indexOf("--\>"),0<=p&&(e.comment&&-1==e.comment(i.substring(4,p),m,i)&&(i=""),i=i.substring(p+3),r=!1);else if(0===i.indexOf("</")){if(q=i.match(d))i=i.substring(q[0].length),q[0].replace(d,o),r=!1}else if(0===i.indexOf("<")&&(q=i.match(a)))i=i.substring(q[0].length),q[0].replace(a,n),r=!1;r&&(p=i.indexOf("<"),b=0>p?i:i.substring(0,p),i=0>p?"":i.substring(p),e.chars&&-1==e.chars(b,m,i)&&(i=""))}else if(-1!=i.indexOf("</"+t.last()+">")){var f=t.last();i=
i.replace(RegExp("([^\x00]*?)</"+t.last()+"[^>]*>","m"),function(a,b){b=b.replace(/<\!--(.*?)--\>/g,"$1").replace(/<!\[CDATA\[(.*?)\]\]>/g,"$1");"script"==t.last()&&w++;"script"==f&&t.pop();e.chars&&-1==e.chars(b,m,i,w,1)&&(i="");"script"==f&&t.push(f);"script"==t.last()&&w--;return""});o("",t.last())}if(i==v)return u=i;v=i}return""};this.setUnparsed=function(a){if("string"==typeof a||"number"==typeof a)u+=a+"";return u};i.length&&this.parse(m,i,j)}})();var x={blocklist:[],urlDisabled:!1};b.CM=x;
l.__krux_write_real=l.write;l.__krux_writeln=l.writeln;l.__krux_write=function(a){if(b.literate())return l.__krux_write_real(a);if(g.KRUXTest&&g.KRUXTest.throwDebugErrors)throw"FAILED to write to page, it's too late. rs="+l.readyState+": "+a;return!1};var o={scriptStack:[],insideStack:[],scriptParse:0,_src:void 0};b.tagWriter=o;o.setup=function(){o.setup.called||(o.setup.called=!0,l.write=l.writeln=o.docWrite=function(a,d){function c(a,d,i,k,j,s){for(var F={},n=a.toLowerCase(),m=0,q=d.length;m<q;m++){if(!h&&
("src"==d[m].name.toLowerCase()||"krux_deferred_src"==d[m].name.toLowerCase())&&x.checkBL(d[m].value))F.blocked_src=d[m].value,F.krux_blocked="1",x.recordBlock(d[m].value);else{if(("krux_deferred_src"==d[m].name.toLowerCase()||"src"==d[m].name.toLowerCase())&&"script"==n)o._src=d[m].value;F[d[m].name]=d[m].value}if(F.krux_blocked&&("img"==n||"iframe"==n))F.style="display: none"}if("script"==a){if((d=H(F))&&b.literate()){l.__krux_write('<script src="'+d+'"><\/script>');return}if(d){s.setUnparsed(j);
g.KRUXhead.js(void 0,d,function(){s.parse(k||o.node,"",{start:c,end:e,chars:f})});return}o.scripts++}a=b.buildElement(a,F);j=o.node;try{p.last()?j.appendChild(a):j.parentNode.insertBefore(a,j.nextSibling)}catch(r){}p.push(i?0:1);o.node=a}function e(){p.pop();p.last()&&(o.node=o.node.parentNode)}function f(a){var b=o.node;if(p.last())try{p.push(0),b.appendChild(l.createTextNode(a)),p.pop()}catch(d){b.text+=a}else try{o.node=b.parentNode.insertBefore(l.createTextNode(a),b.nextSibling)}catch(c){}}var h=
1>x.blocklist.length||x.urlDisabled;if(h&&b.literate())l.__krux_write(a);else if(a+="",0!==a.length){if(d){var i=o.node,k=p;o.node=d;p.length=0;p.push(1)}else{var j=l.getElementsByTagName("script");j.length!=o.scripts&&(o.scripts=j.length,o.node=j[j.length-1],p.push(0))}o.parser?o.parser.parse(d,a,{start:c,end:e,chars:f}):o.parser=new b.HTMLParser(d,a,{start:c,end:e,chars:f});d&&(o.node=i,p=k)}})};x.addToBL=function(a){x.blocklist.push(a.toLowerCase())};g.addToBlocklist=x.addToBL;x.checkBL=function(a){if("string"!=
typeof a)return 0;for(var a=a.toLowerCase().replace(/\?.+$/,""),b=0;b<x.blocklist.length;b++)if(a.match(RegExp(x.blocklist[b])))return 1;return 0};x.recordBlock=function(a){q("counter_measure_blocks");D(b.blockUrl+"?"+A({_kpid:h.pubid,_kcp_s:h.site,_kcp_sc:h.section,_kcp_ssc:h.subSection,_kurl_0:a}))};b.configOnload=function(a){r=a;b.ST.config=a;q("config_request_time",(new Date).getTime()-b.configStartTime,"ms");if(a.blocklist)for(var d=0;d<a.blocklist.length;d++)g.addToBlocklist(a.blocklist[d].pattern);
a.params&&(void 0!==a.params.max_slot_time&&(h.pixelTime=a.params.max_slot_time),h.autoCollect=b.bool(a.params.capture_leakage),h.captureErrors=b.bool(a.params.capture_js_errors),h.siteLevel=b.bool(a.params.site_level_supertag_config),a.params.control_tag_stats_prefix&&q("views."+a.params.control_tag_stats_prefix));if(a.services)for(var c in a.services)switch(c){case "userData":b.userDataUrl=a.services[c];break;case "stats":b.eventsUrl=a.services[c];break;case "monitor":b.errorUrl=a.services[c];break;
case "event":b.eventUrl=a.services[c];break;case "social":b.socialUrl=a.services[c];break;case "pixel":b.collectUrl=a.services[c]}a.blocklist&&0<a.blocklist.length&&o.setup();w.fireOnce("config_loaded")};b.d=function(a,d,c){var e=g.console,f=g.KRUXTest;if(!("object"!=typeof e||d>b.debugLevel)){if(f&&f.throwDebugErrors&&-1>=d)throw"KRUX.d reported an error: "+a;-2>=d?e.error?e.error("KRUX: "+a):e.log("KRUX ERROR: "+a):-1==d?e.warn?e.warn("KRUX: "+a):e.log("KRUX WARNING: "+a):1>=d?e.info?e.info("KRUX: "+
a):e.log("KRUX INFO: "+a):e.log("KRUX DEBUG: "+b.predbg+a);c&&e.dir&&e.dir(c)}};b.DART={};b.DART.parseZone=function(a){for(var b={},a=a.split("/"),c=0;c<a.length;c++)switch(c){case 0:b.site=a[c];break;case 1:b.section=a[c];break;case 2:b.subSection=a[c];break;default:b["subSection"+(c-1)]=a[c]}return b};b.DART.keyValues=function(a){for(var d={},c=a.split(";"),e=0;e<c.length;e++)(a=c[e].match(/(.+)=(.+)/))&&(25<a[1].length||(d[a[1]]=a[2]));return d=b.removeKeys(d,["sz","dcopt",/^ord/,"tile","pos",
/uri/,/click/,"ksgmnt",/null/,/undefined/])};b.DART.passDartKvsAsPageAttributes=function(a){var d=b.tagSrcWithMatchingDomain("ad.doubleclick.net","script")||b.tagSrcWithMatchingDomain("ad.doubleclick.net","iframe");if(!d)return{};var d=b.DART.keyValues(d),d=b.removeKeys(d,a),c;for(c in d)"string"==typeof c&&b.pageAttribute(c,d[c]);return d};b.passDartToKrux=b.DART.passDartKvsAsPageAttributes;b.genUid=function(){var a="abcdefghijklmnopqrstuvwxyz0123456789",b="ABCDEFGHIJKLMNOPQRSTUVWXYZ"+a+"-_",a=a.split(""),
b=b.split(""),c=function(a,b){for(var d=b.length,c,e=[];0<a;)c=a%d,a=Math.floor(a/d),e.push(b[c]);e.reverse();return e.join("")},e=(new Date).getTime()/1E3+""+Math.random().toString().substring(3,6)+"",e=e.substring(1,e.length-1),e=e.replace(".","");return function(e){return[c(e,b),c(e,a)]}(parseInt(e,10))};b.get2ndLevelDomain=function(a){var b=a.match(/https*:\/\/([^:\/]+)/),a=b?b[1].toLowerCase():a.toLowerCase();if(a.match(/^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/)||-1===a.indexOf("."))return a;
return(b=a.match(/([\w\-]{1,249}\.com*\.[a-z]{2})$/))?b[1]:(a=a.match(/([\w\-]{1,250}\.[a-z]{2,3})$/))?a[1]:!1};b.getBrowserLang=function(){var a=g.navigator;return(b.forcedLanguage||a.language||a.systemLanguage||a.browserLanguage||a.userLanguage||"").substring(0,2)};b.getCollectors=function(a){var d=function(a){var d=H(a);d&&(n._knpix=n._knpix?n._knpix+1:1,n["_kpix_"+b.collectors.length]=d.replace(/\?.+/,""),b.collectors.push(a))},c=function(a){for(var b={w:null,h:null},d=a.attributes,c=0,e=d.length;c<
e;c++)"height"==d[c].name.toLowerCase()?b.h=parseInt(d[c].value,10):"width"==d[c].name.toLowerCase()&&(b.w=parseInt(d[c].value,10));if(b.w&&b.h)return b;a.complete&&(b.w=a.width,b.h=a.height);return b};if(a.getElementsByTagName)for(var a=a.getElementsByTagName("img"),e=0,f=a.length;e<f;e++)if(b.isOffsiteTag(a[e])){var g=c(a[e]);(1===g.w&&1===g.h||0===g.w&&0===g.h)&&d(a[e])}};b.getRequestVal=function(a,d,c){c=b.parseQueryString(c||location.search);return a in c?c[a]:d};var D=function(a,d){d&&(a+="?"+
A(d));var c=b._is.ie&&6>=b._is.version?4E3:8E3;a.length>c&&(a=a.substring(0,c));(new Image).src=a;b.backgroundGets.push(a);return a};b.backgroundGet=D;var A=function(a,d){for(var c=[],e,f=b.keyValues(a),d=d||"&",g=0;g<f.keys.length;g++)e=b.toS(f.values[g]),c.push(encodeURIComponent(f.keys[g])+"="+encodeURIComponent(e));return c.join(d)};b.buildQueryString=A;b.cookie=function(a,b,c){if(1<arguments.length){c=c||{};b||(b="",c.expires=-1);var e="";if(c.expires&&("number"===typeof c.expires||c.expires.toUTCString))"number"==
typeof c.expires?(e=new Date,e.setTime(e.getTime()+1E3*c.expires)):e=c.expires,e="; expires="+e.toUTCString();var f=c.path?"; path="+c.path:"",g=c.domain?"; domain="+c.domain:"",h=c.secure?"; secure":"";l.cookie=[a,"=",encodeURIComponent(b),e,f,g,h].join("");return!0}return l.cookie?(e=l.cookie.match(RegExp(a+"=([^;]+)")))?unescape(e[1]):null:null};b.parseQueryString=function(a){var b=[];if(!a)return b;"?"===a.charAt(0)&&(a=a.substr(1));for(var a=a.replace(/\;/g,"&").replace(/\+/g,"%20"),a=a.split("&"),
c=0,e;c<a.length;c++)if(0!==a[c].length){var f="";e="";-1!=(e=a[c].indexOf("="))?(f=decodeURIComponent(a[c].substr(0,e)),e=decodeURIComponent(a[c].substr(e+1))):(f=decodeURIComponent(a[c]),e=!0);b[f]=e}return b};b.init=function(){h.subSection=h.subSection||h.subsection||h.sub_section;h.userAttributes=h.userData||h.userAttributes;var a=b.get2ndLevelDomain(l.domain);b.context("d",a);h.site=h.site||a;b.isInAdIframe()?n._inifr="true":l.referrer&&(n._kpref_=l.referrer);h.trackSocial&&b.afterLoadCallback(b.trackSocial);
"1c6ac852-8938-481a-84b8-4806affc8c13"==h.pubid&&(h.async=!0);a=b.S.get("kuid");a||(a=b.genUid()[0],b.S.set("kuid",a));n._kuid=a;L(h.userAttributes,"_kua_");L(h.pageAttributes,"_kpa_");g.sessionStorage&&(b.sessionViews=(parseInt(g.sessionStorage.kviews,10)||0)+1,g.sessionStorage.kviews=b.sessionViews,n.sview=b.sessionViews);a=l.getElementsByTagName("script");p.push(0);o.scripts=a.length;o.node=a[a.length-1]};var p=[];p.last=function(){return this[this.length-1]};p.p=p.pop;p.pop=function(){return this.p()};
p.s=p.push;p.push=function(a){return this.s(a)};b.inside=p;b.iframeContents=function(a,d){var c=function(a){var d=b.iframeDoc(b._(a));g.addEventListener?d.close():"interactive"==d.readyState?d.close():setTimeout(function(){c(a)},250)};"string"===typeof a&&(a=b._(a));if(!a)return void 0===d?!1:"";var e=b.iframeDoc(a);if(void 0===d)return e.body?e.body.innerHTML:"";var f="<html><head><title>"+l.title+"</title></head>",f=f+("<body><script>window.KRUX = window.parent.KRUX; window.KRUXSetup = window.parent.KRUXSetup;window.KRUXHTTP = window.parent.KRUXHTTP;<\/script>"+
d+"</body></html>");e.open();e.write(f);c(a.id);return!0};b.iframeDoc=function(a){try{if(a.contentDocument)return a.contentDocument;if(a.contentWindow)return a.contentWindow.document}catch(b){return!1}};var H=function(a){try{return a.src}catch(b){return""}};b.in_array=function(a,d,c){for(var d=b.keyValues(d),e=0;e<d.keys.length;e++)if(c){if(b.toS(d.values[e]).toLowerCase()==b.toS(a).toLowerCase())return!0}else if(d.values[e]==a)return!0;return!1};b.isIgnoredError=function(a){if("en"!=b.getBrowserLang())return!0;
for(var d=[/^Permission denied/,/Error loading script/,/Script error\./,/Access is denied/],c=0;c<d.length;c++)if(d[c].test(a))return!0;return!1};b.isInAdIframe=function(){if(g.self==g.top)return!1;var a=0,b=0,c=l.documentElement,e=l.body;if("number"==typeof g.innerWidth)a=g.innerWidth,b=g.innerHeight;else if(c&&(c.clientWidth||c.clientHeight))a=c.clientWidth,b=c.clientHeight;else if(e&&(e.clientWidth||e.clientHeight))a=e.clientWidth,b=e.clientHeight;return 18E4>=a*b};b.isOffsiteTag=function(a,d){var c=
H(a);if(!c)return!1;if(h.allTagsOffsite)return!0;if(!c.match(/https*:\/\//))return!1;var e=b.get2ndLevelDomain(d||l.domain);return b.get2ndLevelDomain(c)!=e};b.kv=function(a,d){return void 0!==d?b._kvs[a]=d:b._kvs[a]||h.userData&&h.userData[a]||h[a]||null};b.keyValues=function(a){var b=[],c=[],e;for(e in a)a.hasOwnProperty(e)&&(b.push(e),c.push(a[e]));return{keys:b,values:c}};b.literate=function(){if(h.async)return!1;var a=l.readyState;return"complete"==a||"loaded"==a||"interactive"==a&&(b._is.gecko||
b._is.webkit)?!1:!0};var i={_kuid:null,_segments:null,_responseData:null,serviceUrl:g.KRUXSetup&&h.segmentsServiceUrl||b.userDataUrl,usingCache:!1,cookieLifetime:2592E3,cacheLifetime:14400,realtimeSegmentLifetime:86400,loadOptions:{html5Storage:!0,varName:"ksgmnts"}};b.Segments=i;i.getEngine=function(){var a=j.HTML5;if(!i.loadOptions.html5Storage||!a.isSupported())a=j.Cookies;return a};i.load=function(a){var a=a||{},b;for(b in a)b in i.loadOptions&&(i.loadOptions[b]=a[b]);var c,a=i.getEngine();null!==
a.get(i.loadOptions.varName)&&(i.usingCache=!0,i._segments=a.get(i.loadOptions.varName),c=a.get(i.loadOptions.varName+"_lu"));i._kuid=a.get("kuid");i.realtimeSegments();i.load.called||(i.load.called=!0,!c||(new Date).getTime()/1E3-parseInt(c,36)>i.cacheLifetime?(c=i.serviceUrl+"?"+A({callback:"KRUX.Segments.callback",pubid:h.pubid}),E(c,!1),i.startTime=(new Date).getTime(),q("segment_requests")):w.fireOnce("segments_loaded"))};b.loadSegments=i.load;i.callback=function(a){q("segment_request_time",
(new Date).getTime()-i.startTime,"ms");i._kuid=a.kuid;if(a.segments){i._segments=a.segments.join(",");var a=b.timeStamp(),d=i.getEngine();d.set(i.loadOptions.varName,i._segments,i.cookieLifetime);d.set(i.loadOptions.varName+"_lu",a,i.cookieLifetime);d.set("kuid",i._kuid);w.fireOnce("segments_loaded")}};i.realtimeSegments=function(){if(r&&r.segments&&r.segments.length){for(var a=[],b=0,c=r.segments.length;b<c;b++)i.isValidSegment(r.segments[b])&&a.push(r.segments[b].segment_id);i._rsegments=a.join(",");
i.getEngine().set(i.loadOptions.varName+"_r",i._rsegments,i.realtimeSegmentLifetime)}};i.get=function(){var a=j,b=i._segments||a.HTML5.isSupported()&&a.HTML5.get(i.loadOptions.varName)||a.Cookies.get(i.loadOptions.varName)||"",a=a.HTML5.isSupported()&&a.HTML5.get(i.loadOptions.varName+"_r")||a.Cookies.get(i.loadOptions.varName+"_r")||"";return b.split(",").concat(a.split(",")).join(",").replace(/^,+/,"").replace(/,+$/,"")};b.getSegments=i.get;i.getKuid=function(){return i._kuid||j.HTML5.isSupported()&&
j.HTML5.get("kuid")||j.Cookies.get("kuid")||""};b.getKuid=i.getKuid;i.isValidSegment=function(a){function d(a,d){switch(a){case "user":return b.userAttribute(d)||"";case "page":return b.pageAttribute(d)||"";case "3rd party":return"";default:return""}}if(a.or&&a.or.length){for(var c=!1,e=0,f=a.or.length;e<f;e++){var g=d(a.or[e].type,a.or[e].name);if(b.in_array(g,a.or[e].values.split(","))){c=!0;break}}if(!c)return!1}if(a.and&&a.and.length){c=0;for(e=a.and.length;c<e;c++)if(f=d(a.and[c].type,a.and[c].name),
!b.in_array(f,a.and[c].values.split(",")))return!1}return!0};b.listen=function(a,b,c){return g.addEventListener?a.addEventListener(b,c,!1):g.attachEvent?a.attachEvent("on"+b,c):!1};b.load=function(a){b.literate()?b.listen(g,"load",a):a.call()};var E=function(a,d,c,e,f){b.loadedScripts.push(a);b.loadScript.sequence=b.loadScript.sequence?b.loadScript.sequence+1:1;var g="kscript_"+b.loadScript.sequence;if(a=H(a)||a)f={id:g,node:e,type:"text/"+(f||"javascript"),src:a},!1===h.async&&d&&b.literate()?(l.__krux_write("<script "+
b.buildAttributes(f)+"><\/script>"),"function"==typeof c&&c()):(f.async="true",b.appendTag("script",f),"function"==typeof c&&b.loadScriptCallback(g,c,e))};b.loadScript=E;b.loadScriptCallback=function(a,d,c){var e=b._(a);e?e.onreadystatechange=e.onload=function(){var a=e.readyState;if(!d.done&&(!a||/loaded|complete/.test(a)))d(c),d.done=!0}:setTimeout(function(){b.loadScriptCallback(a,d,c)},50)};b.loadTemplateTag=function(a,d){b.loadTemplateTag.td={};try{eval("KRUX.loadTemplateTag.td="+a)}catch(c){b.reportError("Error with tag template. "+
c.msg+"\n"+a,"email-template-tag");return}var e=b.loadTemplateTag.td;e.before&&e.before(d);var f=/@@([^@]+)@@/g,g=function(a,b){return d[b]?d[b]:a},h="",h="https:"==location.protocol&&e.sslHost?h+("//"+e.sslHost):h+("http://"+e.host),i=e.path.replace(f,g),h=h+i;if(e.query){for(var i=b.keyValues(e.query),j=0,k=i.keys.length;j<k;j++)e.query[i.keys[j]]=b.toS(i.values[j]).replace(f,g);h+=-1<h.indexOf("?")?"&":"?";h+=A(e.query)}E(h,!1,e.after)};b.makeDate=function(a){if("object"===typeof a&&null!==a&&
a.constructor==Date)return a;if(b.toS(a).match(/^[0-9]+$/))return!1;if(b.toS(a).match(/^([0-9]{4})-([0-9]{2})-([0-9]{2})/))return a=b.toS(a).match(/^([0-9]{4})-([0-9]{2})-([0-9]{2})/),new Date(a[1],a[2]-1,a[3]);if(Date.parse(a)){var d=new Date;d.setTime(Date.parse(a)+6E4*d.getTimezoneOffset());return d}return!1};b.metaTag=function(a){for(var b=l.getElementsByTagName("meta"),c=0,e=b.length;c<e;c++)if(b[c].name==a)return b[c].content;return null};b.onload=function(){if(!b.onloadCalled){b.onloadCalled=
!0;n.fired="load";if(b.afterLoadFunctions)for(var a=0;a<b.afterLoadFunctions.length;a++)b.afterLoadFunctions[a]();KRUX2.fireOnce("load_callbacks_finished");b.Storage.expunge(b.S);b.Storage.cleanup(b.S)}};b.onunload=function(){n.fired||(n.fired="unload",b.collectBeacon())};b.onbeforeunload=function(){n.fired||(n.fired="beforeunload",b.collectBeacon())};b.parseJSON=function(a){return g.JSON&&g.JSON.parse?g.JSON.parse(a):(new Function("return "+a))()};b.PM={};b.PM.supported=function(){return g.postMessage||
l.postMessage?!0:!1};b.PM.listen=function(a){return!b.PM.supported()?!1:b.listen(g,"message",a)};b.PM.send=function(a,d){if(!b.PM.supported())return!1;var c=b.toS(d);if(a.postMessage)return a.postMessage(c,"*");if(a.document.postMessage)return a.document.postMessage(c,"*")};b.Provider={};b.Provider.base={id:"base",getUrl:function(){throw"getUrl not implemented for provider: "+this.id;},checkForNew:86400,checkForUpdate:259200,blocking:!1,httpMethod:"script",noData:"no data"};b.Provider.base.cacheKey=
function(){return this.id+"_d"};b.Provider.base.run=function(){if(b.S.get(this.cacheKey())||!this.getUrl())return!1;"script"==this.httpMethod?E(this.getUrl(),this.blocking):"image"==this.httpMethod?D(this.getUrl()):"iframe"==this.httpMethod&&b.appendTag("iframe",{width:0,height:0,src:this.getUrl()});return!0};b.Provider.base.callback=function(a){var d;a?(a=A(a),d=this.checkForUpdate):(a=this.noData,d=this.checkForNew);b.S.set(this.cacheKey(),a,d)};b.Provider.base.getData=function(){var a=b.S.get(this.cacheKey());
return a==this.noData?null:b.parseQueryString(a)};b.Provider.serviceUrl=function(a,b){return C+"data."+(b||"gif")+"?_kdpid="+a};b.readyFunctions=[];b.ready=function(a){b.readyHasRun?a():b.readyFunctions.push(a)};b.readyRun=function(){if(!b.readyHasRun){b.readyHasRun=!0;for(var a=0;a<b.readyFunctions.length;a++)b.readyFunctions[a](g,[])}};b.doScrollHack=function(){if(!b.readyHasRun){try{l.documentElement.doScroll("left")}catch(a){setTimeout(b.doScrollHack,1);return}b.readyRun()}};b.readyBind=function(){if("complete"==
l.readyState)setTimeout(b.readyRun,1);else if(l.addEventListener)b.DOMContentLoaded=function(){l.removeEventListener("DOMContentLoaded",b.DOMContentLoaded,!1);b.readyRun()},b.listen(l,"DOMContentLoaded",b.DOMContentLoaded),b.listen(g,"load",b.readyRun);else if(l.attachEvent){b.DOMContentLoaded=function(){"complete"==l.readyState&&(l.detachEvent("onreadystatechange",b.DOMContentLoaded),b.readyRun())};b.listen(l,"readystatechange",b.DOMContentLoaded);g.attachEvent("onload",b.readyRun);var a=!1;try{a=
!g.frameElement}catch(d){}l.documentElement.doScroll&&a&&b.doScrollHack()}};b.readyBind();b.ready(b.fireReady);var z={},q=function(a,d,c){d=d||1;c=c||"c";"ms"==c&&3E4<d||(z[a]?"c"==z[a].type?z[a].value+=1:b.reportError("Trying to increment a time value - "+a):z[a]={type:c,value:d})},O=function(){if(g.KRUXTest)b.recorderEvents=z;else if(0.05<Math.random())return;var a=[],d;for(d in z)z.hasOwnProperty(d)&&a.push("controltag."+d+":"+z[d].value+"|"+z[d].type);b.backgroundGet(b.eventsUrl+"?q="+a.join(","))};
b.removeKeys=function(a,d){for(var c=b.clone(a),e=b.keyValues(c),f=0,g=d.length;f<g;f++)if("string"==typeof d[f])delete c[d[f]];else for(var h=0,i=e.keys.length;h<i;h++)"test"in d[f]&&d[f].test(e.keys[h])&&delete c[e.keys[h]];return c};b.reportError=function(a){if(window.KRUXTest)throw"reportError:"+a;q("jserror");m.browser&&(q("jserror."+m.browser),q("jserror."+m.browser+"."+m.version))};"function"!=typeof window.onerror&&(window.onerror=function(a,d,c){b.reportError("Error on line #"+c+" of "+d+
": "+a,"onerror");return!1});b.timeStamp=function(a){a=a||(new Date).getTime();return Math.round(a/1E3).toString(36)};var r=null,k={configUrl:"//cdn.krxd.net/config/",chains:{},executedTags:[]};b.ST=k;b.SuperTag=b.ST;b.ST.loadGeo=function(a){var d=b.ST;if("HTML5"==b.S.name){var c=b.S.get("kgeo");if(c){b.ST.geoFromCache=!0;try{b.geo=b.parseJSON(c)}catch(e){b.S.del("kgeo")}w.fireOnce("geo_loaded");return}}c=h.geoUrl||b.geoUrl;b.ST.loadGeo.startTime=(new Date).getTime();q("geo_requests");N()?b.loadScript(c,
!a,d.loadGeoSave):("HTML5"==b.S.name&&g.JSON&&b.loadScript(c,!1,d.loadGeoSave),w.fireOnce("geo_loaded"))};b.ST.loadGeoSave=function(){"HTML5"==b.S.name&&g.JSON&&j.HTML5.set("kgeo",g.JSON.stringify(b.geo),86400);q("geo_request_time",(new Date).getTime()-b.ST.loadGeo.startTime,"ms");w.fire("geo_loaded")};k.callTag=function(a,d){d||(k.sequence=k.sequence?k.sequence+1:1,d="krux_tag_"+a+"_"+k.sequence);if(!r)return!1;var c=k.gimmeTag(a);c.html_id=d;return!1===c?(b.reportError("No available tags for this format: "+
a+". If the format is valid, check to make sure you have a non-frequency capped tag at the bottom of the chain.","email-config"),!1):k.writeTag(c)};k.callAd=k.callTag;k.deliverPixels=function(){b.pixelsDelivered=0;if(!r)return!1;for(var a=r.tags||[],d=(new Date).getTime(),c=0,e=0;e<a.length;e++){c+=(new Date).getTime()-d;if(c>h.pixelTime)return w.fireOnce("pixels_delivered"),b.pixelsDelivered;var f=a[e];"0x0"==f.format&&k.isValidRules(f)&&!f.started&&(k.writeTag(f),b.pixelsDelivered++)}w.fireOnce("pixels_delivered");
return b.pixelsDelivered};k.invisibleTags=function(){};k.getCountry=function(){return b.getRequestVal("krux_country")?b.getRequestVal("krux_country"):h.forcedCountry?h.forcedCountry:b.geo&&b.geo.country||"Unknown"};b.getCountry=k.getCountry;k.gimmeTag=function(a){for(var d=b.getRequestVal("krux_tagid"),c=0;c<r.tags.length;c++){var e=r.tags[c];if(d&&e.format==a&&e.id==d||e.format==a&&k.isValidRules(e))return e}return!1};k.init=function(){var a=h.superTag;if(void 0!==a.enabled&&!b.bool(a.enabled))return!1;
M(h.async);b.ST.loadGeo(h.async);"function"===typeof h.initialize?h.initialize():h.initialize&&w.each(h.initialize,function(a){a()});w.waitForAll("config_loaded geo_loaded",function(){k.deliverPixels()});!0===h.autoCollect&&KRUX2.waitForAll("load_callbacks_finished pixels_delivered",function(){b.getCollectors(l);b.collectBeacon()});q("views");m.browser&&(q("views."+m.browser),q("views."+m.browser+"."+m.version));return!0};k.isValidCriteria=function(a,d,c){try{c.constructor==Array&&(c=c.toString())}catch(e){}var f=
b.toS(c).split(/, */);if(b.toS(d).match(/[<>]/))if(!isNaN(parseInt(a,10))&&!isNaN(parseInt(c,10)))a=parseInt(a,10),c=parseInt(c,10);else{if("string"!=typeof a||"string"!=typeof c)return null}else if(b.in_array(d,["before","after"])&&(a=b.makeDate(a),c=b.makeDate(c),!a||!c))return null;switch(d){case "=":return b.in_array(a,f,!0);case "!=":return!b.in_array(a,f,!0);case ">":return a>c;case "<":return a<c;case ">=":return a>=c;case "<=":return a<=c;case "before":return a.getTime()<c.getTime();case "after":return a.getTime()>
c.getTime();case "matches":var g;try{return g=0===b.toS(c).indexOf("/")?eval(c):RegExp(c),g.test(a)}catch(h){return!1}case "contains":a=b.toS(a);for(d=0;d<f.length;d++)if(-1<a.indexOf(f[d]))return!0;return!1;default:return b.d("Unrecognized operator: "+d,-1),null}};k.isValidRules=function(a){for(var d=k.isValidCriteria,c=a.rules?a.rules.length:0,e=0;e<c;e++){var f=a.rules[e];f.pass=!0;switch(f.name){case "country":if(d(f.actual=k.getCountry(),f.operator,f.value))break;else return a.rejected="country",
f.pass=!1;case "site":if(d(f.actual=h.site,f.operator,f.value))break;else return a.rejected="site",f.pass=!1;case "section":if(d(f.actual=h.section,f.operator,f.value))break;else return a.rejected="section",f.pass=!1;case "sub_section":if(d(f.actual=h.subSection,f.operator,f.value))break;else return a.rejected="sub_section",f.pass=!1;case "segment":b.loadSegments();var g=b.getSegments().split(","),i=!1,j=b.getRequestVal("krux_segment");j&&g.push(j);f.actual=g.join(",");for(var j=b.toS(f.value).split(","),
l=0;l<j.length;l++)for(var m=0;m<g.length;m++)if(j[l]==g[m]){i=!0;break}if(i)break;else return a.rejected="segment",f.pass=!1;case "url":if(d(f.actual=location.href,f.operator,f.value))break;else return a.rejected="url",f.pass=!1;default:if(f.name.match(/^userAttributes/)){if(g=f.name.replace(/^userAttributes[0-9]+\./,""),!d(f.actual=h.userAttributes[g],f.operator,f.value))return a.rejected="userAttributes",f.pass=!1}else if(f.name.match(/^pageAttributes/)){if(g=f.name.replace(/^pageAttributes[0-9]+\./,
""),!d(f.actual=h.pageAttributes[g],f.operator,f.value))return a.rejected="pageAttributes",f.pass=!1}else return b.reportError("Unrecognized rule - "+f.name,"email-javascript"),f.pass=!1}}if(a.user_percent&&100*Math.random()>a.user_percent)return a.rejected="user %",!1;d=b.YYYYMMDD();if(a.start_date&&a.start_date>=d)return a.rejected="start date",!1;if(a.end_date&&a.end_date<d)return a.rejected="end date",!1;return a.freq_cap&&(d=b.S.get("l"+a.id),parseInt(d,10)>=parseInt(a.freq_cap,10))?(a.rejected=
"freq cap",!1):!0};k.makeHtmlDeferred=function(a){var d=[];new b.HTMLParser(void 0,a,{start:function(a,e,f){var g={},h=a.toLowerCase();d.push("<"+a);for(var a=0,i=e.length;a<i;a++)"script"==h&&"src"==e[a].name?g.krux_deferred_src=e[a].value:g[e[a].name]=e[a].value;"script"==h&&(g.type="text/krux_delayed_script",i=1);0<i?d.push(" "+b.buildAttributes(g)+(f?"/>":">")):d.push(f?"/>":">")},end:function(a){d.push("</"+a+">")},chars:function(a){d.push(a)}});return d.join("")};k.recordAttempt=function(a){a.started=
(new Date).getTime();k.executedTags.push(a);a.freq_cap&&b.S.inc("l"+a.id,86400)};k.writeTag=function(a){a.html_id||(k.sequence=k.sequence?k.sequence+1:1,a.html_id="krux_tag_"+a.format+"_"+k.sequence);b.in_array(a.timing,["asap","ready","onload"])||(a.timing="asap");if(a.template_definition){var d=function(){k.recordAttempt(a);b.loadTemplateTag(a.template_definition,a.params||{})};"onload"==a.timing?b.afterLoadCallback(d):"ready"==a.timing?b.ready(d):d()}else"iframe"==a.method?k.writeTagIframe(a):
k.writeTagScript(a,"onload"==a.timing);return a.html_id};k.writeTagIframe=function(a){var d=a.format.split("x"),c=function(){k.recordAttempt(a);b.iframeContents(a.html_id,a.html)};b.literate()?(l.__krux_write("<iframe "+b.buildAttributes({width:d[0],height:d[1],scrolling:"no",frameborder:0,marginheight:0,marginwidth:0,style:"0x0"==a.format?"display:none;":"",id:a.html_id})+"></iframe>"),"onload"==a.timing?b.afterLoadCallback(c):"ready"==a.timing?b.ready(c):c()):!b.literate()&&"0x0"==a.format&&(b.appendTag("iframe",
{id:a.html_id,width:0,height:0}).style.display="none",c())};k.writeTagScript=function(a,d){k.recordAttempt(a);if(b.literate())d||0<x.blocklist.length||(b.is.msie||b.is.opera)&&a.html.match(/(__bkframe|google-analytics.com|widgets\.twimg)/)?(l.__krux_write('<div id="'+a.html_id+'">'+k.makeHtmlDeferred(a.html)+"</div>"),o.setup(),k.loadDeferred()):l.__krux_write_real('<div id="'+a.html_id+'">'+a.html+"</div>");else if("0x0"==a.format){a.timing="onload";a.forced_delayed_load=!0;var c=b.appendTag("div",
{id:a.html_id});c.style.display="none";c.innerHTML=k.makeHtmlDeferred(a.html);k.loadDeferred()}};k.loadDeferred=function(){for(var a=l.getElementsByTagName("script"),d=0,c=a.length;d<c;d++){var e=a[d];if(e.getAttribute&&"text/krux_delayed_script"==e.getAttribute("type")){var f=e.cloneNode(!0);f.removeAttribute("krux_deferred_src");f.removeAttribute("language");f.setAttribute("type","text/javascript");o.node=f;p.length=0;p.push(0);if(e.text&&!e.getAttribute("krux_deferred_src"))e.setAttribute("type",
"text/javascript"),eval(e.text);else{f.timer=setTimeout(function(a){return function(){a.done||(a.done=!0,k.loadDeferred())}}(f),b.scriptTimeout||2E4);f.onreadystatechange=f.onload=function(){var a=f.readyState;if(!f.done&&(!a||/loaded|complete/.test(a)))clearTimeout(f.timer),f.done=!0,k.loadDeferred()};e.getAttribute("krux_deferred_src")&&f.setAttribute("src",e.attributes.krux_deferred_src.value);e.parentNode.replaceChild(f,e);break}}}};b.Storage={availableEngines:[],getEngine:function(){for(var a=
0;a<b.Storage.availableEngines.length;a++)if(b.Storage.availableEngines[a].isSupported())return b.Storage.availableEngines[a];return!1},expunge:function(a){for(var b=a.keyList(),c=0;c<b.length;c++)null===a.get(b[c])&&a.del(b[c])},cleanup:function(a){for(var b=a.keyList(),c=0;c<b.length;c++){var e=a.get(b[c]).match(/\|~([0-9]+)$/);if(e){var f=a.get(b[c]).replace(/\|~([0-9]+)$/,"");a.del(b[c]);e=(e[1]-(new Date).getTime())/1E3;a.set(b[c],f,e)}}}};var j=b.Storage;j.HTML5={name:"HTML5",isSupported:function(){return g.localStorage?
!0:!1},get:function(a){var d=g.localStorage.getItem(a+"__exp");return d&&d<b.timeStamp()?null:g.localStorage.getItem(a)},set:function(a,d,c){try{g.localStorage.setItem(a,b.toS(d)),c&&g.localStorage.setItem(a+"__exp",b.timeStamp((new Date).getTime()+1E3*c))}catch(e){}},del:function(a){g.localStorage.removeItem(a+"__exp");return g.localStorage.removeItem(a)},inc:function(a,b){var c=j.HTML5.get(a)||0;c++;j.HTML5.set(a,c,b);return c},count:function(){return j.HTML5.keyList().length},clear:function(){return g.localStorage.clear()},
keyList:function(){for(var a=[],b=g.localStorage,c=0;c<b.length;c++)b.key(c).match(/__exp$/)||a.push(b.key(c));return a}};j.availableEngines.push(j.HTML5);j.Cookies={name:"Cookies",cookieName:"KRUXS",cookieExpires:2592E3,isSupported:function(){return navigator.cookieEnabled?!0:!1},get:function(a){var d=j.Cookies._getData();if(a in d){var c=d[a+"__exp"];return c&&c<b.timeStamp()?null:d[a]}return null},set:function(a,d,c){var e=j.Cookies._getData();e[a]=b.toS(d);c&&(e[a+"__exp"]=b.timeStamp((new Date).getTime()+
1E3*c));b.cookie(j.Cookies.cookieName,A(e))},del:function(a){var d=j.Cookies._getData(),a=b.removeKeys(d,[a,a+"__exp"]);b.cookie(j.Cookies.cookieName,A(a))},inc:function(a,b){var c=j.Cookies.get(a)||0;c++;return j.Cookies.set(a,c,b)},count:function(){return b.keyValues(j.Cookies.keyList()).keys.length},clear:function(){b.cookie(j.Cookies.cookieName,null)},keyList:function(){return b.keyValues(b.removeKeys(j.Cookies._getData(),[/__exp$/])).keys},_getData:function(){var a=b.cookie(j.Cookies.cookieName);
return null===a?{}:b.parseQueryString(a)}};j.availableEngines.push(j.Cookies);j.Dummy={name:"Dummy",store:{},isSupported:function(){return!0},set:function(a,d,c){j.Dummy.store[a]=b.toS(d);c&&(j.Dummy.store[a+"__exp"]=b.timeStamp((new Date).getTime()+1E3*c))},get:function(a){if(void 0!==j.Dummy.store[a]){var d=j.Dummy.store[a+"__exp"];return d&&d<b.timeStamp()?null:j.Dummy.store[a]}return null},del:function(a){j.Dummy.store=b.removeKeys(j.Dummy.store,[a,a+"__exp"])},inc:function(a,b){var c=j.Dummy.get(a)||
0;c++;j.Dummy.set(a,c,b)},count:function(){return b.keyValues(j.Dummy.keyList()).keys.length},clear:function(){j.Dummy.store={}},keyList:function(){var a=[],d;for(d in b.removeKeys(j.Dummy.store,[/__exp$/]))a.push(d);return a}};j.availableEngines.push(j.Dummy);b.S=j.getEngine();b.tagSrcWithMatchingDomain=function(a,b){for(var c=l.getElementsByTagName(b),e,f=0,g=c.length;f<g;f++)if(e=H(c[f])){var h=e.match(/^http:\/\/([^\/]+)/);if(h&&("string"!=typeof a&&a.test(h[1])||"string"==typeof a&&-1<h[1].indexOf(a)))return e}return null};
b.toS=function(a){return"string"===typeof a?a:null===a?"null":void 0===a?"undefined":"object"==typeof a?"[object Object]":""+a};b.urlForDomain=function(a){if(b.isInAdIframe())return a.referrer;for(var d=a.getElementsByTagName("base"),c=0,e=d.length;c<e;c++)if(d[c].href)return d[c].href;return a.URL};b.YYYYMMDD=function(a){var b=function(a){return 1==a.toString().length?"0"+a:a};a||(a=new Date);return a.getFullYear()+"-"+b(a.getMonth()+1)+"-"+b(a.getDate())};g.KRUX=b;g.KRUXHTTP=b}(window.KRUXSetup,
window,document);
window.KRUX&&function(h,g,l){h.debugLevel=h.getRequestVal("krux_debug",0);var y=h.getRequestVal;g.pubid=y("krux_pubid",g.pubid);g.site=y("krux_site",g.site);g.section=y("krux_section",g.section);g.subSection=y("krux_subSection",g.subSection);g.channels=y("krux_channels",g.channels);g.autoCollect=h.bool(y("krux_autoCollect",g.autoCollect));g.autoInit=h.bool(y("krux_autoInit",g.autoInit));g.superTag=g.superTag||{};l.jQuery&&jQuery.gatling&&(g.async=!0);y("krux_block")&&l.addToBlocklist(y("krux_block"));y("krux_twinkie")&&
h.S.clear();g.pubid&&(!0===h.bool(g.autoInit)&&(h.init(),h.ST.init()),h.bool(g.loadSegments)&&h.loadSegments());h.listen(l,"beforeunload",h.onbeforeunload);h.listen(l,"unload",h.onunload);h.load(h.onload)}(window.KRUX,window.KRUXSetup,window);