var _paq = _paq || [];
_paq.push(['setAccount', '87xdS8']);
_paq.push(["enableFlash"]);
_paq.push(["trackPageView"]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/about/customerservice.html?link_source=t_header") && t.trackEvent("08ke4g3UL7yK")});
_paq.push(["trackForm", "#connect-self", "0dsKws3ZSD2V", {}, false, false]);
_paq.push(function(t){t.urlMatches("http://www.byki.com/lists/*") && t.trackEvent("0GP4aC4veVF7")});
_paq.push(function(t){t.urlMatches("http://transparentfacebook.appspot.com/page/") && t.trackEvent("0iSwhM47ipNg")});
_paq.push(["trackForm", "#fls-registration", "0jFLAb487E6E", {"email": "email"}, false, true]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/techsupp/?link_source=t_header") && t.trackEvent("0KmgET4xMabn")});
_paq.push(["trackForm", "#connect-classroom", "0QtN954CTFDy", {}, false, false]);
_paq.push(["trackForm", "#userlogin", "33w4WV4PVWtq", {}, false, false]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/about/company_info.html?link_source=t_header") && t.trackEvent("3nnjhw5aNcMZ")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/language-resources/*") && t.trackEvent("3xtBDt5jTv9W")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/government/*") && t.trackEvent("4auEg65WUxLz")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/libraries/*") && t.trackEvent("4MvGSH6zVApc")});
_paq.push(function(t){t.urlMatches("http://upgrade.byki.com/*") && t.trackEvent("4TjXdM6FKQJg")});
_paq.push(["trackClick", "#rss", "4XAHDi6L2B9M"]);
_paq.push(["trackForm", "#cse-search-box", "4zSc2v6ni5wY", {}, false, false]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/personal/connect/*") && t.trackEvent("4zsVnS6mSNTm")});
_paq.push(["trackClick", "#tbl_checkout input", "54fdL76QF7gA"]);
_paq.push(["trackForm", "#bullseye", "5cTeD86Zj89B", {"email": "email"}, false, true]);
_paq.push(["trackForm", "#flsform", "5PXwF27Cpqbv", {"email": "email"}, false, true]);
_paq.push(function(t){t.urlMatches("http://library.transparent.com/aflis/") && t.trackEvent("5qAeS67d28nz")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/education/getquote.html") && t.trackEvent("6dpyR77ZPsmA")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/language-resources/languages.html?link_source=t_header") && t.trackEvent("6kd3FR88CVck")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/*?link_source=t_header") && t.trackEvent("6qQi3f8dgbxJ")});
_paq.push(["trackForm", "#connect-workshop", "6rjza38dKsEw", {}, false, false]);
_paq.push(["trackForm", "#frmContactUsSmall", "6UFRNd8H7KiG", {"email": "email"}, false, true]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/learn-*/*") && t.trackEvent("73AC6Y8Q2vBt")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/personal/*") && t.trackEvent("78jnEr8UKgaU")});
_paq.push(function(t){t.urlMatches("http://library.transparent.com/aflis/game/modern/login") && t.trackEvent("78nS3b8UNKxE")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/*/games/*") && t.trackEvent("7EBEHB9t3ye6")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/about/*") && t.trackEvent("7Kkrh49xLiMx")});
_paq.push(function(t){t.urlMatches("http://library.transparent.com/aflis/game/modern/login") && t.trackEvent("7qE99K9d62Ee")});
_paq.push(["trackClick", ".button-buy", "7xGUqQ9k8MVj"]);
_paq.push(["trackForm", "#frmContactUs", "8APuPG0AwMFC", {"email": "email"}, false, true]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/mobile*") && t.trackEvent("8cwd5v0cdvVr")});
_paq.push(["trackClick", "#download_link", "8fmdnR0f4weM"]);
_paq.push(["trackForm", "#survey", "8MJZE60Msiw2", {"email": "email"}, false, true]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/*/quizzes/*") && t.trackEvent("8nfXFC0mXgxy")});
_paq.push(function(t){t.urlMatches("http://www.transparent.com/education/*") && t.trackEvent("8nmtTF0n4LKB")});
_paq.push(function(t){t.urlMatches("http://library.transparent.com/*/game/modern/login") && t.trackEvent("8nqXgr0n8g8m")});
_paq.push(["trackClick", "#mobile ul a", "8PxfG80Peyy4"]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/*?link_source=t_header") && t.trackEvent("8Qheam0PYx2h")});
_paq.push(["trackForm", "#dr_CheckoutPayment form", "8QHKLQ0Qr4CL", {"EMAILemail": "email"}, false, true]);
_paq.push(function(t){t.urlMatches("http://www.transparent.com/*/phrases.html") && t.trackEvent("8UDKWR0Um4NM")});
_paq.push(["trackForm", "#registration", "8xUHYE0xC2QA", {"email": "email"}, false, true]);
_paq.push(["trackClick", "#loginButton", "8ZrZT40Z9iJY"]);
_paq.push(["trackClick", ".choose-lang a", "9peMWv3nW6Nr"]);
_paq.push(["trackForm", "#blog-email", "9qL4gH3qtm8D", {"email": "email"}, false, true]);
_paq.push(["trackClick", "#addtocart", "9rRi6R3ryAWM"]);

/*
 Copyright 2011 Performable, Inc. http://www.performable.com/
*/
(function(){Math.Fb=function(){var a="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("");return function(c,h){var i=[];h=h||a.length;if(c)for(var l=0;l<c;l++)i[l]=a[0|Math.random()*h];else{i[8]=i[13]=i[18]=i[23]="-";i[14]="4";for(l=0;l<36;l++)if(!i[l]){c=0|Math.random()*16;i[l]=a[l==19?c&3|8:c]}}return i.join("")}}();if(!String.prototype.$a){String.prototype.$a=function(){var a=this.match(arguments.callee.wc);if(!a)return null;return{scheme:a[1]||"",subscheme:a[2]||"",user:a[3]||
"",pass:a[4]||"",host:a[5],port:a[6]||"",path:a[7]||"",query:a[8]||"",fragment:a[9]||""}};String.prototype.$a.wc=/^(?:([a-z]+):(?:([a-z]*):)?\/\/)?(?:([^:@]*)(?::([^:@]*))?@)?((?:[a-z0-9_-]+\.)+[a-z]{2,}|localhost|(?:(?:[01]?\d\d?|2[0-4]\d|25[0-5])\.){3}(?:(?:[01]?\d\d?|2[0-4]\d|25[0-5])))(?::(\d+))?(?:([^:\?\#]+))?(?:\?([^\#]+))?(?:\#([^\s]+))?$/i}var b=b||{};b.na="analytics.performable.com";b.eb=45;b=b||{};b.debug=false;b.log=function(){try{var a=new b.J,c=document.location.hash.indexOf("#pdbg")>
-1;if(b.debug||c||a.p("perf_dbg")==="1"){var h=window.console;h&&typeof h.log==="function"&&h.log.apply(h,arguments);a.D("perf_dbg","1")}}catch(i){}};b=b||{};b.global={};b.global.L=function(a,c,h,i,l,q,v){this.K=a||document;this.Da=c||navigator;this.zc=h||screen;this.Ib=i||window;this.S=l||this.K.location;this.top=q||top;this.parent=v||parent};b.global.L.prototype.mb=function(){var a="";try{a=this.top.document.referrer}catch(c){if(parent)try{a=this.parent.document.referrer}catch(h){a=""}}if(a==="")a=
this.K.referrer;return a};b.global.L.prototype.nc=function(){return this.K.characterSet?this.K.characterSet:this.K.charset?this.K.charset:""};b=b||{};b.e=b.utils={};b.e.Bb=Object.prototype.toString;b.e.ha=function(a){return b.e.Bb.call(a)==="[object Array]"};b.e.ra=function(a,c){for(var h=0,i=c.length;h<i;h++)if(c[h]===a)return h;return-1};b.e.sc=function(a){var c=[];if(a!=null){var h=a.length;if(h==null||typeof a==="string"||b.e.Ba(a)||a.setInterval)c[0]=a;else for(;h;)c[--h]=a[h]}return c};b.e.extend=
function(){var a=arguments[0]||{},c=1,h=arguments.length,i=false,l;if(typeof a==="boolean"){i=a;a=arguments[1]||{};c=2}if(typeof a!=="object"&&!b.e.Ba(a))a={};if(h==c){a=this;--c}for(;c<h;c++)if((l=arguments[c])!=null)for(var q in l){var v=a[q],p=l[q];if(a!==p)if(i&&p&&typeof p==="object"&&!p.nodeType)a[q]=b.e.extend(i,v||(p.length!=null?[]:{}),p);else if(p!==undefined)a[q]=p}return a};b.e.o=function(a,c){var h,i=0,l=a.length;if(l===undefined)for(h in a){if(c.call(a[h],h,a[h])===false)break}else for(h=
a[0];i<l&&c.call(h,i,h)!==false;h=a[++i]);return a};b.e.aa=function(a){return typeof a!=="undefined"};b.e.addEventListener=function(a,c,h,i){if(a.addEventListener){a.addEventListener(c,h,i);return true}else if(a.attachEvent)return a.attachEvent("on"+c,h);a["on"+c]=h};b.e.Wa=function(a,c,h){var i=new Date,l=new Image(1,1);expireDateTime=i.getTime()+c;l.onload=function(){h&&h()};l.src=a};b.e.la=function(a){return(a||"").replace(/^\s+|\s+$/g,"")};b.e.Fa=function(a,c){return a.substr(0,c.length)==c};
b.e.jc=function(a,c){var h=a.length-c.length;return h>=0&&a.lastIndexOf(c)===h};b.e.B=function(a){return undefined==a||"-"==a||""==a};b.e.qc=function(a){for(var c in a)return false;return true};b.e.P=function(a){return!b.e.B(a)?a:""};b.e.Ra=function(a,c){return b.e.ca(a)==b.e.ca(c)};b.e.kc=function(a,c){return b.e.ca(a).indexOf(c)>-1};b.e.ca=function(a){return b.e.P(a).toLowerCase()};b.e.da=function(a,c){var h=encodeURIComponent;return h instanceof Function?c?encodeURI(a):h(a):escape(a)};b.e.pa=function(a,
c){var h=decodeURIComponent,i;a=a.split("+").join(" ");if(h instanceof Function)try{i=c?decodeURI(a):h(a)}catch(l){i=unescape(a)}else i=unescape(a);return i};b.e.Ba=function(a){return b.e.Bb.call(a)==="[object Function]"};b.e.N=function(){var a=new Date;return Math.round((a.getTime()+a.getTimezoneOffset()*6E4)/1E3)};b.e.Va=function(a){hash=0;for(t=a.length-1;t>=0;t--){g=a.charCodeAt(t);hash=(hash<<6&268435455)+g+(g<<14);g=hash&266338304;hash=g!=0?hash^g>>21:hash}return hash};b.e.fa=function(a){a=
a.split(".");if(a.length>2)a=a.slice(1);return"."+a.join(".")};b.e.Qa=function(a,c){var h={},i={"true":true,"false":false,"null":null};a=b.e.la(b.e.P(a));if(b.e.Fa(a,"?")||b.e.Fa(a,"#"))a=a.slice(1);b.e.o(a.split("+").join(" ").split("&"),function(l,q){var v=q.split("=");l=b.e.pa(v[0]);q=h;var p=0,r=l.split("]["),y=r.length-1;if(/\[/.test(r[0])&&/\]$/.test(r[y])){r[y]=r[y].replace(/\]$/,"");r=r.shift().split("[").concat(r);y=r.length-1}else y=0;if(v.length===2){v=b.e.pa(v[1]);if(c)v=v&&!isNaN(v)?
+v:v==="undefined"?undefined:i[v]!==undefined?i[v]:v;if(y)for(;p<=y;p++){l=r[p]===""?q.length:r[p];q=q[l]=p<y?q[l]||(r[p+1]&&isNaN(r[p+1])?{}:[]):v}else if(b.e.ha(h[l]))h[l].push(v);else h[l]=h[l]!==undefined?[h[l],v]:v}else if(l)h[l]=c?undefined:""});return h};b.e.ta=function(a,c){function h(q,v){i[i.length]=b.e.da(q)+"="+b.e.da(v)}var i=[];c=c||"&";for(var l in a)b.e.ha(a[l])?b.e.o(a[l],function(){h(l,this)}):h(l,b.e.Ba(a[l])?a[l]():a[l]);return i.join(c).replace(/%20/g,"+")};b.e.Mb=function(){var a=
[];b.e.o("daum:q,eniro:search_word,naver:query,images.google:q,google:q,yahoo:p,msn:q,bing:q,aol:query,aol:encquery,lycos:query,ask:q,altavista:q,netscape:query,cnn:query,about:terms,mamma:query,alltheweb:q,voila:rdata,virgilio:qs,live:q,baidu:wd,alice:qs,yandex:text,najdi:q,aol:q,mama:query,seznam:q,search:q,wp:szukaj,onet:qt,szukacz:q,yam:k,pchome:q,kvasir:q,sesam:q,ozu:q,terra:query,mynet:q,ekolay:q,rambler:words".split(","),function(c,h){a.push(h.split(":"))});return a}();b.e.bc=function(a,c){c=
b.e.sc(c);try{for(;a;){var h=b.e.ca(a.tagName);if(!b.e.B(h)&&b.e.ra(h,c)>-1)return a;a=a.parentNode}}catch(i){b.log(i)}};b.e.G=function(a,c){try{return b.e.la(b.e.P(a.getAttribute(c)))}catch(h){return""}};b.e.tc=function(a,c){a=b.e.la(a);c=b.e.la(c);if(b.e.Fa(a,"javascript:")||b.e.Fa(a,"#")||b.e.B(c))return a;if(/\?/.test(c))c=c.split("?")[1];if(/#/.test(c))c=c.split("#")[0];var h=a.split("?");a=h[0];var i,l="";if(h.length>=2)i=b.e.la(h.slice(1).join("?"));if(/#/.test(i)){h=i.split("#",2);i=h[0];
l="#"+h[1]}b.e.B(i)||(c=b.e.jc(i,c)?"":"&"+c);return a+"?"+b.e.P(i)+c+l};b.e.Ya=function(a,c){a=a||{};if(!c)return c;for(var h in c)a[h]=c[h];return a};b.e.nb=function(a,c){if(a&&a.className)return b.e.ra(c,a.className.split(" "))>-1};b.e.Ga=function(a){return(a||"").replace(/(^.+?)\[(.+?)\]/,"$1_$2")};b.e.parseCurrency=b.e.$c=function(a){if(typeof a=="number")return a;else if(a=a.match(/([^\d]*)([\d\.,]+)([^\d\.,]*)/)){var c=a[2];a=c.split(".");c=c.split(",");a=a.length>2||a.length==2&&a[1].length>
2&&(c.length==0||a[0].length<c[0].length)||c.length==2&&c[1].length==2?c:a;c=decimalPart=0;if(a.length>1)decimalPart=a.pop();c=a.join("");c=c.replace(/[\.,]/g,"");a=parseInt(c);if(decimalPart)a+=parseFloat(decimalPart)/Math.pow(10,decimalPart.length);return a}else return null};b.e.ia=function(a,c){c=c||{};var h={w:b.e.N(),m:a.message||a.toString?a.toString():"-",jv:b.eb};h=b.e.extend(h,c);if(a.name)h.n=a.name;if(a.fileName)h.f=a.fileName;if(a.lineNumber)h.l=a.lineNumber;try{h.x=a.stack||a.ed||""}catch(i){}b.log("Encountered a JS error");
b.log(h);b.e.Wa("//"+b.na+"/__pto.gif?"+b.e.ta(h))};b=b||{};b.J=function(a){this.j=a||new b.global.L;this.cc=[];this.ga=new b.W};b.J.prototype.D=function(a,c,h){h=h||{};var i;if(h.sb){i=new Date;i.setTime(i.getTime()+h.sb*1E3*60)}else if(h.Z){i=new Date;i.setTime(i.getTime()+h.Z*864E5)}h.Eb===true&&this.ga.D(a,c);this.Yb(a,h.$b?c:b.e.da(c,true),(b.e.aa(i)?";expires="+i.toGMTString():"")+";path="+(h.path?h.path:"/")+(h.domain?";domain="+h.domain:"")+(h.dd?";secure":""))};b.J.prototype.Yb=function(a,
c,h){this.j.K.cookie=a+"="+c+h;this.cc.push({name:a,value:c,Kc:h})};b.J.prototype.p=function(a,c){if(c===true){c=this.ga.p(a);if(c!==undefined)return c}return(a=(new RegExp("(^|;)[ ]*"+a+"=([^;]*)")).exec(this.j.K.cookie))?b.e.pa(a[2],true):""};b.J.prototype.qa=function(a,c){c=c||{};c.Z=-1;this.p(a)&&this.D(a,"",c)};b.J.prototype.$=function(){if(!b.e.aa(this.j.Da.cookieEnabled)){this.D("__p_testcookie","1");return this.p("__p_testcookie")=="1"?"1":"0"}return this.j.Da.cookieEnabled?"1":"0"};b.J.prototype.ob=
function(){return!!this.ga&&this.ga.$()};b.W=function(a){this.Ea=a;this.za=null};b.W.prototype.D=function(a,c){this.$()&&this.Ea.set(a,c)};b.W.prototype.p=function(a){if(this.$())return this.Ea.get(a)};b.W.prototype.qa=function(a){if(this.$())return this.Ea.remove(a)};b.W.prototype.$=function(){if(this.za===null)try{this.Ea.get("");this.za=true}catch(a){this.za=false}return this.za};b=b||{};b.Oa=function(a){var c=(a||new b.global.L).Da;a=c.userAgent.toLowerCase();var h={pc:function(){this.Oa=this.zb(this.gc)||
"";this.version=this.Ab(c.userAgent)||this.Ab(c.appVersion)||"";this.Lb=this.zb(this.hc)||""},zb:function(i){for(var l=0;l<i.length;l++){var q=i[l].H,v=i[l].vc;this.Hb=i[l].va||i[l].A;if(q){if(q.indexOf(i[l].I)!=-1)return i[l].A}else if(v)return i[l].A}},Ab:function(i){var l=i.indexOf(this.Hb);if(l!=-1)return parseFloat(i.substring(l+this.Hb.length+1))},gc:[{H:c.userAgent,I:"Chrome",A:"Chrome"},{H:c.userAgent,I:"OmniWeb",va:"OmniWeb/",A:"OmniWeb"},{H:c.vendor,I:"Apple",A:"Safari",va:"Version"},{vc:window.opera,
A:"Opera"},{H:c.vendor,I:"iCab",A:"iCab"},{H:c.vendor,I:"KDE",A:"Konqueror"},{H:c.userAgent,I:"Firefox",A:"Firefox"},{H:c.vendor,I:"Camino",A:"Camino"},{H:c.userAgent,I:"Netscape",A:"Netscape"},{H:c.userAgent,I:"MSIE",A:"Explorer",va:"MSIE"},{H:c.userAgent,I:"Gecko",A:"Mozilla",va:"rv"},{H:c.userAgent,I:"Mozilla",A:"Netscape",va:"Mozilla"}],hc:[{H:c.platform,I:"Win",A:"Windows"},{H:c.platform,I:"Mac",A:"Mac"},{H:c.userAgent,I:"iPhone",A:"iPhone/iPod"},{H:c.platform,I:"Linux",A:"Linux"}]};h.pc();this.version=
(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1];this.Zc=h.Lb;this.Gc=h.Oa;this.cd=/webkit/.test(a);this.opera=/opera/.test(a);this.uc=/msie/.test(a)&&!/opera/.test(a);this.Vc=/mozilla/.test(a)&&!/(compatible|webkit)/.test(a)};b.g={};b.g.ub=function(a,c){return a+"_"+c};b.g.F=function(a,c,h,i,l,q){this.j=a?a.j:new b.global.L;this.cookie=a||new b.J(F);this.M=b.e.fa(this.j.S.hostname);this.domain=c||b.e.Va(this.M);this.Ha=h||1;this.dc=i||10;this.start=l||b.e.N();this.ja=q};b.g.F.O="__ptcs";
b.g.F.fb="__ptcc";b.g.F.prototype.Ca=function(){return this.ja!==true};b.g.F.parse=function(a,c){var h=a?a.j:new b.global.L;a=a||new b.J(h);if(a.p(b.g.F.fb)==="1"){c=c||a.p(b.g.F.O);c=c.split(".");if(c.length==4)return new b.g.F(a,c[0],c[1],c[2],c[3],true)}return new b.g.F(a)};b.g.F.prototype.oc=function(){try{this.Ha=parseInt(this.Ha||1,10)+1}catch(a){this.Ha=1}};b.g.F.prototype.p=function(){return[this.domain,this.Ha,this.dc,this.start].join(".")};b.g.F.prototype.save=function(){this.cookie.D(b.g.F.fb,
"1",{domain:this.M,path:"/"});this.cookie.D(b.g.F.O,this.p(),{sb:30,domain:this.M,path:"/"})};b.g.q=function(a,c,h,i,l,q,v,p,r,y){this.R=a;this.j=c?c.j:new b.global.L;this.cookie=c||new b.J(this.j);this.M=b.e.fa(this.j.S.hostname);this.domain=h||b.e.Va(this.M);this.ma=i||Math.Fb(12);this.id=l||this.ma;this.pb=q||b.e.N();this.ab=v||b.e.N();this.Aa=p||b.e.N();this.Q=r||1;this.ja=y};b.g.q.O="__ptca";b.g.q.gb="__ptv";b.g.q.db="__pti";b.g.q.Ka="__ptsf";b.g.q.parse=function(a,c,h){var i=c?c.j:new b.global.L;
c=c||new b.J(i);var l=b.g.ub,q=c.p(l(b.g.q.Ka,a))!=="1";c.ob()&&c.qa(l(b.g.q.Ka,a),{domain:b.e.fa(i.S.hostname),path:"/"});h=h||c.p(b.g.q.O,q);i=c.p(l(b.g.q.gb,a),q);l=c.p(l(b.g.q.db,a),q);h=h.split(".");try{if(h.length==6){h[5]=parseInt(h[5],10);return new b.g.q(a,c,h[0],i||h[1],l||i,h[2],h[3],h[4],h[5],true)}}catch(v){}return new b.g.q(a,c,undefined,i,l||i)};b.g.q.prototype.Ca=function(){return!this.ja};b.g.q.prototype.rotate=function(a){this.ab=this.Aa||a;this.Aa=a;this.Q+=1};b.g.q.prototype.Ec=
function(a){var c=this.id;this.id=a;if(c!==this.ma){this.ma=Math.Fb(12);this.pb=b.e.N();this.ab=b.e.N();this.Aa=b.e.N();this.Q=1;this.ja=false;this.cookie.ob()||this.cookie.D(this.La(b.g.q.Ka),"1",{Z:730,domain:this.M,path:"/"})}this.save()};b.g.q.prototype.p=function(){return[this.domain,this.ma,this.pb,this.ab,this.Aa,this.Q].join(".")};b.g.q.prototype.save=function(){this.cookie.D(b.g.q.O,this.p(),{Z:730,domain:this.M,path:"/"});this.cookie.D(this.La(b.g.q.gb),this.ma,{Z:730,domain:this.M,path:"/",
Eb:true});this.cookie.D(this.La(b.g.q.db),this.id,{Z:730,domain:this.M,path:"/",Eb:true})};b.g.q.prototype.La=function(a){return b.g.ub(a,this.R)};b.g.C=function(a,c,h,i,l,q){this.j=a?a.j:new b.global.L;this.cookie=a||new b.J(F);this.M=b.e.fa(this.j.S.hostname);this.domain=c||b.e.Va(this.M);this.fc=h||b.e.N();this.Q=i||1;this.V=l||this.kb();this.ja=q};b.g.C.O="__ptcz";b.g.C.wa="__ptcx";b.g.C.prototype.Ca=function(){return!this.ja};b.g.C.parse=function(a,c){var h=a?a.j:new b.global.L;a=a||new b.J(h);
c=c||a.p(b.g.C.O);try{var i=c.split(".");if(i.length>=5){var l={};b.e.o(i.slice(4).join(".").split("|"),function(v,p){v=p.split("=");if(v.length==2)l[b.e.pa(v[0])]=b.e.pa(v[1])});return new b.g.C(a,i[0],i[1],i[2],l,true)}}catch(q){b.log(q)}return new b.g.C(a)};b.g.C.prototype.Db=function(){if(b.e.P(this.V.ptmcsr)=="(direct)")this.V=b.e.extend(this.V,this.kb())};b.g.C.prototype.Dc=function(a){var c=a||this.cookie.p(b.g.C.wa);if(!b.e.B(c)&&c.split(".").length==3){if(b.e.B(this.V.ptmcex))this.V.ptmcex=
c;a=[];var h=b.e.P(this.V.ptmcx2);b.e.B(h)||(a=h.split(","));var i=false;b.e.o(a,function(l,q){if(q==c)i=true});i||a.push(c);if(a.length>10)a=a.slice(1);this.V.ptmcx2=a.join(",")}};b.g.C.prototype.kb=function(){var a=this.j.mb(),c=this.j.S,h=b.e.Qa(c.search||c.hash),i={},l=false,q={ptmcsr:"(direct)",ptmcmd:"(none)",ptmccn:"(direct)"};if(!b.e.B(a)){var v=a.$a();if(!b.e.B(v)){var p=b.e.Qa(v.query),r=false;b.e.o(b.e.Mb,function(y,z){if(v.host.indexOf(z[0])>-1)if(p[z[1]]){q.ptmccn="(organic)";q.ptmcmd=
"organic";q.ptmcsr=z[0];q.ptmctr=p[z[1]];r=true;return false}});if(!r&&!b.e.Ra(c.hostname,v.host)){q.ptmccn="(referral)";q.ptmcsr=(""+v.host).replace(/^www\./,"");q.ptmcmd="referral";q.ptmctr=v.path}}}b.e.o([["ptmcsr","utm_source"],["ptmccn","utm_campaign"],["ptmcmd","utm_medium"],["ptmctr","utm_term"],["ptmcct","utm_content"]],function(y,z){y=z[0];if(z=b.e.P(h[z[1]])){i[y]=z;l=true}});return l?i:q};b.g.C.prototype.p=function(){return[b.e.da(this.domain),b.e.da(this.fc),b.e.da(this.Q),0,b.e.ta(this.V,
"|")].join(".")};b.g.C.prototype.save=function(){this.cookie.D(b.g.C.O,this.p(),{Z:730,domain:this.M,$b:true,path:"/"})};b.g.h=function(a){this.j=a||new b.global.L;this.now=b.e.N();this.id=this.Q=null;this.Xa=this.qb=false;this.vb=true;this.Gb=false;this.cookie=new b.J(this.j);this.Pa=[];this.Sa=[]};b.g.h.Kb="opt_out";b.g.h.prototype.rc=function(){if(!this.Xa){var a=document.createElement("div");a.style.position="absolute";a.style.left="-10px";if(!b.Oa.uc)a.style.visibility="hidden";a.innerHTML='<object type="application/x-shockwave-flash" id="__perf_flash" data="//d1nu2rn22elx8m.cloudfront.net/performable/performable.swf" width="1" height="1"><param name="movie" value="//d1nu2rn22elx8m.cloudfront.net/performable/performable.swf"/><param name="allowScriptAccess" value="always"/></object>';
document.documentElement.appendChild(a);this.cookie.ga=new b.W(document.getElementById("__perf_flash"))}this.Xa=true};b.g.h.prototype.Fc=function(){if(!this.Gb){b.log("Checking event queue...");this.Gb=true;var a=this.Ta(),c=this;b.e.o(a,function(h,i){b.log("Retrying event: ",i.url);c.Y(null,"//"+b.na+i.url,function(){c.xb(i.url)})})}};b.g.h.prototype.setAccount=function(a){this.R=a;this.T()};b.g.h.prototype.enableFlash=function(){G.rc()};b.g.h.prototype.setDebugMode=function(a){b.debug=a};b.g.h.prototype.setSiteId=
function(a){this.Cc=a};b.g.h.prototype.identify=function(a){this.T();this.A=this.Xb(a);this.mc=a;this.A!==this.id.id&&this.id.Ec(this.A)};b.g.h.prototype.Xb=function(a){if(a.id)return"id:"+a.id;else if(a.ic)return"email:"+a.ic;return null};b.g.h.prototype.trackPageView=function(a){this.T();this.Y(b.e.Ya(a,{k:1}))};b.g.h.prototype.trackConversion=function(a,c){this.T();if(typeof a==="string"||typeof a==="number"){a={id:b.e.P(a)};if(b.e.aa(c))a=b.e.Ya(a,c)}if(b.e.Ba(a.value))a.value=a.value(b);c=a.domain;
if(!b.e.B(c)){var h=b.e.fa(this.j.S.hostname),i=b.e.fa(c);if(!b.e.Ra(i,h)){a=b.e.extend(a,{account:this.R});delete a.domain;this.Wb("//"+c+"/xd_conversion.html?"+b.e.ta(a));return}}a=b.e.Ya(a,{k:3,n:b.e.P(a.id),m:b.e.P(a.value)});var l=this.hb(a),q=this;q.yc(l);q.Y(a,l,function(){q.xb(l)})};b.g.h.prototype.trackEvent=b.g.h.prototype.trackConversion;b.g.h.prototype.trackLocalConversion=function(){this.Y({k:2})};b.g.h.prototype.trackForms=function(){this.T();var a=this;b.e.o(b.find("form"),function(c,
h){a.Zb(h)})};b.g.h.prototype.trackForm=function(a,c,h,i,l,q){b.log("trackForm",arguments);this.Sa.push(a);h=b.e.aa(h)?h:{};i=b.e.aa(i)?i:false;l=b.e.aa(l)?l:true;var v={};for(key in h)v[b.e.Ga(key)]=h[key];h=v;this.T();var p=this;b.e.o(b.find(a),function(r,y){b.log("Attaching submit listener to:");b.log(y);b.e.addEventListener(y,"submit",function(){try{var z=p.lc(y),C={},A;b.log(z);b.log(h);for(A in z)if(h[A])C[h[A]]=z[A];else if(i)C[A]=z[A];l&&!b.e.qc(C)&&p.identify(C);p.trackEvent(c,q)}catch(O){b.e.ia(O)}})})};
b.g.h.prototype.trackClick=function(a,c,h){b.log("trackClick",arguments);this.T();var i=this;this.Pa.push(a);b.e.o(b.find(a),function(l,q){b.log("Attaching mousedown listener to:");b.log(q);b.e.addEventListener(q,"mousedown",function(){try{i.trackEvent(c,h)}catch(v){b.e.ia(v)}})})};b.g.h.prototype.xc=function(a){return"/"+a.split("//")[1].split("/").splice(1).join("/")};b.g.h.prototype.urlMatches=function(a,c){c||(c=this.j.K.location.toString().toLowerCase());a=a.toLowerCase();if(c==a)return true;
if(a.indexOf("?")===-1){var h=c.indexOf("?");if(h!==-1)c=c.substring(0,h)}if(a.indexOf("*")==-1){a=a.replace(/\/$/,"");c=c.replace(/\/$/,"");return a==c?true:a.indexOf("/")==0?this.xc(c)==a:false}if(a==c)return true;if(a.length==0)return false;regex=a.replace(new RegExp("[.+?|()\\[\\]{}\\\\]","g"),"\\$&").replace(new RegExp("\\*","g"),"(.*?)");regex=/\/$/.test(regex)?"^"+regex+"$":"^"+regex+"/?$";regex=new RegExp(regex,"i");if(regex.test(c))return true;else if(a.indexOf("/")==0){c="/"+c.split("//")[1].split("/").splice(1).join("/");
return regex.test(c)}else return false};b.g.h.prototype.trackEvents=function(){this.T();var a=this;b.e.addEventListener(this.j.K.body,"mousedown",function(c){try{if(!c)c=window.event;var h=c.target||c.fromElement||c.srcElement,i=b.e.bc(h,["a","button","input"]);if(i){var l={k:4},q=a.cookie.p(b.g.C.wa);!b.e.B(q)&&q.split(".").length==3&&b.e.o([h,i],function(r,y){r=b.e.G(y,"class")||y.className;if(b.e.kc(r,"performable-conversion"))l.k=2});if(b.e.ca(i.tagName)=="input")if(b.e.G(i,"type")!="submit"&&
l.k!==2)return;a.Y(b.e.extend(l,a.Pb(i)));if(a.vb&&b.e.Ra(i.tagName,"a")){var v=b.e.G(i,"href");i.setAttribute("href",b.e.tc(v,a.j.S.search))}}}catch(p){b.e.ia(p,a.ib())}finally{return true}})};b.g.h.prototype.setParameterPassing=function(a){this.vb=a===true};b.g.h.prototype.enrollInExperiment=function(){var a=this.Rb();this.cookie.$()&&a&&b.e.Wa("//"+this.j.S.hostname+"/__ptx.gif?i="+a+"&cb="+b.e.N())};b.g.h.prototype.redirect=function(a){var c=0,h=[];for(k in a)c+=a[k];if(c){for(k in a)h.push([1E3/
c*a[k],k]);var i=(new Date).getTime()%1E3;b.e.o(h,function(l,q){if(i<q[0]){if(q[1]!="#")window.location=q[1];return false}})}};b.g.h.prototype.validateSetup=function(a){window.parent&&window.parent.Perf&&window.parent.Perf.receiveMessage&&window.parent.Perf.receiveMessage([["Able to check setup.",true],["Account is set properly.",a===this.R&&this.trackPageView]])};b.g.h.prototype.showTargetedElements=function(){b.e.o(this.Pa,function(a,c){b.e.o(b.find(c),function(h,i){i.Ma=i.style.border;i.style.border=
"dotted 2px red"})});b.e.o(this.Sa,function(a,c){b.e.o(b.find(c),function(h,i){i.Ma=i.style.border;i.style.border="dotted 2px blue"})})};b.g.h.prototype.hideTargetedElements=function(){function a(c,h){b.e.o(b.find(h),function(i,l){if(b.e.aa(l.Ma))l.style.border=l.Ma})}b.e.o(this.Pa,a);b.e.o(this.Sa,a)};b.g.h.prototype.T=function(){if(!this.qb){this.R||this.Ob();try{this.cookie.qa("__ptv:"+this.R);this.cookie.qa("__pti:"+this.R);this.cookie.qa("__ptsf:"+this.R)}catch(a){}this.Q=b.g.F.parse(this.cookie);
this.id=b.g.q.parse(this.R,this.cookie);this.content=b.g.C.parse(this.cookie);if(this.Q.Ca())this.id.Ca()||this.id.rotate(this.Q.start);else this.Q.oc();this.id.save();this.Q.save();this.content.Db();this.content.Dc();this.content.save();this.content.Db();this.qb=true;this.Qb()}};b.g.h.prototype.Ob=function(){this.Xa=true;this.cookie.ga=new b.W(null)};b.g.h.prototype.Qb=function(){var a={},c=false,h=this.j.S,i=b.e.Qa(h.search||h.hash);b.e.o([["pt_email","email"],["pt_twitter","twitter"],["pt_facebook",
"facebook"],["pt_openid","openid"],["pt_id","id"],["pt_name","name"],["pt_fname","firstname"],["pt_lname","lastname"]],function(l,q){l=q[1];if(q=b.e.P(i[q[0]])){a[l]=q;c=true}});c&&this.identify(a)};b.g.h.prototype.Sb=function(){var a={};a.v=2;a.w=b.e.N();a.a=this.R;a.si=this.Cc||0;a.i=b.e.ta(this.mc);a.id=this.id.id;a.vi=this.id.ma;var c=this.cookie.p(b.g.q.O);b.e.B(c)||(a.u=c);c=this.cookie.p(b.g.C.O);b.e.B(c)||(a.z=c);c=this.cookie.p(b.g.F.O);b.e.B(c)||(a.b=c);c=this.cookie.p(b.g.C.wa);if(!b.e.B(c)&&
c.split(".").length==3)a.x=c;return a};b.g.h.prototype.ib=function(){var a={jv:b.eb},c=this.j.zc;if(c){a.s=c.width+"x"+c.height;a.d=c.colorDepth+"-bit"}c=this.j.mb();b.e.B(c)||(a.r=c);c=this.j.K.title;b.e.B(c)||(a.t=c);c=this.j.nc();b.e.B(c)||(a.c=c);c=this.j.Da;c=c.language?c.language:c.ac?c.ac:"";b.e.B(c)||(a.l=b.e.ca(c));return a};b.g.h.prototype.Rb=function(){var a=this.cookie.p(b.g.C.wa);if(!b.e.B(a)&&a.split(".").length==3)return b.e.la(a);return false};b.g.h.prototype.hb=function(a){var c=
"//"+b.na+"/__ptq.gif";a=b.e.extend(a,this.ib(),this.Sb());return c+"?"+b.e.ta(a)};b.g.h.prototype.Y=function(a,c,h){b.log("Sending Request");a&&b.log(a);c=c||this.hb(a);b.log(c);b.e.Wa(c,0,h)};b.g.h.prototype.Pb=function(a){var c=b.e.G(a,"action")||undefined,h=b.e.G(a,"id")||undefined,i=b.e.G(a,"title")||undefined,l=b.e.G(a,"href")||undefined,q=b.e.G(a,"alt")||undefined,v=b.e.G(a,"name")||undefined,p=b.e.G(a,"class")||a.className||undefined,r=b.e.G(a,"rel")||undefined,y=b.e.G(a,"rev")||undefined,
z=b.e.ca(a.tagName);if(z=="input")z=":"+(b.e.G(a,"type")||"text");return{ee:z,ea:c,ei:h,et:i,eh:l,el:q,en:v,ec:p,er:r,ev:y}};b.g.h.prototype.Wb=function(a){var c=this.j.K;if(c.createElement){var h=c.createElement("iframe");h.width="1";h.height="1";h.style.border="0px";h.style.width="0px";h.style.height="0px";h.scrolling="no";h.src=a;c.body.appendChild(h)}};b.g.h.prototype.Ub=function(a){return b.e.Ga(a.name).replace(/[_\-]/,"").match(/pass|billing|creditcard|cardnum|^cc|ccnum|exp|seccode|securitycode|securitynum|cvc|cvv|ssn|socialsec|socsec|csc/i)?
true:false};b.g.h.prototype.Vb=function(a){return b.e.Ga(a.name).replace(/[_\-]/,"").match(/login|user|username|email|userid/i)?true:false};b.g.h.prototype.Nb=function(a){if(b.e.nb(a,"perf_include"))return true;if(b.e.nb(a,"perf_exclude"))return false;if(!a.name)return false;if(!a.nodeName.match(/input|select/i))return false;if(a.nodeName.match(/input/i)&&!a.type.match(/text|radio|checkbox/i)&&!this.Vb(a))return false;if(this.Ub(a))return false;if(a.type.match(/radio|checkbox/)&&!(a.checked||a.selected))return false;
return true};b.g.h.prototype.lc=function(a){var c={},h=this;b.e.o(b.find("input, textarea, select",a),function(i,l){if(h.Nb(l)){i=l.value;if(!i&&l.nodeName.match(/select/i))i=l.options[l.selectedIndex].text;l=b.e.Ga(l.name);if(l.match(/\[\]$/)){l=l.replace(/\[\]$/,"");i=c[l]?e[l].split(","):[];i.push(l.replace(/,/g," "));i.sort();c[l]=i.join(",")}else c[l]=i}});return c};b.g.h.prototype.yb=function(a){var c=[];b.e.o(a,function(h,i){c.push(i.timestamp+" "+i.url)});this.cookie.D("perf_se",encodeURIComponent(c.join("|")))};
b.g.h.prototype.xb=function(a){a=a.replace("//"+b.na,"");var c=this.Ta(),h=[];b.e.o(c,function(i,l){l.url!=a&&h.push(l)});this.yb(h);b.log("Removed event: ",a)};b.g.h.prototype.timestamp=function(){return Math.round((new Date).getTime()/1E3)};b.g.h.prototype.Ta=function(){var a=decodeURIComponent(this.cookie.p("perf_se")).split("|");if(!a)return[];var c=[],h=this.timestamp()-300;b.e.o(a,function(i,l){i=l.split(" ");if(i.length==2){i={timestamp:parseInt(i[0],10),url:i[1]};i.timestamp>h&&c.push(i)}});
return c};b.g.h.prototype.yc=function(a){a=a.replace("//"+b.na,"");if(a.indexOf("/")!=0)a="/"+a;var c=this.Ta(),h=false;b.e.o(c,function(i,l){if(l.url===a)h=true});if(!h){c.push({url:a,timestamp:this.timestamp()});b.log("Saving Event:",a);this.yb(c)}};b.g.h.prototype.Zb=function(a){var c=this,h=[];function i(l){var q=h.indexOf(l);return q==-1?h.push(l):q}b.e.o(b.find("input, textarea, select",a),function(l,q){l=b.e.G(q,"type");if(!(b.e.ra(l,["hidden","submit"])>-1)){var v=b.e.G(q,"name");if(!b.e.B(v)){var p=
i(v),r="focus";if(b.e.ra(l,["radio","checkbox"])>-1)r="change";b.e.addEventListener(q,r,function(){try{c.Y({k:4,n:p+":"+v})}catch(y){}})}}});b.e.addEventListener(a,"submit",function(){try{c.Y({k:4,n:"Form Submitted"})}catch(l){}})};b.g.h.prototype.Tb=function(){return this.cookie.p(b.g.h.Kb)=="yes"};b=b||{};(function(){function a(d,f,j,m,n,o){n=0;for(var u=m.length;n<u;n++){var s=m[n];if(s){var x=false;for(s=s[d];s;){if(s.ua===j){x=m[s.bb];break}if(s.nodeType===1&&!o){s.ua=j;s.bb=n}if(s.nodeName.toLowerCase()===
f){x=s;break}s=s[d]}m[n]=x}}}function c(d,f,j,m,n,o){n=0;for(var u=m.length;n<u;n++){var s=m[n];if(s){var x=false;for(s=s[d];s;){if(s.ua===j){x=m[s.bb];break}if(s.nodeType===1){if(!o){s.ua=j;s.bb=n}if(typeof f!=="string"){if(s===f){x=true;break}}else if(p.filter(f,[s]).length>0){x=s;break}}s=s[d]}m[n]=x}}}var h=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,i=0,l=Object.prototype.toString,q=false,v=true;[0,0].sort(function(){v=
false;return 0});function p(d,f,j,m){j=j||[];var n=f=f||document;if(f.nodeType!==1&&f.nodeType!==9)return[];if(!d||typeof d!=="string")return j;var o,u,s,x,D,B=true,E=p.sa(f),w=[],J=d;do{h.exec("");if(o=h.exec(J)){J=o[3];w.push(o[1]);if(o[2]){x=o[3];break}}}while(o);if(w.length>1&&y.exec(d))if(w.length===2&&r.ka[w[0]])u=P(w[0]+w[1],f);else for(u=r.ka[w[0]]?[f]:p(w.shift(),f);w.length;){d=w.shift();if(r.ka[d])d+=w.shift();u=P(d,u)}else{if(!m&&w.length>1&&f.nodeType===9&&!E&&r.match.X.test(w[0])&&!r.match.X.test(w[w.length-
1])){o=p.find(w.shift(),f,E);f=o.U?p.filter(o.U,o.D)[0]:o.D[0]}if(f){o=m?{U:w.pop(),D:A(m)}:p.find(w.pop(),w.length===1&&(w[0]==="~"||w[0]==="+")&&f.parentNode?f.parentNode:f,E);u=o.U?p.filter(o.U,o.D):o.D;if(w.length>0)s=A(u);else B=false;for(;w.length;){o=D=w.pop();if(r.ka[D])o=w.pop();else D="";if(o==null)o=f;r.ka[D](s,o,E)}}else s=[]}s||(s=u);s||p.error(D||d);if(l.call(s)==="[object Array]")if(B)if(f&&f.nodeType===1)for(d=0;s[d]!=null;d++){if(s[d]&&(s[d]===true||s[d].nodeType===1&&p.contains(f,
s[d])))j.push(u[d])}else for(d=0;s[d]!=null;d++)s[d]&&s[d].nodeType===1&&j.push(u[d]);else j.push.apply(j,s);else A(s,j);if(x){p(x,n,j,m);p.Cb(j)}return j}p.Cb=function(d){if(K){q=v;d.sort(K);if(q)for(var f=1;f<d.length;f++)d[f]===d[f-1]&&d.splice(f--,1)}return d};p.Tc=function(d,f){return p(d,null,null,f)};p.rb=function(d,f){return p(f,null,null,[d]).length>0};p.find=function(d,f,j){var m;if(!d)return[];for(var n=0,o=r.Za.length;n<o;n++){var u,s=r.Za[n];if(r.ba[s]&&r.ba[s].exec)if(u=r.ba[s].exec(d)){var x=
u[1];u.splice(1,1);if(x.substr(x.length-1)!=="\\"){u[1]=(u[1]||"").replace(/\\/g,"");m=r.find[s](u,f,j);if(m!=null){d=d.replace(r.match[s],"");break}}}}m||(m=f.getElementsByTagName("*"));return{D:m,U:d}};p.filter=function(d,f,j,m){for(var n,o,u=d,s=[],x=f,D=f&&f[0]&&p.sa(f[0]);d&&f.length;){for(var B in r.filter)if(r.ba[B]&&r.ba[B].exec)if((n=r.ba[B].exec(d))!=null&&n[2]){var E,w,J=r.filter[B];w=n[1];o=false;n.splice(1,1);if(w.substr(w.length-1)!=="\\"){if(x===s)s=[];if(r.wb[B])if(n=r.wb[B](n,x,j,
s,m,D)){if(n===true)continue}else o=E=true;if(n)for(var L=0;(w=x[L])!=null;L++)if(w){E=J(w,n,L,x);var Q=m^!!E;if(j&&E!=null)if(Q)o=true;else x[L]=false;else if(Q){s.push(w);o=true}}if(E!==undefined){j||(x=s);d=d.replace(r.match[B],"");if(!o)return[];break}}}if(d===u)if(o==null)p.error(d);else break;u=d}return x};p.error=function(d){throw"Syntax error, unrecognized expression: "+d;};var r=p.Ac={Za:["ID","NAME","TAG"],match:{X:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,Ja:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,
Jb:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,cb:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,ya:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,Ia:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+\-]*)\))?/,xa:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,oa:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},ba:{},jb:{"class":"className","for":"htmlFor"},Na:{href:function(d){return d.getAttribute("href")}},ka:{"+":function(d,
f){var j=typeof f==="string",m=j&&!/\W/.test(f);j=j&&!m;if(m)f=f.toLowerCase();m=0;for(var n=d.length,o;m<n;m++)if(o=d[m]){for(;(o=o.previousSibling)&&o.nodeType!==1;);d[m]=j||o&&o.nodeName.toLowerCase()===f?o||false:o===f}j&&p.filter(f,d,true)},">":function(d,f){var j,m=typeof f==="string",n=0,o=d.length;if(m&&!/\W/.test(f))for(f=f.toLowerCase();n<o;n++){if(j=d[n]){j=j.parentNode;d[n]=j.nodeName.toLowerCase()===f?j:false}}else{for(;n<o;n++)if(j=d[n])d[n]=m?j.parentNode:j.parentNode===f;m&&p.filter(f,
d,true)}},"":function(d,f,j){var m,n=i++,o=c;if(typeof f==="string"&&!/\W/.test(f)){m=f=f.toLowerCase();o=a}o("parentNode",f,n,d,m,j)},"~":function(d,f,j){var m,n=i++,o=c;if(typeof f==="string"&&!/\W/.test(f)){m=f=f.toLowerCase();o=a}o("previousSibling",f,n,d,m,j)}},find:{X:function(d,f,j){if(typeof f.getElementById!=="undefined"&&!j)return(d=f.getElementById(d[1]))&&d.parentNode?[d]:[]},Jb:function(d,f){if(typeof f.getElementsByName!=="undefined"){var j=[];f=f.getElementsByName(d[1]);for(var m=0,
n=f.length;m<n;m++)f[m].getAttribute("name")===d[1]&&j.push(f[m]);return j.length===0?null:j}},ya:function(d,f){return f.getElementsByTagName(d[1])}},wb:{Ja:function(d,f,j,m,n,o){d=" "+d[1].replace(/\\/g,"")+" ";if(o)return d;o=0;for(var u;(u=f[o])!=null;o++)if(u)if(n^(u.className&&(" "+u.className+" ").replace(/[\t\n]/g," ").indexOf(d)>=0))j||m.push(u);else if(j)f[o]=false;return false},X:function(d){return d[1].replace(/\\/g,"")},ya:function(d){return d[1].toLowerCase()},Ia:function(d){if(d[1]===
"nth"){var f=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(d[2]==="even"&&"2n"||d[2]==="odd"&&"2n+1"||!/\D/.test(d[2])&&"0n+"+d[2]||d[2]);d[2]=f[1]+(f[2]||1)-0;d[3]=f[3]-0}d[0]=i++;return d},cb:function(d,f,j,m,n,o){f=d[1].replace(/\\/g,"");if(!o&&r.jb[f])d[1]=r.jb[f];if(d[2]==="~=")d[4]=" "+d[4]+" ";return d},oa:function(d,f,j,m,n){if(d[1]==="not")if((h.exec(d[3])||"").length>1||/^\w/.test(d[3]))d[3]=p(d[3],null,null,f);else{d=p.filter(d[3],f,j,true^n);j||m.push.apply(m,d);return false}else if(r.match.xa.test(d[0])||
r.match.Ia.test(d[0]))return true;return d},xa:function(d){d.unshift(true);return d}},lb:{enabled:function(d){return d.disabled===false&&d.type!=="hidden"},disabled:function(d){return d.disabled===true},checked:function(d){return d.checked===true},selected:function(d){return d.selected===true},parent:function(d){return!!d.firstChild},empty:function(d){return!d.firstChild},$:function(d,f,j){return!!p(j[3],d).length},Oc:function(d){return/h\d/i.test(d.nodeName)},text:function(d){return"text"===d.type},
bd:function(d){return"radio"===d.type},Hc:function(d){return"checkbox"===d.type},Lc:function(d){return"file"===d.type},ad:function(d){return"password"===d.type},submit:function(d){return"submit"===d.type},Pc:function(d){return"image"===d.type},reset:function(d){return"reset"===d.type},button:function(d){return"button"===d.type||d.nodeName.toLowerCase()==="button"},input:function(d){return/input|select|textarea|button/i.test(d.nodeName)}},Bc:{Mc:function(d,f){return f===0},Rc:function(d,f,j,m){return f===
m.length-1},Jc:function(d,f){return f%2===0},Yc:function(d,f){return f%2===1},Sc:function(d,f,j){return f<j[3]-0},Nc:function(d,f,j){return f>j[3]-0},Xc:function(d,f,j){return j[3]-0===f},Ic:function(d,f,j){return j[3]-0===f}},filter:{oa:function(d,f,j,m){var n=f[1],o=r.lb[n];if(o)return o(d,j,f,m);else if(n==="contains")return(d.textContent||d.innerText||p.Ua([d])||"").indexOf(f[3])>=0;else if(n==="not"){f=f[3];j=0;for(m=f.length;j<m;j++)if(f[j]===d)return false;return true}else p.error("Syntax error, unrecognized expression: "+
n)},Ia:function(d,f){var j=f[1],m=d;switch(j){case "only":case "first":for(;m=m.previousSibling;)if(m.nodeType===1)return false;if(j==="first")return true;m=d;case "last":for(;m=m.nextSibling;)if(m.nodeType===1)return false;return true;case "nth":j=f[2];var n=f[3];if(j===1&&n===0)return true;f=f[0];var o=d.parentNode;if(o&&(o.ua!==f||!d.tb)){var u=0;for(m=o.firstChild;m;m=m.nextSibling)if(m.nodeType===1)m.tb=++u;o.ua=f}d=d.tb-n;return j===0?d===0:d%j===0&&d/j>=0}},X:function(d,f){return d.nodeType===
1&&d.getAttribute("id")===f},ya:function(d,f){return f==="*"&&d.nodeType===1||d.nodeName.toLowerCase()===f},Ja:function(d,f){return(" "+(d.className||d.getAttribute("class"))+" ").indexOf(f)>-1},cb:function(d,f){var j=f[1];d=r.Na[j]?r.Na[j](d):d[j]!=null?d[j]:d.getAttribute(j);j=d+"";var m=f[2];f=f[4];return d==null?m==="!=":m==="="?j===f:m==="*="?j.indexOf(f)>=0:m==="~="?(" "+j+" ").indexOf(f)>=0:!f?j&&d!==false:m==="!="?j!==f:m==="^="?j.indexOf(f)===0:m==="$="?j.substr(j.length-f.length)===f:m===
"|="?j===f||j.substr(0,f.length+1)===f+"-":false},xa:function(d,f,j,m){var n=r.Bc[f[2]];if(n)return n(d,j,f,m)}}},y=r.match.xa;function z(d,f){return"\\"+(f-0+1)}for(var C in r.match)if(C!="previousObject"){r.match[C]=new RegExp(r.match[C].source+/(?![^\[]*\])(?![^\(]*\))/.source);r.ba[C]=new RegExp(/(^(?:.|\r|\n)*?)/.source+r.match[C].source.replace(/\\(\d+)/g,z))}function A(d,f){d=Array.prototype.slice.call(d,0);if(f){f.push.apply(f,d);return f}return d}try{Array.prototype.slice.call(document.documentElement.childNodes,
0)}catch(O){A=function(d,f){var j=0;f=f||[];if(l.call(d)==="[object Array]")Array.prototype.push.apply(f,d);else if(typeof d.length==="number")for(var m=d.length;j<m;j++)f.push(d[j]);else for(;d[j];j++)f.push(d[j]);return f}}var K,I;if(document.documentElement.compareDocumentPosition)K=function(d,f){if(d===f){q=true;return 0}if(!d.compareDocumentPosition||!f.compareDocumentPosition)return d.compareDocumentPosition?-1:1;return d.compareDocumentPosition(f)&4?-1:1};else{K=function(d,f){var j,m,n=[],
o=[];j=d.parentNode;m=f.parentNode;var u=j;if(d===f){q=true;return 0}else if(j===m)return I(d,f);else if(j){if(!m)return 1}else return-1;for(;u;){n.unshift(u);u=u.parentNode}for(u=m;u;){o.unshift(u);u=u.parentNode}j=n.length;m=o.length;for(u=0;u<j&&u<m;u++)if(n[u]!==o[u])return I(n[u],o[u]);return u===j?I(d,o[u],-1):I(n[u],f,1)};I=function(d,f,j){if(d===f)return j;for(d=d.nextSibling;d;){if(d===f)return-1;d=d.nextSibling}return 1}}p.Ua=function(d){for(var f="",j,m=0;d[m];m++){j=d[m];if(j.nodeType===
3||j.nodeType===4)f+=j.nodeValue;else if(j.nodeType!==8)f+=p.Ua(j.childNodes)}return f};(function(){var d=document.createElement("div"),f="script"+(new Date).getTime(),j=document.documentElement;d.innerHTML="<a name='"+f+"'/>";j.insertBefore(d,j.firstChild);if(document.getElementById(f)){r.find.X=function(m,n,o){if(typeof n.getElementById!=="undefined"&&!o)return(n=n.getElementById(m[1]))?n.id===m[1]||typeof n.getAttributeNode!=="undefined"&&n.getAttributeNode("id").nodeValue===m[1]?[n]:undefined:
[]};r.filter.X=function(m,n){var o=typeof m.getAttributeNode!=="undefined"&&m.getAttributeNode("id");return m.nodeType===1&&o&&o.nodeValue===n}}j.removeChild(d);j=d=null})();(function(){var d=document.createElement("div");d.appendChild(document.createComment(""));if(d.getElementsByTagName("*").length>0)r.find.ya=function(f,j){j=j.getElementsByTagName(f[1]);if(f[1]==="*"){f=[];for(var m=0;j[m];m++)j[m].nodeType===1&&f.push(j[m]);j=f}return j};d.innerHTML="<a href='#'></a>";if(d.firstChild&&typeof d.firstChild.getAttribute!==
"undefined"&&d.firstChild.getAttribute("href")!=="#")r.Na.href=function(f){return f.getAttribute("href",2)};d=null})();document.querySelectorAll&&function(){var d=p,f=document.createElement("div");f.innerHTML="<p class='TEST'></p>";if(!(f.querySelectorAll&&f.querySelectorAll(".TEST").length===0)){p=function(m,n,o,u){n=n||document;m=m.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!u&&!p.sa(n))if(n.nodeType===9)try{return A(n.querySelectorAll(m),o)}catch(s){}else if(n.nodeType===1&&n.nodeName.toLowerCase()!==
"object"){var x=n.getAttribute("id"),D=x||"__sizzle__";x||n.setAttribute("id",D);try{return A(n.querySelectorAll("#"+D+" "+m),o)}catch(B){}finally{x||n.removeAttribute("id")}}return d(m,n,o,u)};for(var j in d)p[j]=d[j];f=null}}();(function(){var d=document.documentElement,f=d.rb||d.Uc||d.gd||d.Wc,j=false;try{f.call(document.documentElement,"[test!='']:sizzle")}catch(m){j=true}if(f)p.rb=function(n,o){o=o.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!p.sa(n))try{if(j||!r.match.oa.test(o)&&!/!=/.test(o))return f.call(n,
o)}catch(u){}return p(o,null,null,[n]).length>0}})();(function(){var d=document.createElement("div");d.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!d.getElementsByClassName||d.getElementsByClassName("e").length===0)){d.lastChild.className="e";if(d.getElementsByClassName("e").length!==1){r.Za.splice(1,0,"CLASS");r.find.Ja=function(f,j,m){if(typeof j.getElementsByClassName!=="undefined"&&!m)return j.getElementsByClassName(f[1])};d=null}}})();p.contains=document.documentElement.contains?
function(d,f){return d!==f&&(d.contains?d.contains(f):true)}:document.documentElement.compareDocumentPosition?function(d,f){return!!(d.compareDocumentPosition(f)&16)}:function(){return false};p.sa=function(d){return(d=(d?d.ownerDocument||d:0).documentElement)?d.nodeName!=="HTML":false};function P(d,f){var j,m=[],n="";for(f=f.nodeType?[f]:f;j=r.match.oa.exec(d);){n+=j[0];d=d.replace(r.match.oa,"")}d=r.ka[d]?d+"*":d;j=0;for(var o=f.length;j<o;j++)p(d,f[j],m);return p.filter(n,m)}b.find=p;b.U=p.Ac;b.U[":"]=
b.U.lb;b.fd=p.Cb;b.text=p.Ua;b.Qc=p.sa;b.contains=p.contains})();try{var F=new b.global.L,G=new b.g.h(F);if(G.Tb())b.log("User has opted out. No tracking will be performed.");else{function R(){var a=F.K;if(!a.readyState||a.readyState=="complete"||a.addEventListener&&a.readyState=="loaded"){N();return true}else return false}function N(){if(!S){S=true;b.log("Ready. Processing PAQ.");G.Fc();function a(){for(b.e.o(H,function(){var i=this;b.e.ha(i)&&i&&b.e.ra(i[0],["setAccount","identify","setDebugMode"])!==
-1&&M(i)});H.length;)M(H.shift());H.push=M}var c=false;try{b.e.o(H,function(){if(b.e.ha(this)&&this&&this[0]==="enableFlash"){c=true;M(this)}});c?setTimeout(a,1E3):a()}catch(h){b.e.ia(h);a()}}}function M(a){try{if(typeof a=="function")a(G,b);else if(b.e.ha(a)&&a)return G[a[0]].apply(G,a.slice(1))}catch(c){b.e.ia(c)}}var T=F.Ib,H=T._paq;b.e.ha(H)||(T._paq=[]);var S=false;if(!R()){var U=F.K,V=F.Ib;b.e.addEventListener(U,"DOMContentLoaded",N,true);b.e.addEventListener(U,"readystatechange",R,true);b.e.addEventListener(V,
"load",N,true)}}}catch(W){b.e.ia(W)}})();

