var skimlinks_pub_id = '4343X644758';
var skimlinks_site = 'suite101.com';
var skimwords_horizontal_distance = 100;
var skimwords_vertical_distance = 100;
var noskoupon = true;
var noskimproducts = true;
var skimwords_lite = true;
var skimwords_instant = true;
(function(){var T,ua,va,Ra,Sa,Ta,wa,Ua,Va,Wa,xa,ya;function Xa(){B=c.location;H=c.skimwords_decoration||!1;ja=c.skimwords_standard||!1;U=c.skimwords_lite||!1;N=c.skimwords_style||!1;O=c.skimwords_weight||!1;F=c.skimwords_color||!1;C=c.skimlinks_tracking||!1;ka=c.skimlinks_site||!1;Ya=c.skimlinks_domain||"go.redirectingat.com";Za=(P=c.skimlinks_google||!1)||"skimout";V=c.skimlinks_target||!1;za=c.sl_test||!1;W=c.skimlinks_exclude||[];Aa=c.skimlinks_noright||!1;Ba=c.skimlinks_exrel||!1;G=B.hostname.replace(la,
"");Ca=c.skimlinks_byrel||!1;z=c.skimlinks_pub_id||"";$a=c.skimlinks_maxproducts||3;ma=c.noskimproducts||!1;ab=c.noskim||c.noskimlinks||!1;bb=c.noskim||!1;X=c.noskimwords||!1;cb=c.noimpressions||!1;I=c.force_location||c.location.href;db=c.skimwords_hover_name||"dark";J=c.skimwords_instant||!1;eb=c.skimwords_horizontal_distance||0;fb=c.skimwords_vertical_distance||0;gb=c.skimwords_block_ie7||!1;K=c.skimlinks_blocked_tag||!1;Da=c.skimwords_no_limit||!1;Ea=c.skimwords_debug||0;Y=c.skimwords_force_country||
!1;Z=c.skimwords_title||!1;$=c.skimwords_merchant_excludes||!1;aa=c.skimwords_merchant_includes||!1;c.skimwords_flyover_version&&(Fa=c.skimwords_flyover_version);c.skimwords_instant_api_location&&(ua=T=c.skimwords_instant_api_location);c.skimwords_css_location&&(va=c.skimwords_css_location);c.skimwords_flyover_template&&(hb=c.skimwords_flyover_template);c.skimwords_flyover_loop_multi&&(ib=c.skimwords_flyover_loop_multi);c.skimwords_flyover_loop_simple&&(jb=c.skimwords_flyover_loop_simple);c.skimwords_flyover_before&&
(kb=c.skimwords_flyover_before);c.skimwords_flyover_after&&(lb=c.skimwords_flyover_after);c.skimwords_flyover_max_title_multi&&(mb=c.skimwords_flyover_max_title_multi);c.skimwords_flyover_max_title_single&&(nb=c.skimwords_flyover_max_title_single);c.skimwords_flyover_big_thumbnails&&(ob=c.skimwords_flyover_big_thumbnails);if(U||ja)J=!0;K&&(K=K.toLowerCase());ba=c.skimlinks_included_classes||[];ca=c.skimlinks_included_ids||[];o.pub=z;o.pag=I;o.uc=C}function pb(){var a=va+db;e("<link rel='stylesheet' type='text/css' href='"+
(a+".css")+"' />").appendTo("head")}function Tb(){return Math.round(Math.random())-0.5}function Q(a,b,f){f=f||{};f.charset||(f.charset="utf-8");f.target||(f.target=this);return function(a,b,f){var j=f.charset,g=f.target,f=f.async,e=g.document,h=e.getElementsByTagName("head")[0],c=e.createElement("script"),r=!1;c.type="text/javascript";c.charset=j;c.onload=c.onreadystatechange=function(){var a=this.readyState;if(!r&&(!a||"complete"===a||"loaded"===a))c.onload=c.onreadystatechange=null,r=!0,b.call(g)};
c.async=!1!==f;c.src=a;h.appendChild(c)}.call(this,a,b||function(){},f)}function Ub(a){var b=null;if(e)a(e);else{try{b=c.jQuery}catch(f){}b&&b.fn&&b.fn.jquery&&b.fn.jquery>=Sa?(e=L=b,a(e)):Q(Ta,function(){e=L=c.jQuery.noConflict(!0);a(e)},{})}}function qb(a){var b=[],f=0,d;for(d in a)"undefined"!=a[d]&&(b[f]=d,f++);b.sort(Tb);return b}function Vb(a){var b=a.html().slice(0,4);("http"===b||"www."===b)&&a.prepend("<span style='display:none!important;'>&nbsp;</span>")}function da(a){var b="{",f=0,d="",
n;for(n in a)0<f&&(b+=","),d="page"!=n&&"object"==typeof a[n]?da(a[n]):'"'+a[n]+'"',b+='"'+n+'":'+d,f++;return b+"}"}function Ga(){if(!cb){rb=(new Date).getTime();var a=rb-sb;o.slc=tb;o.swc=ub;o.jsl=a;o.guid=R;phrase_data=o.phr;o.phr=[];var b=wa+"track.php?data=",f=da(o).replace(/http:/g,""),d=encodeURIComponent(f).length,n=0,c=1,j=L.browser.msie?1960:7960;e(phrase_data).each(function(a,e){phrase_string=da(e).replace(/http:/g,"");current_string=0!=n?",":"";current_string+='"'+n+'":'+phrase_string;
if(d+encodeURIComponent(current_string).length<j)f=f.replace('},"pub"',current_string+'},"pub"'),d=encodeURIComponent(f).length;else{var h=b+encodeURIComponent(f);(2E3>h.length||!L.browser.msie&&8E3>h.length)&&Q(h,!1,{async:!0});o.t=0;f=da(o).replace(/http:/g,"");current_string=current_string.replace('"'+n+'":','"0":');f=f.replace('},"pub"',current_string+'},"pub"');d=encodeURIComponent(f).length;n=0;c++}n++});a=b+encodeURIComponent(f);(2E3>a.length||!L.browser.msie&&8E3>a.length)&&Q(a,!1,{async:!0})}}
function Wb(a,b){x=e(a).mouseenter(function(){D=!0}).mouseleave(function(){na();D=!1});x.appendTo(Xb);var f=x.find(".flyover2-body");f.html(b);f.find(".skimwords-hover-link").click(vb).bind("contextmenu",wb);f.find(".skimwords-ebay-link").click(xb).bind("contextmenu",xb);x.find(".flyover2-close").click(function(){na();D=!1});f.find(".flyover2-row").not(".first").hover(function(){e(this).addClass("flyover2-row-hover")},function(){e(this).removeClass("flyover2-row-hover")});f.find(".flyover2-box-container").hover(function(){e(this).addClass("flyover2-box-container-hover")},
function(){e(this).removeClass("flyover2-box-container-hover")})}function na(){if(c.skimwords_persistent_flyover)return!1;c.setTimeout(function(){if(!D&&x){var a=yb;zb=(new Date).getTime();var b={};b.dur=zb-Ab;b.pub=z;b.pag=I;b.guid=R;b.gid=e(a).attr("data-group-id");b.phr=e(a).text();b.url=e(a).attr("href");b.ver=p;b.pc=x.find(".merc-link").size();a=wa+"hover.php?data="+encodeURIComponent(da(b));Q(a,!1,{async:!0});x.fadeOut("fast").slideUp();x.remove();D=x=!1}},Ua)}function Yb(a,b,f,d,n){a.attr("data-flyover",
Ha);a.mouseenter(function(c){Ia=setTimeout(function(){var j=ea(hb,{id:f,multiclass:d?"flyovermulti":"",hover_title:n?n:""});x||Wb(j,b,d);var j=c.pageX,g=c.pageY,k=x.width(),h=x.height(),m=e(t).width();e(t).scrollTop();var r=0,j=j-k/2;j+r+k>m&&(r=0-k);x.css({top:g+"px",left:j+"px",marginTop:0-h-5+"px",marginLeft:r+"px"});D||x.fadeIn("fast");Ab=(new Date).getTime();yb=a;D=!0},500)}).mouseleave(function(){Ia&&clearTimeout(Ia);na();D=!1});Ha++}function Zb(a){a=a.split(".");a[0]=a[0].split("").reverse().join("");
a[0]=a[0].replace(/(\d{3})(?!,)/g,"$1,");a[0]=a[0].split("").reverse().join("");a[0]=0==a[0].indexOf(",")?a[0].substring(1):a[0];return a.join(".")}function Bb(a){function b(a,b,d,f,c,n,g){return'<a href="'+d.url+'" class="'+(f||"")+' skimwords-link skimwords-hover-link" data-skim-creative="'+g+'" data-skim-product="'+n+'" data-skimwords-word="'+c+'" data-skimwords-id="'+d.product_id+"X"+d.merchant_id+'" title="'+b+'" target="_blank" border=0>'+a+"</a>"}if(a)for(var f=e(".skimwords-link"),d=0,n=f.length;d<
n;d++){var c=f[d],j=parseInt(e(c).attr("data-group-id")),c=e(c),g=c.attr("data-skimwords-id"),k=c.attr("data-skimwords-word");c.text();var h=parseInt(c.attr("data-skim-creative"))%10,m=0,r="",u,E=!0,S,y,A;if(j){if(y=a.groups[j]){u=0;S=!1;var r=[],fa="The availability and pricing displayed are not guaranteed and are subject to change.",E=!0;for(A in y)if(y.hasOwnProperty(A)&&y[A].mt){S=!0;break}for(A in y)if(y.hasOwnProperty(A)){var s=y[A];if(S){if(E=!1,!s.mt)continue}else-1!==s.url.indexOf("ebay.")&&
(E=!1);1E7<s.product_id&&6!=parseInt(h)?A=s.product_id-1E7:(parseInt(h),A=s.product_id);var t=A==g,w=S?mb:nb;if(u<$a&&s.price&&" "!=s.price){var o="",q="$",m=1;u++;c.attr("title","");s.price=Zb(s.price.toString());full_title=s.title;s.title.length>w&&(s.title=s.title.substr(0,w-3)+"...");if(s.country)if("GB"===s.country)q="&pound;";else if("DE"==s.country)var fa=String.fromCharCode(252),q=String.fromCharCode(246),w=String.fromCharCode(228),v=String.fromCharCode(196),fa="Die Verf"+fa+"gbarkeit der Produkte und der ver"+
q+"ffentlichte Preis werden nicht garantiert. Preis"+w+"nderungen und "+v+"nderung der Verf"+fa+"gbarkeit vorbehalt.",q="&euro;";w={};w.imageLink=b('<img src="'+s.image+(ob?"":"_thumb")+'" style="border:0px !important;" title="'+full_title+'" />',"",s,"image",k,A,"2"+p+"1"+h);w.titleLink=b(s.title,full_title,s,"product-link flyover2-link",k,A,"2"+p+"2"+h);w.merchantLink=b(s.merchant_name,"",s,"merc-link flyover2-clickable",k,s.product_id,"2"+p+"3"+h);w.priceLink=b(q+s.price,"",s,"flyover2-clickable",
k,s.product_id,"2"+p+"3"+h);w.emptyLink=b("",full_title,s,"flyover2-arrow product-link",k,s.product_id,"2"+p+"2"+h);w.plainLink=s.url;S?(p=parseInt(Fa)+1,10>p&&(p="0"+p),w.closeButton=t?"<div class='flyover2-close nowidth'></div>":"",o=ea(ib,w)):(p=parseInt(Fa),10>p&&(p="0"+p),t&&(o=ea(kb,w)),w.extraClass=t?"flyover2-row-main":"",o+=ea(jb,w));t?r.splice(0,0,o):r.push(o)}}E&&(g="_sacat=See-All-Categories&_nkw="+k,skim_gets="&skimlinks_search_product=ebay&skimlinksurl="+encodeURIComponent("http://www.ebay.com/sch/i.html?")+
"&skimlinkspubid="+z,naked_link="http://www.ebay.com/sch/i.html?"+g,ebay_link="http://go.redirectingat.com/forms.php?"+g+skim_gets,r.push(ea(lb,{link1:'<a href="'+naked_link+'" data-skimlinks-href="'+ebay_link+'" target="_blank" class="search-link flyover2-clickable skimwords-ebay-link" title="Search on eBay">Search on eBay</a>',link2:'<a href="'+naked_link+'" data-skimlinks-href="'+ebay_link+'" target="_blank" class="flyover2-arrow flyover2-clickable skimwords-ebay-link" title="Search on eBay"></a>'})));
r=r.join("")}m&&!(e.browser.msie&&"7.0">e.browser.version)&&e.support.boxModel&&Yb(c,r,j,S,fa)}}}function $b(){var a=ja?"standard":U?"lite":"";if(e.browser.msie)if(c.XDomainRequest){var b=new XDomainRequest;b&&(b.open("POST",T),b.onload=function(){var a={};try{a=JSON.parse(b.responseText)}catch(f){a=eval("("+b.responseText+")")}oa(a)},b.onerror=function(){},b.onprogress=function(){},b.ontimeout=function(){},b.async=!0,b.send("data="+encodeURIComponent('{"instant":"1","pubcode":"'+z+'","page":"'+I+
'"'+(Y?',"force_country":"'+Y+'"':"")+($?',"merchant_excludes":"'+$+'"':"")+(aa?',"merchant_includes":"'+aa+'"':"")+"}")+"&filter="+a+"&content="+encodeURIComponent(M)))}else J=!1,ga("skimwordsDataCallback");else try{e.ajax({url:T,type:"POST",async:!0,crossDomain:!0,data:{data:'{"instant":"1","pubcode":"'+z+'","page":"'+I+'"'+(Y?',"force_country":"'+Y+'"':"")+($?',"merchant_excludes":"'+$+'"':"")+(aa?',"merchant_includes":"'+aa+'"':"")+"}",debug:Ea,filter:a,content:M},success:function(a){var b={};
try{b=JSON.parse(a)}catch(f){b=eval("("+a+")")}oa(b)},error:function(){J=!1;ga("skimwordsDataCallback")},complete:function(){}})}catch(f){J=!1,ga("skimwordsDataCallback")}}function pa(a,b){function f(a){var b=a.nodeName===d?e.trim(a.nodeValue):null;return b?(v.push(a),l++,10>l?j.push(b):(l=0,j.push(b+"\n"),M+=j.join(" SKMLNKS "),j=[]),!0):!1}a=a||[];b=b||[];0==a.length&&(a[0]="body");b.push("div[class=widget-content]");b.push("div[class=googleAdText]");b.push("div[id=ad]");b.push("div[id=banner]");
b.push("div[id=advertisement]");b.push("div[id=adv_container]");b.push("div[class=ad]");b.push("div[class=banner]");b.push("div[class=advertisement]");b.push("div[class=ad_container]");-1!=B.href.indexOf(".google.")?(b.push("td[class=gac_c]"),b.push("table[id=mbEnd]"),b.push("span[id=taw]"),b.push("td[class=std]"),b.push("table[class=gssb_e]")):-1!=B.href.indexOf(".yahoo.")?(b.push("ul[class=spns reducepx-spnslist]"),b.push("ul[class*=reducepx-spnslist]"),b.push("ul[id=east]")):-1!=B.href.indexOf(".aol.")?
(b.push("div[class=sllLink]"),b.push("div[class=n]")):-1!=B.href.indexOf(".bing.")&&(b.push("div[class=sb_adsW]"),b.push("div[id=sidebar]"));if(!v.length)for(var d=t.createTextNode("").nodeName,c=[],l=0,j=[],g=0,k=a.length;g<k;g++)for(var h=e(a[g]),m=0,r=h.length;m<r;m++){c.push(h[m]);for(j=[];0<c.length;)if(node=c.shift())if(node.hasChildNodes()){children_to_callback=[];for(i=0,k=node.childNodes.length;i<k;i++)(child=node.childNodes[i])&&child.nodeName&&!f(child)&&-1!==",p,section,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,".indexOf(","+
child.nodeName.toLowerCase()+",")&&Ja(L(child),"skimwords",!0)&&c.push(child)}else f(node);M+=j.join(" SKMLNKS ")+"\n";j=[]}}function Cb(a){return a.replace(/[-[\]{}()*+?.,\\^$|#]/g,"\\$&")}function Db(a,b,f,d,c,e,j,g,k,h){var m=a.word.split(" "),r=Cb(a.word);Z&&(a.title=Z);a.title="de"==Ka.toLowerCase()?"Shopping link hinzugef\u00fcgt von SkimWords":Z?Z:"Shopping link added by SkimWords";if("cn"===b||"ko"===b||"ja"===b)b="(?:"+r+")",f='<a href="'+a.link+'" class="skimwords-link" target="_blank" style="'+
f+" "+d+" "+c+" "+e+' " data-skimwords-id="'+j+'" data-skimwords-word="'+encodeURIComponent(a.word)+'" data-group-id="'+g+'" data-skim-creative="'+h+'" data-skim-product="'+k+'" title="'+a.title+'">$1</a>';else if((1<m.length||"4"!==a.action_type||1===m.length&&/(?:\d[a-z])|(?:[a-z]|\d)/i.test(m[0]))&&(2>m.length||/[a-zA-Z]+/.test(a.word)))b="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/\\?])?("+r+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/\\?])*(?:[\\s]+|$)",f='$1$2<a href="'+a.link+'" class="skimwords-link" target="_blank" style="'+
f+" "+d+" "+c+" "+e+' " data-skimwords-id="'+j+'" data-skimwords-word="'+encodeURIComponent(a.word)+'" data-group-id="'+g+'" data-skim-creative="'+h+'" data-skim-product="'+k+'" title="'+a.title+'">$3$4</a>$5$6';else return null;a=b.replace(/\?:/g,"");return{search_regex:RegExp(b,"i"),repl_regex:RegExp(a,"i"),repl_text:f}}function Eb(a,b,f,d){var c,l,j,g,k,h;if(!a)return!1;f=t.createTextNode("").nodeName;c=a.data;for(var m=0,r=La.length;m<r;m++)if(g=La[m],b[g].group_id?(l=b[g].group_id,j="2"+p+"0"+
b[g].action_type):(l=0,j="1"+p+"0"+b[g].action_type),h=b[g].id,k=1E7<parseInt(h)&&6!=b[g].action_type?h-=1E7:0,j=Db(b[g],Ma,F,O,H,N,h,l,k,j),l=a&&0<b[g].limit&&j&&j.search_regex.test(c)){repl_regex=j.repl_regex;c=j.repl_text;if(!(0==b[g].limit||!Da&&ha==q.maxkeywords)){ha++;b[g].limit--;Fb++;m={};m.w=b[g].word;m.lp=b[g].link;0==b[g].group_id?(m.t="1"+p+"0"+b[g].action_type,m.pid=0):(m.t="2"+p+"0"+b[g].action_type,m.pid=6==b[g].action_type?g:g-1E7);-1==e.inArray(m,o.phr)&&o.phr.push(m);b=a.data.replace(repl_regex,
c);g=t.createElement("span");c=t.createDocumentFragment();for(g.innerHTML=b;g.firstChild;)g.firstChild.nodeName==f?(obj=c.appendChild(g.firstChild),v.push(obj)):obj=c.appendChild(g.firstChild);-1!=d&&(v[d]=0);e(a).replaceWith(c)}return!1}}function Gb(a,b){var f,d;if(Da||ha<q.maxkeywords){f=qb(b);for(var c=0,l=f.length;c<l;c++){var j=f[c];if(0===a||j==a||0>a&&j!=-a){La=qb(b[j]);var g=v.length,k=Math.ceil(g/2);for(d=0;d<=k;d++){var h=e(v[d]).parent().eq(0);Eb(v[d],b[j],h,d);d!=k&&(h=e(v[g-1-d]).parent().eq(0),
Eb(v[g-1-d],b[j],h,g-1-d));g=v.length;k=Math.ceil(g/2)}}}}}function ac(a){for(var b,f=[],d=0,c=v.length;d<c;d++){b=v[d];var e=b.nodeValue,j=b.parentNode;if(j){var g=bc(b,a);g.sort(function(a,b){return a.start-b.start});if(g&&g.length){for(var k=t.createDocumentFragment(),h=0,m=0,r=g.length;m<r;m++){var u=g[m],E=t.createElement("span");E.className="skimwords-potential";h=t.createTextNode(e.substring(h,u.start));k.appendChild(h);E.innerHTML=u.text;k.appendChild(E);h={};h.node=E;h.match=u;f.push(h);
h=u.start+u.text.length}e=t.createTextNode(e.substring(h));k.appendChild(e);j.replaceChild(k,b)}}}return f}function bc(a,b){var f,d,c,e,j,g,k,h;overlapping_matches=[];matches=[];if(!a)return matches;t.createTextNode("");f=a.data;(function(){if(qa)h=qa;else{h=[];for(var a in b)if(b.hasOwnProperty(a)){var f=b[a],g;for(g in f)if(f.hasOwnProperty(g)){var k=f[g];k.group_id?(d=k.group_id,c="2"+p+"0"+k.action_type):(d=0,c="1"+p+"0"+k.action_type);j=k.id;e=1E7<parseInt(j)&&6!=k.action_type?j-=1E7:0;var m=
Db(k,Ma,F,O,H,N,j,d,e,c);m&&h.push({phrase:k,repl_regex:m.repl_regex,replacement:m.repl_text,regex:m.search_regex})}}h.sort(function(a,b){var f=parseInt(a.phrase.action_type),c=parseInt(b.phrase.action_type),d=c-f;return!d?b.phrase.word.length-a.phrase.word.length:4===c?1:4===f?-1:d});qa=h}})();for(var m=0,r=h.length;m<r;m++){var u=h[m];phrase=u.phrase;k={};k.start=-1;k.phrase=phrase;k.text=null;(function(){if(a&&0<phrase.limit){var b=f.match(u.regex);if(b){var c=b[0].indexOf(b[1]);k.start=b.index+
(-1!==c?c:0);k.text=f.substring(k.start,k.start+b[1].length)}else k.start=-1}})();g=0;-1!=k.start&&k.text&&(g=1);g?(k.repl_regex=u.repl_regex,k.replacement=u.replacement,overlapping_matches.push(k)):k.start=-1}(function(){if(overlapping_matches&&overlapping_matches.length){overlapping_matches.sort(function(a,b){return b.text.length-a.text.length});for(var a=overlapping_matches.length,b=[],f=0;f<a;f++){var c=overlapping_matches[f],d={},g=!0;d.lower=c.start;d.upper=c.start+c.text.length;for(var e=0,
j=b.length;e<j;e++){var h=b[e];if(d.lower>=h.lower&&d.lower<=h.upper||d.upper<=h.upper&&d.upper>=h.lower){g=!1;break}}g&&(matches.push(c),b.push(d))}overlapping_matches=b=null}})();return matches}function cc(a,b){if(a.length){var f,c,n,l,j=[],g=0,b=b||0,k=e.browser.msie&&"9.0">e.browser.version;k&&(n=e("body").text().length,3E4<n?b=Math.ceil(n/1E4):k=!1);for(n=0,l=a.length;n<l;n++){c=a[n];f=c.node;c=c.match;var h=!1;if("1"===c.phrase.action_type||"2"===c.phrase.action_type)h=!0;k&&(h=!0);"17075X740592"===
z&&e(f).parents(".atma-norules").length&&(h=!0);if(Ja(e(f),"skimwords")&&(h||dc(f,j))){g++;h=c.phrase;if(0!=h.limit){ha++;h.limit--;Fb++;var m={};m.w=h.word;m.lp=h.link;0==h.group_id?(m.t="1"+p+"0"+h.action_type,m.pid=0):(m.t="2"+p+"0"+h.action_type,m.pid=6==h.action_type?h.id:h.id-1E7);-1==e.inArray(m,o.phr)&&o.phr.push(m);c=(f.data?f.data:f.childNodes[0].data).replace(c.repl_regex,c.replacement);h=t.createElement("span");m=t.createDocumentFragment();for(h.innerHTML=c;h.firstChild;)void 0==h.firstChild.nodeName?
(obj=m.appendChild(h.firstChild),v.push(obj)):obj=m.appendChild(h.firstChild);e(f).replaceWith(m)}if(b&&g>=b)break}}}}function Na(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return{x:b,y:c}}function ec(a,b,c){var d=0,e=a.length-1,l,j;for("function"!==typeof c&&(c=cmp);d<=e;)if(l=Math.floor((e+d)/2),j=c(b,a[l]),0<j)d=l+1;else if(0>j)e=l-1;else return{found:!0,index:l};return{found:!1,index:d}}function dc(a,b){function c(a,b){Math.abs(a.x-b.x)<=p&&Math.abs(a.y-
b.y)<=y&&(q=!0);return a.y===b.y?a.x-b.x:a.y-b.y}var d,e,l,j,g,k,h,m,r,u,o;l=Na(a);var p=eb,y=fb,q=!1;if(!p&&!y)return!0;p=!p?0:p;y=!y?4:y;e=[{test:function(a){return 0<a&&a<b.length},count:function(a){return a-1}},{test:function(a){return a<b.length},count:function(a){return a+1}}];d=t.createElement("span");d.style.position="absolute";a.nextSibling?a.parentNode.insertBefore(d,a.nextSibling):a.parentNode.appendChild(d);d=Na(d);d=t.createElement("span");d.style.position="absolute";a.nextSibling?a.parentNode.insertBefore(d,
a.nextSibling):a.parentNode.appendChild(d);d=Na(d);j=[l,d];for(g=0;g<j.length;g++){k=j[g];if(q)break;h=ec(b,k,c);for(u=0;u<e.length&&!(o=e[u],q);u++)for(m=o.count(h.index);o.test(m);m=o.count(m)){r=b[m];if(!(Math.abs(k.y-r.y)<=y))break;if(Math.abs(k.x-r.x)<=p){q=!0;break}}}if(q)return!q;e=l.y===d.y?l.x-d.x:l.y-d.y;0<e?e=d:0>e?(e=l,l=d):(e=l,l=null);h.index===b.length?(b.push(e),l&&b.push(l)):l?b.splice(h.index,0,e,l):b.splice(h.index,0,e);return!q}function oa(a){if(q=a)if(q.guid&&(R=q.guid),q.lang&&
(Ma=q.lang.toLowerCase()),pa(q.includes,q.excludes),v.length&&e(q.words).size()){a=1;if(e.browser.mozilla){var b=/Firefox\/(\d.\d)/.exec(navigator.userAgent);b&&2<=b.length&&3.7>=parseFloat(b[1])&&(a=0)}else e.browser.msie&&"8.0">e.browser.version&&(a=0);a?(a=ac(q.words),cc(a,q.maxkeywords)):(Gb(4,q.words),Gb(-4,q.words));if(e.browser.msie&&"9.0">e.browser.version){var a=e(".skimwords-link"),f,d,n,l=/^\s/;for(b=0,f=a.length;b<f;b++){n=a[b];if((d=n.previousSibling)&&d.nodeValue&&d.nodeValue.length&&
l.test(d.nodeValue[d.nodeValue.length-1]))d.nodeValue+=" ";if((d=n.nextSibling)&&d.nodeValue&&d.nodeValue.length&&l.test(d.nodeValue[0]))d.nodeValue=" "+d.nodeValue}}ub=e(".skimwords-link").length;c.setTimeout(function(){for(var a=e(".skimwords-link"),b,c=0,f=a.length;c<f;c++)b=e(a[c]),b.click(vb),b.bind("contextmenu",wb);if("17075X740592"===z){a=e(".atma-norules a.skimwords-link");c=0;for(f=a.length;c<f;c++)a[c].style.color="#C9C7C7 !important",a[c].style.fontStyle="normal !important"}},10)}ma||
(q.groups?(ia||(pb(),ia=!0),Bb({groups:q.groups})):(Hb=e(t),Hb.ready(function(){var a=e("a[href]:not(:has(img))"),b={},c={},f={};e([]);e([]);for(var d=0,n=a.length;d<n;d++){var l=a[d],p=l.className,q=l.href,o=l.hostname.replace(la,""),l=l.getAttribute("data-skimwords-id");if(-1==q.indexOf(G)||!G)if(p&&-1!=p.indexOf("skimwords")){if(o&&!c[o]&&(Ib.push(o),c[o]=!0),l){p=l.split(" ");q=0;for(o=p.length;q<o;q++)if(l=p[q],(l=e.trim(l))&&!f[l])Jb.push(l),f[l]=!0}}else o&&!b[o]&&(Kb.push(o),b[o]=!0)}e(".skimwords-link");
e('a[href^=http://]:not([href*="'+G+'"],[class=skimwords-link])');ia||(pb(),ia=!0);a='{"groups": [';b=0;c=e(".skimwords-link");f=0;for(d=c.length;f<d;f++)n=c[f],p=e(n).attr("data-group-id"),parseInt(p)&&"0"!=parseInt(p)&&(0!=b&&(a+=","),a+='"'+e(n).attr("data-group-id")+'"',b++);b&&Q(Va+"?callback=productDataCallback&data="+(a+"]}"))})));Ga()}function ga(a){if(U||ja)var a="instantDataCallback",b=U?"&filter=lite":"&filter=standard";else b="";if(J)var c=encodeURIComponent('{"instant":"1","page":"'+
I+'"}'),d=T;else c=encodeURIComponent('{"page":"'+I+'"}'),d=ua;Q(d+"?callback="+a+"&data="+c+"&debug="+Ea+b)}function fc(){var a;if("undefined"===typeof ra){ra={};a=W.concat(Wa);for(var b=0,c=a.length;b<c;b++){var d=a[b];ra[d]=d.length}}return ra}function Lb(a){var b=!1,c=fc(),d=a.length;e.each(c,function(c,f){if(0===c.indexOf("*")){if(c=c.slice(1),f-=1,-1!==a.lastIndexOf(c)&&a.lastIndexOf(c)===d-f)return b=!0,!1}else if(a===c)return b=!0,!1});return b}function Oa(a){var b;if(!(b=!a))if(!(b=Ca&&a===
Ca)){if("undefined"===typeof sa){sa={};b=Ba?[Ba]:[];b=b.concat(xa);for(var c=0,d=b.length;c<d;c++)sa[b[c]]=!0}b=!sa[a]}return b}function gc(a){var b=c.pageTracker,f=c.urchinTracker,a="/"+Za+"/"+a;b&&b._trackPageview?b._trackPageview(a):f&&f(a)}function ta(a,b){var c,d,e;a&&("img"==a.prop("tagName").toLowerCase()&&(a=a.parent()),d=a[0],c=d.href,(e=a.data("skimlinks-href"))||(e=a.hasClass("skimwords-link")?"http://"+Ra+"/?id="+z+(C?"&xcust="+C:"")+"&xs=2&url="+encodeURIComponent(c)+"&xguid="+R+(void 0!==
a.attr("data-skimwords-word")?"&xword="+a.attr("data-skimwords-word"):"&xword=")+(void 0!==a.attr("data-skim-creative")?"&xcreo="+a.attr("data-skim-creative"):"&xcreo=0")+(void 0!==a.attr("data-skim-product")?"&xpid="+a.attr("data-skim-product"):"&xpid=0")+"&sref="+encodeURIComponent(B):Ja(a,"skimlinks")?"http://"+Ya+"/?id="+z+(ka?"&site="+ka:"")+(za?"&test="+za:"")+(C?"&xcust="+C:"")+"&xs=1&url="+encodeURIComponent(c)+"&xguid="+R+(a&&void 0!==a.attr("data-skim-creative")?"&xcreo="+a.attr("data-skim-creative"):
"&xcreo=0")+"&sref="+encodeURIComponent(B):c,a.data("skimlinks-href",e)),b&&gc(c),a.data("skimlinks-orig-link")||a.data("skimlinks-orig-link",c),d.href=e,setTimeout(function(){d.href=a.data("skimlinks-orig-link")},100))}function Pa(a,b){var c=a.target;anchor=e(c);c.href||(c=a.currentTarget,anchor=e(c));ta(anchor,b)}function wb(a){Pa(a,!1)}function vb(a){Pa(a,P)}function Mb(a){Pa(a,P)}function xb(a){var b=a.target;anchor=e(b);b.href||(b=a.currentTarget,anchor=e(b));anchor.data("skimlinks-href",anchor.attr("data-skimlinks-href"));
ta(anchor,P)}function Nb(a){a=a.target;e(a);a=encodeURIComponent('{"pubcode":"'+z+'","referrer":"'+B+'","site":"'+ka+'","url":"'+a.href+'","custom":"'+C+'","product":"1"}');e.getScript(ya+"?call=track&data="+a)}function hc(a,b){var c=!1;b.merchant_domains&&e.each(b.merchant_domains,function(b,e){if(a==e)return c=!0});return c}function ic(a){if(ba.length)for(var b=0,c=ba.length;b<c;b++)if(a.parents("."+ba[b]).length)return!0;if(ca.length){b=0;for(c=ca.length;b<c;b++)if(a.parents("#"+ca[b]).length)return!0}return!1}
function jc(a){if(!K)return!0;a=a[0].previousSibling;if(!a)return!0;var a=e.trim(L(a).text().toLowerCase()),b=a.indexOf("["+K+"]");return!(-1!==b&&b+(K.length+2)===a.length)}function Ob(){if(X||bb)return Pb;F&&(F=-1==F.indexOf("#")?"color:#"+F+" !important;":"color:"+F+" !important;");O=O?"font-weight: "+O+" !important;":"";N=N?"font-style: "+N+" !important;":"";H="double"==H?"border-bottom: 1px double !important;":H?"text-decoration: "+H+" !important;":"text-decoration: underline !important;";J?
ga("instantDataCallback"):ga("skimwordsDataCallback")}function Qa(){if(ab)return X?Ga():Ob(),Pb;W=W.concat(xa);c.skimlinks_site&&W.push(c.skimlinks_site);C&&!kc.test(C)&&(C=!1);for(var a=e("a[href]"),b=[],f={},d=0,n=a.length;d<n;d++){var l=a[d],j=e(l),g=l.hostname.replace(la,""),l=e.trim(l.href),j=j.attr("rel");Qb.test(l)&&-1===g.indexOf(G)&&-1===G.indexOf("."+g)&&!Lb(g)&&Oa(j)&&g&&!f[g]&&(b.push(g),f[g]=!0)}a=encodeURIComponent;f='{"pubcode":"'+z+'","domains":';d="";if(b.length){n=0;for(g=b.length;n<
g;n++)d+='"'+b[n]+'",';d=d.slice(0,-1)}b=a(f+("["+d+"]")+"}");e.getScript(ya+"?callback=skimlinksApplyHandlers&data="+b);return!0}function Rb(){Ib=[];Jb=[];Kb=[];merchantLimits=[];totalDisplayed=e(".skimlinks-icon-link").size();v=[];M="";Ha=0;var a=e("a");a.data("skimlinks-href","");a.data("skimlinks-orig-link","");Xa();Qa()}function Sb(){for(var a=e(".skimwords-link"),b=ha=0,c=a.length;b<c;b++){var d=e(a[b]);d.after(d.text());d.remove()}}var ea=function(){var a=RegExp("{{([a-z0-9_][\\.a-z0-9_]*)}}",
"gi");return function(b,c){return b.replace(a,function(a,b){for(var e=b.split("."),j=e.length,g=c,k=0;k<j;k++)if(g=g[e[k]],k===j-1)return g})}}(),c=this,t=c.document;Ta="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js";Sa="1.5.5";Ra=c.skimlinks_domain||"go.redirectingat.com";Wa="*doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");xa=["noskim","norewrite"];T="http://i.skimresources.com/api/index.php";
ua="http://i.skimresources.com/api/index.php";Va="http://i.skimresources.com/api/product.php";ya="http://r.skimresources.com/api/";wa="http://t.skimresources.com/api/";va="http://s.skimresources.com/css/flyover-";Ua=250;var cb,X,bb,ab,ma,$a,z,Ka="",R="",Pb=function(){},la=/^www\./,Qb=/^\/\/|https?:\/\//,kc=/^[a-z0-9_\\|]+$/i,B,ra,sa,ba=[],ca=[],sb=null,rb=null,Ab=null,zb=null,G,Ca,Ba,Aa,W,za,V,P,Za,Ya,ka,C,tb=0,F,O,N,U,ja,H,J,ub=0,p="02",Fa="02",v=[],M="",db,Ma="en",eb,fb,gb,K,Da,Ea,Z,Y,q,I,Fb=0,
ha=0,La,ia=!1,qa,aa=!1,$=!1,hb="<div id='flyover2-{{id}}' class='flyover2-outer {{multiclass}}'><div class='flyover2-body'></div><div class='flyover2-bottom'><a class='bottom-link' target='_blank' href='http://www.skimlinks.com/?ref=flyover' ref='hoverover'></a><a class='bottom-link-2' title='{{hover_title}}'></a></div></div>",ib='<div class="flyover2-row">{{closeButton}}{{imageLink}}{{titleLink}}<div class="flyover2-box-container"><div class="flyover2-merc-section"><span class="flyover2-merc">{{merchantLink}}</span></div><div class="flyover2-price">{{priceLink}}</div>{{emptyLink}}<br /></div></div>',
jb='<div class="flyover2-row {{extraClass}}"><div class="flyover2-merc-section"><span class="flyover2-merc">{{merchantLink}}</span></div><div class="flyover2-price">{{priceLink}}</div>{{titleLink}}<br /></div>',kb='<div class="flyover2-row first"><div class="flyover2-close nowidth"></div>{{imageLink}}{{titleLink}}</div>',lb='<div class="flyover2-row"><div class="flyover2-search-section">{{link1}}</div>{{link2}}</div>',mb=73,nb=63,ob=!1,x,Ha=0,yb,D=!1,Ia=null,Hb,Xb=t.body,Ib=[],Jb=[],Kb=[],o={pag:"",
phr:[],pub:"",slc:0,swc:0,jsl:0,jsf:"",guid:"",uc:"",t:1},e,L;Xa();var Ja=function(){var a=/\bnoskim\b/i;return function(b,c,d){var e=b[0].className||"",d=d||!1;return!a.test(e)&&!RegExp("\\b"+Cb("no"+c)+"\\b","i").test(e)&&(d||0==b.parents(".no"+c).length&&0==b.parents(".noskim").length)?!0:!1}}();c.skimlinks=Qa;c.mugicPopWin=Mb;c.mugicRight=Mb;c.skimwordsDataCallback=oa;c.instantDataCallback=function(a){a.country&&(Ka=a.country);if(1==a.nc){if(a.includes)try{pa(a.includes,a.excludes)}catch(b){pa(["body"],
[])}else pa(["body"],[]);$b()}else 2!=a.nc&&oa(a)};c.skimlinksApplyHandlers=function(a){var b=e("a[href]"),c=0<ba.length||0<ca.length;a.country&&(Ka=a.country);a.guid&&(R=a.guid);for(var d=0,n=b.length;d<n;d++){var l=b[d],j=e(l),g=l.hostname.replace(la,""),l=e.trim(l.href),k=j.attr("rel"),h=e.browser.msie;if((!c||ic(j))&&jc(j))if(hc(g,a)){if(Oa(k)){V&&j.attr("target",V);if(h){if(-1!==encodeURIComponent(l).indexOf("%C3%82%C2%A3"))return!0;Vb(j)}j.click(function(){var a=e(this);ta(a,P)});tb++;Aa||j.bind("contextmenu",
function(){var a=e(this);ta(a,P)})}}else Qb.test(l)&&-1===g.indexOf(G)&&-1===G.indexOf("."+g)&&!Lb(g)&&Oa(k)&&(V&&j.attr("target",V),j.click(Nb),Aa||j.bind("contextmenu",Nb))}X?Ga():Ob()};c.productDataCallback=Bb;c.skimlinksReload=Rb;c.skimwordsReload=function(){na();D=!1;qa=null;e("head").find("link[rel=stylesheet]").each(function(){this.href&&-1!==this.href.indexOf("skimlinks.")&&e(this).remove()});ia=!1;Sb();Rb()};(function(){sb=(new Date).getTime();-1==B.href.indexOf("https://")&&Ub(function(a){a.browser.msie&&
"8.0">a.browser.version&&(gb?X=!0:(a=/Windows NT (\d.\d)/.exec(navigator.userAgent))&&2<=a.length&&6>=parseFloat(a[1])&&(ma=!0));ma&&(p="00");Sb();Qa()})})()})();