var skimlinks_pub_id = '27372X857815';
var skimlinks_site = 'languagesandnumbers.com';
var skimwords_hover_name = 'neutral';
var skimwords_horizontal_distance = 100;
var skimwords_vertical_distance = 100;
var noskoupon = true;
var noskimproducts = true;
var skimwords_instant = true;
(function(){var R,na,oa,La,Ma,Na,pa,Oa,Pa,Qa,qa,ra;function Ra(){y=c.location;F=c.skimwords_decoration||!1;ba=c.skimwords_standard||!1;S=c.skimwords_lite||!1;M=c.skimwords_style||!1;N=c.skimwords_weight||!1;D=c.skimwords_color||!1;z=c.skimlinks_tracking||!1;ca=c.skimlinks_site||!1;Sa=c.skimlinks_domain||"go.redirectingat.com";Ta=(O=c.skimlinks_google||!1)||"skimout";T=c.skimlinks_target||!1;sa=c.sl_test||!1;U=c.skimlinks_exclude||[];ta=c.skimlinks_noright||!1;ua=c.skimlinks_exrel||!1;E=y.hostname.replace(da,
"");va=c.skimlinks_byrel||!1;A=c.skimlinks_pub_id||"";Ua=c.skimlinks_maxproducts||3;ea=c.noskimproducts||!1;Va=c.noskim||c.noskimlinks||!1;Wa=c.noskim||!1;V=c.noskimwords||!1;Xa=c.noimpressions||!1;G=c.force_location||c.location.href;Ya=c.skimwords_hover_name||"dark";H=c.skimwords_instant||!1;Za=c.skimwords_horizontal_distance||0;$a=c.skimwords_vertical_distance||0;ab=c.skimwords_block_ie7||!1;I=c.skimlinks_blocked_tag||!1;wa=c.skimwords_no_limit||!1;xa=c.skimwords_debug||0;ya=c.skimwords_force_country||
!1;za=c.skimwords_title||!1;c.skimwords_instant_api_location&&(na=R=c.skimwords_instant_api_location);c.skimwords_css_location&&(oa=c.skimwords_css_location);if(S||ba)H=!0;I&&(I=I.toLowerCase());W=c.skimlinks_included_classes||[];X=c.skimlinks_included_ids||[];o.pub=A;o.pag=G;o.uc=z}function bb(){var a=oa+Ya;f("<link rel='stylesheet' type='text/css' href='"+(a+".css")+"' />").appendTo("head")}function Fb(){return Math.round(Math.random())-0.5}function P(a,b,d){d=d||{};d.charset||(d.charset="utf-8");
d.target||(d.target=this);return function(a,b,d){var h=d.charset,g=d.target,d=d.async,f=g.document,j=f.getElementsByTagName("head")[0],l=f.createElement("script"),c=!1;l.type="text/javascript";l.charset=h;l.onload=l.onreadystatechange=function(){var a=this.readyState;if(!c&&(!a||"complete"===a||"loaded"===a))l.onload=l.onreadystatechange=null,c=!0,b.call(g)};l.async=!1!==d;l.src=a;j.appendChild(l)}.call(this,a,b||function(){},d)}function Gb(a){var b=null;if(f)a(f);else{try{b=c.jQuery}catch(d){}b&&
b.fn&&b.fn.jquery&&b.fn.jquery>=Ma?(f=J=b,a(f)):P(Na,function(){f=J=c.jQuery.noConflict(!0);a(f)},{})}}function cb(a){var b=[],d=0,e;for(e in a)"undefined"!=a[e]&&(b[d]=e,d++);b.sort(Fb);return b}function Hb(a){var b=a.html().slice(0,4);("http"===b||"www."===b)&&a.prepend("<span style='display:none!important;'>&nbsp;</span>")}function Y(a){var b="{",d=0,e="",k;for(k in a)0<d&&(b+=","),e="page"!=k&&"object"==typeof a[k]?Y(a[k]):'"'+a[k]+'"',b+='"'+k+'":'+e,d++;return b+"}"}function Aa(){if(!Xa){db=
(new Date).getTime();var a=db-eb;o.slc=fb;o.swc=gb;o.jsl=a;o.guid=Q;phrase_data=o.phr;o.phr=[];var b=pa+"track.php?data=",d=Y(o).replace(/http:/g,""),e=encodeURIComponent(d).length,k=0,m=1,h=J.browser.msie?1960:7960;f(phrase_data).each(function(a,f){phrase_string=Y(f).replace(/http:/g,"");current_string=0!=k?",":"";current_string+='"'+k+'":'+phrase_string;if(e+encodeURIComponent(current_string).length<h)d=d.replace('},"pub"',current_string+'},"pub"'),e=encodeURIComponent(d).length;else{var j=b+encodeURIComponent(d);
(2E3>j.length||!J.browser.msie&&8E3>j.length)&&P(j,!1,{async:!0});o.t=0;d=Y(o).replace(/http:/g,"");current_string=current_string.replace('"'+k+'":','"0":');d=d.replace('},"pub"',current_string+'},"pub"');e=encodeURIComponent(d).length;k=0;m++}k++});a=b+encodeURIComponent(d);(2E3>a.length||!J.browser.msie&&8E3>a.length)&&P(a,!1,{async:!0})}}function Ib(a,b){u=f(a).mouseenter(function(){C=!0}).mouseleave(function(){fa();C=!1});u.appendTo(Jb);var d=u.find(".flyover2-body");d.html(b);d.find(".skimwords-hover-link").click(hb).bind("contextmenu",
ib);d.find(".skimwords-ebay-link").click(jb).bind("contextmenu",jb);u.find(".flyover2-close").click(function(){fa();C=!1});d.find(".flyover2-row").not(".first").hover(function(){f(this).addClass("flyover2-row-hover")},function(){f(this).removeClass("flyover2-row-hover")});d.find(".flyover2-box-container").hover(function(){f(this).addClass("flyover2-box-container-hover")},function(){f(this).removeClass("flyover2-box-container-hover")})}function fa(){if(c.skimwords_persistent_flyover)return!1;c.setTimeout(function(){if(!C&&
u){var a=kb;lb=(new Date).getTime();var b={};b.dur=lb-mb;b.pub=A;b.pag=G;b.guid=Q;b.gid=f(a).attr("data-group-id");b.phr=f(a).text();b.url=f(a).attr("href");b.ver=w;b.pc=u.find(".merc-link").size();a=pa+"hover.php?data="+encodeURIComponent(Y(b));P(a,!1,{async:!0});u.fadeOut("fast").slideUp();u.remove();C=u=!1}},Oa)}function Kb(a,b,d,e,k){a.attr("data-flyover",Ba);a.mouseenter(function(m){Ca=setTimeout(function(){var h=Lb(Mb,{id:d,multiclass:e?"flyovermulti":"",hover_title:k?k:""});u||Ib(h,b,e);var h=
m.pageX,g=m.pageY,n=u.width(),j=u.height(),l=f(s).width();f(s).scrollTop();var c=0,h=h-n/2;h+c+n>l&&(c=0-n);u.css({top:g+"px",left:h+"px",marginTop:0-j-5+"px",marginLeft:c+"px"});C||u.fadeIn("fast");mb=(new Date).getTime();kb=a;C=!0},500)}).mouseleave(function(){Ca&&clearTimeout(Ca);fa();C=!1});Ba++}function Nb(a){a=a.split(".");a[0]=a[0].split("").reverse().join("");a[0]=a[0].replace(/(\d{3})(?!,)/g,"$1,");a[0]=a[0].split("").reverse().join("");a[0]=0==a[0].indexOf(",")?a[0].substring(1):a[0];return a.join(".")}
function nb(a){function b(a,b,e,d,k,h,g){return'<a href="'+e.url+'" class="'+(d||"")+' skimwords-link skimwords-hover-link" data-skim-creative="'+g+'" data-skim-product="'+h+'" data-skimwords-word="'+k+'" data-skimwords-id="'+e.product_id+"X"+e.merchant_id+'" title="'+b+'" target="_blank" border=0>'+a+"</a>"}function d(a,e,d,k){return'<div class="flyover2-merc-section"><span class="flyover2-merc">'+b(a.merchant_name,"",a,"merc-link flyover2-clickable",e,a.product_id,"2"+w+"3"+k)+'</span></div><div class="flyover2-price">'+
b(u+a.price,"",a,"flyover2-clickable",e,a.product_id,"2"+w+"3"+k)+"</div>"+b("",d,a,"flyover2-arrow product-link",e,a.product_id,"2"+w+"2"+k)+"<br />"}if(a)for(var e=f(".skimwords-link"),k=0,m=e.length;k<m;k++){var h=e[k],g=parseInt(f(h).attr("data-group-id")),h=f(h),n=h.attr("data-skimwords-id"),j=h.attr("data-skimwords-word");h.text();var l=parseInt(h.attr("data-skim-creative"))%10,c=0,r="",x,ga=!0,v,K,B;if(g){if(K=a.groups[g]){x=0;v=!1;var r=[],s="The availability and pricing displayed are not guaranteed and are subject to change.",
ga=!0;for(B in K)if(K.hasOwnProperty(B)&&K[B].mt){v=!0;break}for(B in K)if(K.hasOwnProperty(B)){var t=K[B];if(v){if(ga=!1,!t.mt)continue}else-1!==t.url.indexOf("ebay.")&&(ga=!1);1E7<t.product_id&&6!=parseInt(l)?B=t.product_id-1E7:(parseInt(l),B=t.product_id);var o=B==n,q=v?73:63;if(o||x<Ua&&t.price&&" "!=t.price){var p="",u="$",c=1;x++;h.attr("title","");t.price=Nb(t.price.toString());full_title=t.title;t.title.length>q&&(t.title=t.title.substr(0,q-3)+"...");if(t.country)if("GB"===t.country)u="&pound;";
else if("DE"==t.country)var s=String.fromCharCode(252),q=String.fromCharCode(246),y=String.fromCharCode(228),z=String.fromCharCode(196),s="Die Verf"+s+"gbarkeit der Produkte und der ver"+q+"ffentlichte Preis werden nicht garantiert. Preis"+y+"nderungen und "+z+"nderung der Verf"+s+"gbarkeit vorbehalt.",u="&euro;";w=v?"03":"02";if(o||v)p='<div class="flyover2-row '+(o&&!v?"first":"")+'">'+(o?"<div class='flyover2-close nowidth'></div>":"")+b('<img src="'+t.image+'_thumb" style="border:0px !important;" title="'+
full_title+'" />',"",t,"image",j,B,"2"+w+"1"+l)+b(t.title,full_title,t,"product-link flyover2-link",j,B,"2"+w+"2"+l)+(v?'<div class="flyover2-box-container">'+d(t,j,full_title,l)+"</div>":"")+"</div>";v||(p+='<div class="flyover2-row '+(o?"flyover2-row-main":"")+'">'+d(t,j,full_title,l)+"</div>");o?r.splice(0,0,p):r.push(p)}}ga&&(n="_sacat=See-All-Categories&_nkw="+j,skim_gets="&skimlinks_search_product=ebay&skimlinksurl="+encodeURIComponent("http://www.ebay.com/sch/i.html?")+"&skimlinkspubid="+A,
naked_link="http://www.ebay.com/sch/i.html?"+n,ebay_link="http://go.redirectingat.com/forms.php?"+n+skim_gets,r.push('<div class="flyover2-row"><div class="flyover2-search-section"><a href="'+naked_link+'" data-skimlinks-href="'+ebay_link+'" target="_blank" class="search-link flyover2-clickable skimwords-ebay-link" title="Search on eBay">Search on eBay</a></div><a href="'+naked_link+'" data-skimlinks-href="'+ebay_link+'" target="_blank" class="flyover2-arrow flyover2-clickable skimwords-ebay-link" title="Search on eBay"></a></div>'));
r=r.join("")}c&&!(f.browser.msie&&"7.0">f.browser.version)&&f.support.boxModel&&Kb(h,r,g,v,s)}}}function Ob(){var a=ba?"standard":S?"lite":"";if(f.browser.msie)if(c.XDomainRequest){var b=new XDomainRequest;b&&(b.open("POST",R),b.onload=function(){var a={};try{a=JSON.parse(b.responseText)}catch(d){a=eval("("+b.responseText+")")}ha(a)},b.onerror=function(){},b.onprogress=function(){},b.ontimeout=function(){},b.async=!0,b.send("data="+encodeURIComponent('{"instant":"1","pubcode":"'+A+'","page":"'+G+
'"}')+"&filter="+a+"&content="+encodeURIComponent(L)))}else H=!1,Z("skimwordsDataCallback");else try{f.ajax({url:R,type:"POST",async:!0,crossDomain:!0,data:{data:'{"instant":"1","pubcode":"'+A+'","page":"'+G+'"'+(ya?',"force_country":"'+ya+'"':"")+"}",debug:xa,filter:a,content:L},success:function(a){var b={};try{b=JSON.parse(a)}catch(d){b=eval("("+a+")")}ha(b)},error:function(){H=!1;Z("skimwordsDataCallback")},complete:function(){}})}catch(d){H=!1,Z("skimwordsDataCallback")}}function ia(a,b){function d(a){var b=
a.nodeName===e?f.trim(a.nodeValue):null;return b?(p.push(a),m++,10>m?h.push(b):(m=0,h.push(b+"\n"),L+=h.join(" SKMLNKS "),h=[]),!0):!1}0==a.length&&(a[0]="body");b.push("div[class=widget-content]");b.push("div[class=googleAdText]");b.push("div[id=ad]");b.push("div[id=banner]");b.push("div[id=advertisement]");b.push("div[id=adv_container]");b.push("div[class=ad]");b.push("div[class=banner]");b.push("div[class=advertisement]");b.push("div[class=ad_container]");-1!=y.href.indexOf(".google.")?(b.push("td[class=gac_c]"),
b.push("table[id=mbEnd]"),b.push("span[id=taw]"),b.push("td[class=std]"),b.push("table[class=gssb_e]")):-1!=y.href.indexOf(".yahoo.")?(b.push("ul[class=spns reducepx-spnslist]"),b.push("ul[class*=reducepx-spnslist]"),b.push("ul[id=east]")):-1!=y.href.indexOf(".aol.")?(b.push("div[class=sllLink]"),b.push("div[class=n]")):-1!=y.href.indexOf(".bing.")&&(b.push("div[class=sb_adsW]"),b.push("div[id=sidebar]"));if(!p.length)for(var e=s.createTextNode("").nodeName,k=[],m=0,h=[],g=0,n=a.length;g<n;g++)for(var j=
f(a[g]),l=0,c=j.length;l<c;l++){k.push(j[l]);for(h=[];0<k.length;)if(node=k.shift())if(node.hasChildNodes()){children_to_callback=[];for(i=0,n=node.childNodes.length;i<n;i++)(child=node.childNodes[i])&&child.nodeName&&!d(child)&&-1!==",p,section,body,div,span,ul,ol,li,table,tbody,td,tr,th,tfoot,col,colgroup,em,strong,big,small,blockquote,cite,b,dl,dfn,dd,dt,ins,form,legend,noframes,pre,noscript,center,font,i,article,".indexOf(","+child.nodeName.toLowerCase()+",")&&Da(J(child),"skimwords",!0)&&k.push(child)}else d(node);
L+=h.join(" SKMLNKS ")+"\n";h=[]}}function ob(a){return a.replace(/[-[\]{}()*+?.,\\^$|#]/g,"\\$&")}function pb(a,b,d,e,k,f,h,g,n,j){var l=a.word.split(" "),c=ob(a.word);za&&(a.title=za);a.title="de"==Ea.toLowerCase()?"Shopping link hinzugef\u00fcgt von SkimWords":"Shopping link added by SkimWords";if("cn"===b||"ko"===b||"ja"===b)b="(?:"+c+")",d='<a href="'+a.link+'" class="skimwords-link" target="_blank" style="'+d+" "+e+" "+k+" "+f+' " data-skimwords-id="'+h+'" data-skimwords-word="'+encodeURIComponent(a.word)+
'" data-group-id="'+g+'" data-skim-creative="'+j+'" data-skim-product="'+n+'" title="'+a.title+'">$1</a>';else if((1<l.length||"4"!==a.action_type||1===l.length&&/(?:\d[a-z])|(?:[a-z]|\d)/i.test(l[0]))&&(2>l.length||/[a-zA-Z]+/.test(a.word)))b="(?:^|[\\s]+)(?:\\\\;\\.|,\\'\\\"\\(\\)\\/\\?])?("+c+")(?:\\'s)?(?:[\\\\;,\\.\\'\\\"|\\(\\)\\/\\?])*(?:[\\s]+|$)",d='$1$2<a href="'+a.link+'" class="skimwords-link" target="_blank" style="'+d+" "+e+" "+k+" "+f+' " data-skimwords-id="'+h+'" data-skimwords-word="'+
encodeURIComponent(a.word)+'" data-group-id="'+g+'" data-skim-creative="'+j+'" data-skim-product="'+n+'" title="'+a.title+'">$3$4</a>$5$6';else return null;a=b.replace(/\?:/g,"");return{search_regex:RegExp(b,"i"),repl_regex:RegExp(a,"i"),repl_text:d}}function qb(a,b,d,e){var k,c,h,g,n,j;if(!a)return!1;d=s.createTextNode("").nodeName;k=a.data;for(var l=0,u=Fa.length;l<u;l++)if(g=Fa[l],b[g].group_id?(c=b[g].group_id,h="2"+w+"0"+b[g].action_type):(c=0,h="1"+w+"0"+b[g].action_type),j=b[g].id,n=1E7<parseInt(j)&&
6!=b[g].action_type?j-=1E7:0,h=pb(b[g],Ga,D,N,F,M,j,c,n,h),c=a&&0<b[g].limit&&h&&h.search_regex.test(k)){repl_regex=h.repl_regex;k=h.repl_text;if(!(0==b[g].limit||!wa&&$==q.maxkeywords)){$++;b[g].limit--;rb++;l={};l.w=b[g].word;l.lp=b[g].link;0==b[g].group_id?(l.t="1"+w+"0"+b[g].action_type,l.pid=0):(l.t="2"+w+"0"+b[g].action_type,l.pid=6==b[g].action_type?g:g-1E7);-1==f.inArray(l,o.phr)&&o.phr.push(l);b=a.data.replace(repl_regex,k);g=s.createElement("span");k=s.createDocumentFragment();for(g.innerHTML=
b;g.firstChild;)g.firstChild.nodeName==d?(obj=k.appendChild(g.firstChild),p.push(obj)):obj=k.appendChild(g.firstChild);-1!=e&&(p[e]=0);f(a).replaceWith(k)}return!1}}function sb(a,b){var d,e;if(wa||$<q.maxkeywords){d=cb(b);for(var k=0,c=d.length;k<c;k++){var h=d[k];if(0===a||h==a||0>a&&h!=-a){Fa=cb(b[h]);var g=p.length,n=Math.ceil(g/2);for(e=0;e<=n;e++){var j=f(p[e]).parent().eq(0);qb(p[e],b[h],j,e);e!=n&&(j=f(p[g-1-e]).parent().eq(0),qb(p[g-1-e],b[h],j,g-1-e));g=p.length;n=Math.ceil(g/2)}}}}}function Pb(a){for(var b,
d=[],e=0,k=p.length;e<k;e++){b=p[e];var f=b.nodeValue,h=b.parentNode;if(h){var g=Qb(b,a);g.sort(function(a,b){return a.start-b.start});if(g&&g.length){for(var c=s.createDocumentFragment(),j=0,l=0,o=g.length;l<o;l++){var r=g[l],x=s.createElement("span");x.className="skimwords-potential";j=s.createTextNode(f.substring(j,r.start));c.appendChild(j);x.innerHTML=r.text;c.appendChild(x);j={};j.node=x;j.match=r;d.push(j);j=r.start+r.text.length}f=s.createTextNode(f.substring(j));c.appendChild(f);h.replaceChild(c,
b)}}}return d}function Qb(a,b){var d,e,k,f,h,g,c,j;overlapping_matches=[];matches=[];if(!a)return matches;s.createTextNode("");d=a.data;(function(){if(ja)j=ja;else{j=[];for(var a in b)if(b.hasOwnProperty(a)){var d=b[a],c;for(c in d)if(d.hasOwnProperty(c)){var g=d[c];g.group_id?(e=g.group_id,k="2"+w+"0"+g.action_type):(e=0,k="1"+w+"0"+g.action_type);h=g.id;f=1E7<parseInt(h)&&6!=g.action_type?h-=1E7:0;var l=pb(g,Ga,D,N,F,M,h,e,f,k);l&&j.push({phrase:g,repl_regex:l.repl_regex,replacement:l.repl_text,
regex:l.search_regex})}}j.sort(function(a,b){var d=parseInt(a.phrase.action_type),e=parseInt(b.phrase.action_type),c=e-d;return!c?b.phrase.word.length-a.phrase.word.length:4===e?1:4===d?-1:c});ja=j}})();for(var l=0,o=j.length;l<o;l++){var r=j[l];phrase=r.phrase;c={};c.start=-1;c.phrase=phrase;c.text=null;(function(){if(a&&0<phrase.limit){var b=d.match(r.regex);if(b){var e=b[0].indexOf(b[1]);c.start=b.index+(-1!==e?e:0);c.text=d.substring(c.start,c.start+b[1].length)}else c.start=-1}})();g=0;-1!=c.start&&
c.text&&(g=1);g?(c.repl_regex=r.repl_regex,c.replacement=r.replacement,overlapping_matches.push(c)):c.start=-1}(function(){if(overlapping_matches&&overlapping_matches.length){overlapping_matches.sort(function(a,b){return b.text.length-a.text.length});for(var a=overlapping_matches.length,b=[],d=0;d<a;d++){var e=overlapping_matches[d],c={},k=!0;c.lower=e.start;c.upper=e.start+e.text.length;for(var g=0,f=b.length;g<f;g++){var h=b[g];if(c.lower>=h.lower&&c.lower<=h.upper||c.upper<=h.upper&&c.upper>=h.lower){k=
!1;break}}k&&(matches.push(e),b.push(c))}overlapping_matches=b=null}})();return matches}function Rb(a,b){if(a.length){var d,e,c,m,h=[],g=0,b=b||0,n=f.browser.msie&&"9.0">f.browser.version;n&&(c=f("body").text().length,3E4<c?b=Math.ceil(c/1E4):n=!1);for(c=0,m=a.length;c<m;c++){e=a[c];d=e.node;e=e.match;var j=!1;if("1"===e.phrase.action_type||"2"===e.phrase.action_type)j=!0;n&&(j=!0);"17075X740592"===A&&f(d).parents(".atma-norules").length&&(j=!0);if(Da(f(d),"skimwords")&&(j||Sb(d,h))){g++;j=e.phrase;
if(0!=j.limit){$++;j.limit--;rb++;var l={};l.w=j.word;l.lp=j.link;0==j.group_id?(l.t="1"+w+"0"+j.action_type,l.pid=0):(l.t="2"+w+"0"+j.action_type,l.pid=6==j.action_type?j.id:j.id-1E7);-1==f.inArray(l,o.phr)&&o.phr.push(l);e=(d.data?d.data:d.childNodes[0].data).replace(e.repl_regex,e.replacement);j=s.createElement("span");l=s.createDocumentFragment();for(j.innerHTML=e;j.firstChild;)void 0==j.firstChild.nodeName?(obj=l.appendChild(j.firstChild),p.push(obj)):obj=l.appendChild(j.firstChild);f(d).replaceWith(l)}if(b&&
g>=b)break}}}}function Ha(a){var b=0,d=0;if(a.offsetParent){do b+=a.offsetLeft,d+=a.offsetTop;while(a=a.offsetParent)}return{x:b,y:d}}function Tb(a,b,d){var e=0,c=a.length-1,f,h;for("function"!==typeof d&&(d=cmp);e<=c;)if(f=Math.floor((c+e)/2),h=d(b,a[f]),0<h)e=f+1;else if(0>h)c=f-1;else return{found:!0,index:f};return{found:!1,index:e}}function Sb(a,b){function d(a,b){Math.abs(a.x-b.x)<=p&&Math.abs(a.y-b.y)<=v&&(q=!0);return a.y===b.y?a.x-b.x:a.y-b.y}var e,c,f,h,g,n,j,l,o,r,x;f=Ha(a);var p=Za,v=
$a,q=!1;if(!p&&!v)return!0;p=!p?0:p;v=!v?4:v;c=[{test:function(a){return 0<a&&a<b.length},count:function(a){return a-1}},{test:function(a){return a<b.length},count:function(a){return a+1}}];e=s.createElement("span");e.style.position="absolute";a.nextSibling?a.parentNode.insertBefore(e,a.nextSibling):a.parentNode.appendChild(e);e=Ha(e);e=s.createElement("span");e.style.position="absolute";a.nextSibling?a.parentNode.insertBefore(e,a.nextSibling):a.parentNode.appendChild(e);e=Ha(e);h=[f,e];for(g=0;g<
h.length;g++){n=h[g];if(q)break;j=Tb(b,n,d);for(r=0;r<c.length&&!(x=c[r],q);r++)for(l=x.count(j.index);x.test(l);l=x.count(l)){o=b[l];if(!(Math.abs(n.y-o.y)<=v))break;if(Math.abs(n.x-o.x)<=p){q=!0;break}}}if(q)return!q;c=f.y===e.y?f.x-e.x:f.y-e.y;0<c?c=e:0>c?(c=f,f=e):(c=f,f=null);j.index===b.length?(b.push(c),f&&b.push(f)):f?b.splice(j.index,0,c,f):b.splice(j.index,0,c);return!q}function ha(a){if(q=a)if(q.guid&&(Q=q.guid),q.lang&&(Ga=q.lang.toLowerCase()),ia(q.includes,q.excludes),p.length&&f(q.words).size()){a=
1;if(f.browser.mozilla){var b=/Firefox\/(\d.\d)/.exec(navigator.userAgent);b&&2<=b.length&&3.7>=parseFloat(b[1])&&(a=0)}else f.browser.msie&&"8.0">f.browser.version&&(a=0);a?(a=Pb(q.words),Rb(a,q.maxkeywords)):(sb(4,q.words),sb(-4,q.words));if(f.browser.msie&&"9.0">f.browser.version){var a=f(".skimwords-link"),d,e,k,m=/^\s/;for(b=0,d=a.length;b<d;b++){k=a[b];if((e=k.previousSibling)&&e.nodeValue&&e.nodeValue.length&&m.test(e.nodeValue[e.nodeValue.length-1]))e.nodeValue+=" ";if((e=k.nextSibling)&&
e.nodeValue&&e.nodeValue.length&&m.test(e.nodeValue[0]))e.nodeValue=" "+e.nodeValue}}gb=f(".skimwords-link").length;c.setTimeout(function(){for(var a=f(".skimwords-link"),b,d=0,e=a.length;d<e;d++)b=f(a[d]),b.click(hb),b.bind("contextmenu",ib);if("17075X740592"===A){a=f(".atma-norules a.skimwords-link");d=0;for(e=a.length;d<e;d++)a[d].style.color="#C9C7C7 !important",a[d].style.fontStyle="normal !important"}},10)}ea||(q.groups?(aa||(bb(),aa=!0),nb({groups:q.groups})):(tb=f(s),tb.ready(function(){var a=
f("a[href]:not(:has(img))"),b={},d={},e={};f([]);f([]);for(var c=0,k=a.length;c<k;c++){var m=a[c],o=m.className,q=m.href,p=m.hostname.replace(da,""),m=m.getAttribute("data-skimwords-id");if(-1==q.indexOf(E)||!E)if(o&&-1!=o.indexOf("skimwords")){if(p&&!d[p]&&(ub.push(p),d[p]=!0),m){o=m.split(" ");q=0;for(p=o.length;q<p;q++)if(m=o[q],(m=f.trim(m))&&!e[m])vb.push(m),e[m]=!0}}else p&&!b[p]&&(wb.push(p),b[p]=!0)}f(".skimwords-link");f('a[href^=http://]:not([href*="'+E+'"],[class=skimwords-link])');aa||
(bb(),aa=!0);a='{"groups": [';b=0;d=f(".skimwords-link");e=0;for(c=d.length;e<c;e++)k=d[e],o=f(k).attr("data-group-id"),parseInt(o)&&"0"!=parseInt(o)&&(0!=b&&(a+=","),a+='"'+f(k).attr("data-group-id")+'"',b++);b&&P(Pa+"?callback=productDataCallback&data="+(a+"]}"))})));Aa()}function Z(a){if(S||ba)var a="instantDataCallback",b=S?"&filter=lite":"&filter=standard";else b="";if(H)var d=encodeURIComponent('{"instant":"1","page":"'+G+'"}'),e=R;else d=encodeURIComponent('{"page":"'+G+'"}'),e=na;P(e+"?callback="+
a+"&data="+d+"&debug="+xa+b)}function Ub(){var a;if("undefined"===typeof ka){ka={};a=U.concat(Qa);for(var b=0,d=a.length;b<d;b++){var e=a[b];ka[e]=e.length}}return ka}function xb(a){var b=!1,d=Ub(),e=a.length;f.each(d,function(d,c){if(0===d.indexOf("*")){if(d=d.slice(1),c-=1,-1!==a.lastIndexOf(d)&&a.lastIndexOf(d)===e-c)return b=!0,!1}else if(a===d)return b=!0,!1});return b}function Ia(a){var b;if(!(b=!a))if(!(b=va&&a===va)){if("undefined"===typeof la){la={};b=ua?[ua]:[];b=b.concat(qa);for(var d=
0,e=b.length;d<e;d++)la[b[d]]=!0}b=!la[a]}return b}function Vb(a){var b=c.pageTracker,d=c.urchinTracker,a="/"+Ta+"/"+a;b&&b._trackPageview?b._trackPageview(a):d&&d(a)}function ma(a,b){var d,e,c;a&&(e=a[0],d=e.href,(c=a.data("skimlinks-href"))||(c=a.hasClass("skimwords-link")?"http://"+La+"/?id="+A+(z?"&xcust="+z:"")+"&xs=2&url="+encodeURIComponent(d)+"&xguid="+Q+(void 0!==a.attr("data-skimwords-word")?"&xword="+a.attr("data-skimwords-word"):"&xword=")+(void 0!==a.attr("data-skim-creative")?"&xcreo="+
a.attr("data-skim-creative"):"&xcreo=0")+(void 0!==a.attr("data-skim-product")?"&xpid="+a.attr("data-skim-product"):"&xpid=0")+"&sref="+encodeURIComponent(y):Da(a,"skimlinks")?"http://"+Sa+"/?id="+A+(ca?"&site="+ca:"")+(sa?"&test="+sa:"")+(z?"&xcust="+z:"")+"&xs=1&url="+encodeURIComponent(d)+"&xguid="+Q+(a&&void 0!==a.attr("data-skim-creative")?"&xcreo="+a.attr("data-skim-creative"):"&xcreo=0")+"&sref="+encodeURIComponent(y):d,a.data("skimlinks-href",c)),b&&Vb(d),a.data("skimlinks-orig-link")||a.data("skimlinks-orig-link",
d),e.href=c,setTimeout(function(){e.href=a.data("skimlinks-orig-link")},100))}function Ja(a,b){var d=a.target;anchor=f(d);d.href||(d=a.currentTarget,anchor=f(d));ma(anchor,b)}function ib(a){Ja(a,!1)}function hb(a){Ja(a,O)}function yb(a){Ja(a,O)}function jb(a){var b=a.target;anchor=f(b);b.href||(b=a.currentTarget,anchor=f(b));anchor.data("skimlinks-href",anchor.attr("data-skimlinks-href"));ma(anchor,O)}function zb(a){a=a.target;f(a);a=encodeURIComponent('{"pubcode":"'+A+'","referrer":"'+y+'","site":"'+
ca+'","url":"'+a.href+'","custom":"'+z+'","product":"1"}');f.getScript(ra+"?call=track&data="+a)}function Wb(a,b){var d=!1;b.merchant_domains&&f.each(b.merchant_domains,function(b,c){if(a==c)return d=!0});return d}function Xb(a){if(W.length)for(var b=0,d=W.length;b<d;b++)if(a.parents("."+W[b]).length)return!0;if(X.length){b=0;for(d=X.length;b<d;b++)if(a.parents("#"+X[b]).length)return!0}return!1}function Yb(a){if(!I)return!0;a=a[0].previousSibling;if(!a)return!0;var a=f.trim(J(a).text().toLowerCase()),
b=a.indexOf("["+I+"]");return!(-1!==b&&b+(I.length+2)===a.length)}function Ab(){if(V||Wa)return Bb;D&&(D=-1==D.indexOf("#")?"color:#"+D+" !important;":"color:"+D+" !important;");N=N?"font-weight: "+N+" !important;":"";M=M?"font-style: "+M+" !important;":"";F="double"==F?"border-bottom: 1px double !important;":F?"text-decoration: "+F+" !important;":"text-decoration: underline !important;";H?Z("instantDataCallback"):Z("skimwordsDataCallback")}function Ka(){if(Va)return V?Aa():Ab(),Bb;U=U.concat(qa);
c.skimlinks_site&&U.push(c.skimlinks_site);z&&!Zb.test(z)&&(z=!1);for(var a=f("a[href]"),b=[],d={},e=0,k=a.length;e<k;e++){var m=a[e],h=f(m),g=m.hostname.replace(da,""),m=f.trim(m.href),h=h.attr("rel");Cb.test(m)&&-1===g.indexOf(E)&&-1===E.indexOf("."+g)&&!xb(g)&&Ia(h)&&g&&!d[g]&&(b.push(g),d[g]=!0)}a=encodeURIComponent;d='{"pubcode":"'+A+'","domains":';e="";if(b.length){k=0;for(g=b.length;k<g;k++)e+='"'+b[k]+'",';e=e.slice(0,-1)}b=a(d+("["+e+"]")+"}");f.getScript(ra+"?callback=skimlinksApplyHandlers&data="+
b);return!0}function Db(){ub=[];vb=[];wb=[];merchantLimits=[];totalDisplayed=f(".skimlinks-icon-link").size();p=[];L="";Ba=0;Ra();Ka()}function Eb(){for(var a=f(".skimwords-link"),b=$=0,d=a.length;b<d;b++){var c=f(a[b]);c.after(c.text());c.remove()}}var Lb=function(){var a=RegExp("{{([a-z0-9_][\\.a-z0-9_]*)}}","gi");return function(b,d){return b.replace(a,function(a,b){for(var c=b.split("."),f=c.length,g=d,n=0;n<f;n++)if(g=g[c[n]],void 0===g&&console.log("tim: '"+c[n]+"' not found in "+a),n===f-1)return g})}}(),
c=this,s=c.document;Na="https://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js";Ma="1.5.5";La=c.skimlinks_domain||"go.redirectingat.com";Qa="*doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(",");qa=["noskim","norewrite"];R="http://i.skimresources.com/api/index.php";na="http://d.skimresources.com/api/index.php";Pa="http://d.skimresources.com/api/product.php";ra="http://r.skimresources.com/api/";pa=
"http://t.skimresources.com/api/";oa="http://s.skimresources.com/css/flyover-";Oa=250;var Xa,V,Wa,Va,ea,Ua,A,Ea="",Q="",Bb=function(){},da=/^www\./,Cb=/^\/\/|https?:\/\//,Zb=/^[a-z0-9_\\|]+$/i,y,ka,la,W=[],X=[],eb=null,db=null,mb=null,lb=null,E,va,ua,ta,U,sa,T,O,Ta,Sa,ca,z,fb=0,D,N,M,S,ba,F,H,gb=0,w="02",p=[],L="",Ya,Ga="en",Za,$a,ab,I,wa,xa,za,ya,q,G,rb=0,$=0,Fa,aa=!1,ja,Mb="<div id='flyover2-{{id}}' class='flyover2-outer {{multiclass}}'><div class='flyover2-body'></div><div class='flyover2-bottom'><a class='bottom-link' target='_blank' href='http://www.skimlinks.com/?ref=flyover' ref='hoverover'></a><a class='bottom-link-2' title='{{hover_title}}'></a></div></div>",
u,Ba=0,kb,C=!1,Ca=null,tb,Jb=s.body,ub=[],vb=[],wb=[],o={pag:"",phr:[],pub:"",slc:0,swc:0,jsl:0,jsf:"",guid:"",uc:"",t:1},f,J;Ra();var Da=function(){var a=/\bnoskim\b/i;return function(b,d,c){var f=b[0].className||"",c=c||!1;return!a.test(f)&&!RegExp("\\b"+ob("no"+d)+"\\b","i").test(f)&&(c||0==b.parents(".no"+d).length&&0==b.parents(".noskim").length)?!0:!1}}();c.skimlinks=Ka;c.mugicPopWin=yb;c.mugicRight=yb;c.skimwordsDataCallback=ha;c.instantDataCallback=function(a){a.country&&(Ea=a.country);if(1==
a.nc){if(a.includes)try{ia(a.includes,a.excludes)}catch(b){ia(["body"],[])}else ia(["body"],[]);Ob()}else 2!=a.nc&&ha(a)};c.skimlinksApplyHandlers=function(a){var b=f("a[href]"),c=0<W.length||0<X.length;a.country&&(Ea=a.country);a.guid&&(Q=a.guid);for(var e=0,k=b.length;e<k;e++){var m=b[e],h=f(m),g=m.hostname.replace(da,""),m=f.trim(m.href),n=h.attr("rel"),j=f.browser.msie;if((!c||Xb(h))&&Yb(h))if(Wb(g,a)){if(Ia(n)){T&&h.attr("target",T);if(j){if(-1!==encodeURIComponent(m).indexOf("%C3%82%C2%A3"))return!0;
Hb(h)}h.click(function(){var a=f(this);ma(a,O)});fb++;ta||h.bind("contextmenu",function(){var a=f(this);ma(a,O)})}}else Cb.test(m)&&-1===g.indexOf(E)&&-1===E.indexOf("."+g)&&!xb(g)&&Ia(n)&&(T&&h.attr("target",T),h.click(zb),ta||h.bind("contextmenu",zb))}V?Aa():Ab()};c.productDataCallback=nb;c.skimlinksReload=Db;c.skimwordsReload=function(){fa();C=!1;ja=null;f("head").find("link[rel=stylesheet]").each(function(){this.href&&-1!==this.href.indexOf("skimlinks.")&&f(this).remove()});aa=!1;Eb();Db()};(function(){eb=
(new Date).getTime();-1==y.href.indexOf("https://")&&Gb(function(a){a.browser.msie&&"8.0">a.browser.version&&(ab?V=!0:(a=/Windows NT (\d.\d)/.exec(navigator.userAgent))&&2<=a.length&&6>=parseFloat(a[1])&&(ea=!0));ea&&(w="00");Eb();Ka()})})()})();