var googleAdClient="pub-6409535612800042",TMNadsenseCount=0;
function setStyle(){styles="<style>\n";styles+=".tmnAdsenseContainer  {float:left;}\n";styles+=".tmnAdsByGoogleCont   {float:left;}\n";styles+=".tmnAdsByGoogle       {font-size:12px; float:left; text-align:right;}\n";styles+=".tmnAdsByGoogle a     {color:#777777; text-decoration:none; font-size:11px;}\n";styles+=".tmnAdsenseAdCont     {float:left; overflow:hidden;}\n";styles+=".tmnAdsenseAdTitle    {margin-bottom:5px;}\n";styles+=".tmnAdsenseAdTitle a  {text-decoration:none; font-size:15px; color:#4444DD; font-weight: bold;}\n";styles+=
".tmnAdsenseAdDescCont {}\n";styles+=".tmnAdsenseAdDesc     {color:#000000; font-size:11px;}\n";styles+=".tmnAdsenseAdLink     {}\n";styles+=".tmnAdsenseAdLink a   {color:#999999; text-decoration:none; font-size:11px;}\n";styles+="</style>\n";document.write(styles)}setStyle();
var TmnAdsense={checkHex:function(a){return a.match(/^(?:#)?([0-9A-Fa-f]{6})$/)},display:function(a){if(TMNadsenseCount<3){TMNadsenseCount++;if(!a)a=TmnAdsense.options;var l=(new Date).getTime();if(!a.width||a.width<100)a.width=100;if(!a.ad_width)a.ad_width=100;if(a.ad_width>a.width)a.ad_width=a.width;if(!a.max_ads||a.max_ads<1)a.max_ads=2;if(a.max_ads>6)a.max_ads=6;if(!a.channel_id)a.channel_id=null;if(!a.col_margin)a.col_margin=0;if(!a.row_margin)a.row_margin=0;if(a.adsbyposition!="topleft")a.adsbyposition=
"bottomright";if(!a.adsbyvertical)a.adsbyvertical=10;a.adsbyhorizontal?a.adsbyhorizontal+=66:a.adsbyhorizontal=66;var b=0,k="";typeof a.adFontFamily=="string"&&(k+="font-family:"+a.adFontFamily+";");var g="";typeof a.adsbyFontSize=="number"&&(g+="font-size:"+a.adsbyFontSize+"px;");typeof a.adsbyFontFamily=="string"&&(g+="font-family:"+a.adsbyFontFamily+";");typeof a.adsbyFontWeight=="string"&&(g+="font-weight:"+a.adsbyFontWeight+";");if(typeof a.adsbyColor=="string"&&(b=TmnAdsense.checkHex(a.adsbyColor)))g+=
"color:#"+b[1]+";";var h='style="';typeof a.titleFontSize=="number"&&(h+="font-size:"+a.titleFontSize+"px;");typeof a.titleFontFamily=="string"&&(h+="font-family:"+a.titleFontFamily+";");typeof a.titleFontWeight=="string"&&(h+="font-weight:"+a.titleFontWeight+";");typeof a.titleDecoration=="string"&&(h+="text-decoration:"+a.titleDecoration+";");if(typeof a.titleFontColor=="string"&&(b=TmnAdsense.checkHex(a.titleFontColor)))h+="color:#"+b[1]+";";var j='style="';typeof a.titleMarginBottom=="number"&&
(j+="margin-bottom:"+a.titleMarginBottom+"px;");typeof a.titlePaddingTop=="number"&&(j+="padding-top:"+a.titlePaddingTop+"px;");var e='style="';typeof a.descFontSize=="number"&&(e+="font-size:"+a.descFontSize+"px;");typeof a.descFontFamily=="string"&&(e+="font-family:"+a.descFontFamily+";");typeof a.descDecoration=="string"&&(e+="text-decoration:"+a.descDecoration+";");typeof a.descLineSpacing=="number"&&(e+="line-height:"+a.descLineSpacing+"px;");if(typeof a.descFontColor=="string"&&(b=TmnAdsense.checkHex(a.descFontColor)))e+=
"color:#"+b[1]+";";typeof a.descFontWeight=="string"&&(e+="font-weight:"+a.descFontWeight+";");var f='style="';typeof a.descMarginBottom=="number"&&(f+="margin-bottom:"+a.descMarginBottom+"px;");var i='style="';typeof a.linkFontSize=="number"&&(i+="font-size:"+a.linkFontSize+"px;");typeof a.linkFontFamily=="string"&&(i+="font-family:"+a.linkFontFamily+";");typeof a.linkDecoration=="string"&&(i+="text-decoration:"+a.linkDecoration+";");if(typeof a.linkFontColor=="string"&&(b=TmnAdsense.checkHex(a.linkFontColor)))i+=
"color:#"+b[1]+";";typeof a.linkFontWeight=="string"&&(e+="font-weight:"+a.linkFontWeight+";");b='style="';typeof a.linkMarginBottom=="number"&&(b+="margin-bottom:"+a.linkMarginBottom+"px;");var c=a.adsOnRow?a.adsOnRow:Math.floor((a.width+a.col_margin)/(a.ad_width+a.col_margin));if(a.adstyle=="twoline")f+="float:left;",b+="float:left;",typeof a.descPaddingTop=="number"&&(f+="padding-top:"+a.descPaddingTop+"px;"),typeof a.linkPaddingTop=="number"&&(b+="padding-top:"+a.linkPaddingTop+"px;"),b+=typeof a.linkPaddingLeft==
"number"?"padding-left:"+a.linkPaddingLeft+"px;":"padding-left:10px;",a.adsbyposition="topleft",c=1,a.ad_width=a.width;if(a.adstyle=="oneline")j+="float:left;",f+="float:left;",b+="float:left;",typeof a.descPaddingTop=="number"&&(f+="padding-top:"+a.descPaddingTop+"px;"),f+=typeof a.descPaddingLeft=="number"?"padding-left:"+a.descPaddingLeft+"px;":"padding-left:10px;",typeof a.linkPaddingTop=="number"&&(b+="padding-top:"+a.linkPaddingTop+"px;"),b+=typeof a.linkPaddingLeft=="number"?"padding-left:"+
a.linkPaddingLeft+"px;":"padding-left:10px;",a.adsbyposition="topleft",c=1,a.ad_width=a.width;if(a.adstyle=="twolineurltop")j+="float:left;",f+="clear:both;",b+="float:left;",typeof a.linkPaddingTop=="number"&&(b+="padding-top:"+a.linkPaddingTop+"px;"),b+=typeof a.linkPaddingLeft=="number"?"padding-left:"+a.linkPaddingLeft+"px;":"padding-left:10px;",c=1,a.ad_width=a.width;d='<script type="text/javascript">\n';d+="<\!--\n";d+="if(typeof(google_adnum) == 'undefined'){\n";d+="var google_adnum = 0;\n";
d+="}\n";d+="function google_ad_request_done(google_ads){\n";d+="var s='';\n";d+="if(google_ads.length == 0){\n";d+="return;\n";d+="}\n";d+="if(google_ads.length != 0){\n";d+="if(google_ads.length<"+c+"\n)";d+="ads_by_width=(google_ads.length)*"+a.ad_width+"+(google_ads.length-1)*"+a.col_margin+"\n";d+="else\n";d+="ads_by_width="+a.ad_width*c+"+("+c+"-1)*"+a.col_margin+"\n";d+="if(ads_by_width>"+a.width+")\n";d+="ads_by_width="+a.width+"\n";d+='s+=\'<div class="tmnAdsenseContainer" style="width: '+
a.width+"px;\">'\n";a.adsbyposition=="topleft"&&(d+='s+=\'<div class="tmnAdsByGoogleCont" style="width: '+a.width+"px;padding-bottom:"+a.adsbyvertical+"px\">'\n",d+="s+='  <div style=\"width:"+a.adsbyhorizontal+'px"class="tmnAdsByGoogle">\'\n',d+="s+='    <a style=\"float:right;"+g+'" href="\' + google_info.feedback_url + \'" class="tmnAdsByGoogle">Ads by Google</a>\'\n',d+="s+='</div>'\n",d+="s+='</div>'\n");d+="var marginR=0;\n";d+="var marginB=0;\n";d+="var numAds="+(c-1)+";\n";d+="var ad_less="+
(c-1)+";\n";d+="for(var i = 0; i < google_ads.length; ++i){\n";d+="marginR=((i < ad_less)?"+a.col_margin+":0);\n";d+="if (i >= ad_less) {ad_less = (ad_less + "+c+");}\n";d+="marginB=(i < ((google_ads.length-1) - numAds)?"+a.row_margin+":0);\n";d+='s+=\'<div class="tmnAdsenseAdCont" style="width: '+a.ad_width+"px;margin-right:' + marginR + 'px; margin-bottom:'+ marginB +'px;"+k+"\">'\n";d+='s+=\'  <div class="tmnAdsenseAdTitle" '+j+"\">'\n";d+='s+=\'    <a class="tmnAdsenseAdTitle" href="\' + google_ads[i].url + \'" '+
h+"\">' + google_ads[i].line1 + '</a>'\n";d+="s+='  </div>'\n";a.adstyle=="twolineurltop"&&(d+='s+=\'    <div class="tmnAdsenseAdLink" '+b+"\">'\n",d+='s+=\'      <a class="tmnAdsenseAdLink" href="\' + google_ads[i].url + \'" '+i+"\">'\n",d+="s+='        <span>' + google_ads[i].visible_url + '</span>'\n",d+="s+='      </a>'\n",d+="s+='    </div>'\n");d+='s+=\'  <div class="tmnAdDescCont" '+f+"\">'\n";d+='s+=\'    <span class="tmnAdsenseAdDesc" '+e+"\">' + google_ads[i].line2 + ' ' + google_ads[i].line3 + '</span>'\n";
d+="s+='  </div>'\n";a.adstyle!="twolineurltop"&&(d+='s+=\'    <div class="tmnAdsenseAdLink" '+b+"\">'\n",d+='s+=\'      <a class="tmnAdsenseAdLink" href="\' + google_ads[i].url + \'" '+i+"\">'\n",d+="s+='        <span>' + google_ads[i].visible_url + '</span>'\n",d+="s+='      </a>'\n",d+="s+='    </div>'\n");d+="s+='</div>'\n";d+="}\n";a.adsbyposition=="bottomright"&&(d+='s+=\'<div class="tmnAdsByGoogleCont" style="clear:both;padding-top:'+a.adsbyvertical+"px;width:'+ads_by_width+'px;\">'\n",d+=
's+=\'  <div class="tmnAdsByGoogle" style="float:right;">\'\n',d+="s+='    <a style=\"float:left;"+g+'" href="\' + google_info.feedback_url + \'" class="tmnAdsByGoogle">Ads by Google</a>\'\n',d+="s+='  </div>'\n",d+="s+='</div>'\n");d+="s+='</div>'\n";d+='if (google_ads[0].bidtype == "CPC") {\n';d+="google_adnum=google_adnum + google_ads.length;\n";d+="}\n";d+="}\n";d+="document.write(s);\n";d+="return;\n";d+="}\n";d+="google_ad_client='"+googleAdClient+"';\n";a.channel_id&&(d+="google_ad_channel='"+
a.channel_id+"';\n");d+="google_ad_output='js';\n";d+="google_max_num_ads='"+a.max_ads+"';\n";d+="google_ad_type='text_html';\n";d+="google_feedback='on';\n";d+="google_skip=google_adnum;\n";d+="--\>\n";d+="<\/script>\n";d+='<script src="http://pagead2.googlesyndication.com/pagead/show_ads.js?'+l+'"><\/script>';document.write(d)}},options:{width:315,ad_width:315,max_ads:4,adsOnRow:1,col_margin:0,titleFontSize:15,titleFontColor:"4444DD",descFontSize:11,descFontColor:"000000",linkFontSize:11,linkFontColor:"999999"}};